### ISSUE TITLE
[Corner case] Unwanted scroll when there are no messages

### ISSUE THREAD

**Issue by daminisatya** [fossasia/susi.ai#1]
![image](https://cloud.githubusercontent.com/assets/6227784/25281600/7a08f412-26cb-11e7-8e10-7f97b07120b2.png)

The scroll must appear only when there are messages overflowing.

**Comment by muskanbararia** [comment]
Can I work on it?

**Comment by daminisatya** [comment]
@muskanbararia Sure!

**Comment by muskanbararia** [comment]
@daminisatya fixed in #2

**Comment by mariobehling** [comment]
Please follow up on this repo: https://github.com/fossasia/chat.susi.ai
