### ISSUE TITLE
Add coverage for chat.susi.ai

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi.ai#1099]
**Actual Behaviour**

The Codacy coverage for this repository is 0%.

**Expected Behaviour**

We should add coverage for this project for better testing of code.

**Screenshots of the issue**

This is displayed on the codacy dashboard for chat.susi.ai -
<img width="250" alt="screen shot 2018-02-16 at 10 04 32 pm" src="https://user-images.githubusercontent.com/31174685/36318583-47d52f82-1366-11e8-9bcb-3472fdf62f7d.png">

**Would you like to work on the issue?**

No, anyone can take this up. 😃

**Comment by mariobehling** [comment]
@DNS-404 Are you going to follow up on your own issue?

**Comment by DNS-404** [comment]
@mariobehling No, anyone who's willing can take this up.

**Comment by mariobehling** [comment]
There are codacy checks at the moment. Therefore closing this.
