### ISSUE TITLE
Susi logo is not aligned with other footer elements

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#13]
Actual Behaviour
susi logo should is shifted upwards with respect to other footer elements.

Expected Behaviour

susi logo should be in alignment with other footer elements

Screenshots of the issue
![footer](https://user-images.githubusercontent.com/32234926/45407159-3a9c6100-b686-11e8-8c22-5ffa26feece2.PNG)

Would you like to work on the issue?
Yes

**Comment by lakshaysharma14** [comment]
@mariobehling @Orbiter I want to work on this. Can you please assign this to me?

**Comment by samagragupta** [comment]
I have made this same issue on https://github.com/fossasia/chat.susi.ai as https://github.com/fossasia/chat.susi.ai/issues/1551 .

As it can be solved there .
