### ISSUE TITLE
Loop through action types and display result for all actions

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi.ai#151]
**Actual Behaviour**

Query "multi3". The sever response contains 3 action types but only result of first is displayed.
Also for map type only first action type is used. 

**Expected Behaviour**
```
"actions": [
      {
        "type": "answer",
        "expression": "Singapore is a place with a population of 3547809. Here is a map: https://www.openstreetmap.org/#map=13/1.2896698812440377/103.85006683126556"
      },
      {
        "type": "anchor",
        "link": "https://www.openstreetmap.org/#map=13/1.2896698812440377/103.85006683126556",
        "text": "Link to Openstreetmap: Singapore"
      },
      {
        "type": "map",
        "latitude": "1.2896698812440377",
        "longitude": "103.85006683126556",
        "zoom": "13"
      }
    ]
```
If response is of this type, then the client should loop through all the actions and display result one after other with delay provided in the response. So, ideally the result of this response should be :
* 1st message : Singapore is a place with a population of 3547809. Here is a map: https://www.openstreetmap.org/#map=13/1.2896698812440377/103.85006683126556
* 2nd message after 0 delay : [Link to Openstreetmap: Singapore](https://www.openstreetmap.org/#map=13/1.2896698812440377/103.85006683126556)
* 3rd message after 0 delay: A map displaying the given coordinates and zoom level 

For response this 
```
"actions": [
      {
        "type": "answer",
        "expression": "Line 1"
      },
      {
        "type": "answer",
        "delay": 400,
        "expression": "Line 2"
      },
      {
        "type": "answer",
        "delay": 1000,
        "expression": "Line 3"
      }
    ]
```
Response should be 
* 1st message Line 1
* 2nd message after 0.4 seconds of 1st message : Line 2
* 3rd message after 1 second of 1st message : Line 3

**Comment by uday96** [comment]
@chiragw15 Cool, I was also wondering about the same. So the delay is only in rendering the response right? 

I will work on this :+1:

**Comment by chiragw15** [comment]
Yes. User should see messages one after another with given delay. Same applies for text to speech. Text1 should be converted to speech. After given delay, text2 and so on.

**Comment by uday96** [comment]
@chiragw15 are there any working queries with which i can test the delay attributes ?

**Comment by chiragw15** [comment]
"multi3"

**Comment by rishiraj824** [comment]
@uday96 is this issue fixed? or needs to be closed?

**Comment by uday96** [comment]
@rishiraj824 Looping through actions and rendering is done. Implementing the delay is pending. Facing some issues with chat box scrolling to bottom after delayed rendering

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi Rendering the responses with delay is still pending implementation. I tried using [react-delay](https://www.npmjs.com/package/react-delay) but when the elements are rendered with delay, the scroll bar was not scrolling to bottom.

Anyone can take this up from here :+1:

**Comment by AakashMallik** [comment]
@rishiraj824  @isuruAb  @madhavrathi May I take it up?

**Comment by mariobehling** [comment]
There is a basic functionality like that implemented now in the server and this is the right place to follow up on more features that are related as well. Thanks for getting this started!
