### ISSUE TITLE
Redundant/Duplicate code present in various CSS files.

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/susi.ai#1645]
**Actual Behaviour**

Classes have been defined multiple times in various CSS files and in many cases.

**Expected Behaviour**
Redundancy/Duplicacy should be resolved.

Observe the CSS files.

**Screenshots of the issue**
1)
![screenshot 2018-10-25 at 4 33 12 pm](https://user-images.githubusercontent.com/31539812/47502393-471af880-d885-11e8-9f8e-15f1e8fb9eed.png)
2) (.chat-input is defined twice)
![screenshot 2018-10-25 at 4 29 14 pm](https://user-images.githubusercontent.com/31539812/47502439-67e34e00-d885-11e8-991a-956caabf6312.png)
3)
![screenshot 2018-10-25 at 4 35 47 pm](https://user-images.githubusercontent.com/31539812/47502301-0f13b580-d885-11e8-8452-7f3643b9214f.png)

**Would you like to work on the issue?**
Yes

**Comment by Rajat1999** [comment]
I would like to work on this..
so what I need to do is merge all classes with same name under a single class ?

**Comment by akshatnitd** [comment]
We already have an issue for it and working on it.
