### ISSUE TITLE
Shifting from CSS to Styled-Components

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/susi.ai#1669]
**Actual Behaviour**

The current stack uses CSS for styling all the React components.

**Expected Behaviour**

Styled components is a much better approach to have more modular and logically complete components. Here is a [link](https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112) giving a brief description of the technology.

**Would you like to work on the issue?**

Yes, it would be a big initiative so I would like people to discuss this before I get started. @Akshat-Jain @akshatnitd

**Comment by akshatnitd** [comment]
Yes, it is a good idea. It requires a lot of effort at this stage and we should do it each UI component at a time.

**Comment by AakashMallik** [comment]
Just what I wanted to hear, yes it will be a lot of effort so I will start with the least coupled components first. I would like to start with *Overview* component. How about I create a totally new branch for this?

**Comment by AakashMallik** [comment]
> I would like to help here(I am a gci participant). just want to know where to start?

@ammarbinfaisal Sure thing, we are planning to first refactor the whole code base, them move on to enhancements. I'll let you know when we get started.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@AakashMallik can i also take part in this work?

**Comment by AakashMallik** [comment]
@RAJAGOPALAN-GANGADHARAN Yeah sure. I'll let you know when we get started with this. Currently, we are not doing this.
