### ISSUE TITLE
Use rem unit instead of pixel

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2088]
**Actual Behaviour**

Pixels are static, does not scale in a spacing properties

**Expected Behaviour**

Shift from `pixel` to `rem`
Supporting article: https://medium.com/@julienetienne/pixels-are-dead-faa87cd8c8b9

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@fragm3 @samagragupta Fixing this for about pages
