### ISSUE TITLE
Display SUSI features in chat

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi.ai#2113]
**Actual Behaviour**
Currently if I click on mic and don't speak anything nothing happens.

**Expected Behaviour**
I was thinking of making it more like Apple siri. In siri if you don't speak anything a modal open up displaying its features. So we can have a chat come up in card view displaying the 6 features of SUSI chat. This would interest the user to try out the SUSI features.

**Screenshots of the issue**
![Screenshot 2019-05-20 at 3 47 33 PM](https://user-images.githubusercontent.com/31013104/58014500-9de46a00-7b16-11e9-9620-1ecef66d18d3.png)

**Would you like to work on the issue?**
Yes

**Comment by harsh-jindal** [comment]
@akshatnitd Should I work on this?

**Comment by akshatnitd** [comment]
I think you should work on priority features before working on enhancements. Although, the idea seems good. Please try to integrate Redux on the Settings component and refactor it.

**Comment by harsh-jindal** [comment]
Okay

**Comment by fragm3** [comment]
@harsh-jindal Good idea 👍

**Comment by akshatnitd** [comment]
@harsh-jindal You can start to work on it, in parallel to the migration/refactoring.

**Comment by mariobehling** [comment]
This feature needs to be implemented in an actual skill.
