### ISSUE TITLE
Fix overlapping CSS classes due to merge of Skill CMS

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2143]
**Actual Behaviour**

Due to the merging of Skill CMS, CSS of some component is changed.

**Expected Behaviour**

Fix it

**Would you like to work on the issue?**

Yes, I and @harsh-jindal will fix all the CSS bugs

**Comment by harsh-jindal** [comment]
@fragm3 I am fixing the high priority bugs. Extra padding on top in skills home page. When not logged in the edit skills shows static app bar twice.
