### ISSUE TITLE
Get userName from settings store in StaticAppBar, TopAppBar

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2160]
**Actual Behaviour**

Currently, userName is taken from the app store, which has a drawback that after logging in, if the userName is changed in settings, it is not reflected in AppBar

**Expected Behaviour**

Fix it by using settings store.

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
@fragm3 Also, make sure in this PR, to completely remove userName from app store. Set userName in settings store after login.

**Comment by fragm3** [comment]
@akshatnitd roger that
