### ISSUE TITLE
Build Analytics page for bot builder

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi.ai#2178]
**Expected Behaviour**

This page should include things like:
- Total users using the bot
- Total messages sent/received.
- Total numbers of hours spent on the bot.

**Mockup**

<img width="859" alt="screen shot 2018-05-30 at 8 48 39 pm" src="https://user-images.githubusercontent.com/31174685/40729826-e931aff6-644a-11e8-9ec0-763459210ce3.png">
Mockup created by: Me and @hkedia321

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Basics are in the system. Other parts need to be thought-through and we will follow up in a new issue.
