### ISSUE TITLE
Integrate review and feedback

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2181]
**Expected Behaviour**

<img width="600" alt="screen shot 2018-06-16 at 11 44 58 pm" src="https://user-images.githubusercontent.com/18073126/41501297-96dcb5fc-71bf-11e8-874e-b0ab7f7aef71.png">

On clicking rate this product,

<img width="600" alt="screen shot 2018-06-17 at 12 00 09 am" src="https://user-images.githubusercontent.com/18073126/41501416-a8102618-71c1-11e8-89fa-04bf9e74337b.png">

This would require API to support review rating + feedback support

Cases:

1. Rating is must, feedback is optional. If a user clicks sends after sending a rating it should send only rating.

2. Title is optional

**Would you like to work on the issue?**

Yes

**Comment by Dilshaad21** [comment]
@akshatnitd I have made a [PR](https://github.com/fossasia/susi_server/pull/1451) in the server side to begin with this. Please view the changes.

**Comment by anishagg17** [comment]
@akshatnitd I want to work on this issue on client-Side

**Comment by Dilshaad21** [comment]
@anishagg17 I have done client part going to make a PR
