### ISSUE TITLE
Analytics for skill creators

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi.ai#2186]
**Actual Behaviour**
All of the analytics so far is done publicly where data for all the skills is just shown.

**Expected Behaviour**
Need some analytics which is specific to skill creators so the skill creators may know how to improve their skills and have a collective data about how their skills are performing.

**Would you like to work on the issue?**
Me, @akshatnitd and @AnupKumarPanwar will be collectively working on it.

**Comment by mariobehling** [comment]
This is currently out of scope as we want to focus on the skills itself. We might come back to this at a later time.
