### ISSUE TITLE
Implement languages supported by a skill

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi.ai#2190]
There should be an option on the skill page to add a translation. By choosing that option the user should be able to select the language followed by the skill name.

Server side PR : https://github.com/fossasia/susi_server/pull/1024

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
This is a useful feature, but currently out of scope and we are not able to maintain it. We continue to focus on the basics for now. Closing it therefore. Thank you
