### ISSUE TITLE
Tour for SkillCreator

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/susi.ai#2193]
**Actual Behaviour**

We currently don't have a tour for newcomers for the SkillCreator component. It is a bit of an advanced tool for people with little knowledge about the platform.

**Expected Behaviour**

We should have a tour for this seemingly advanced tool so that people of any background can use this without going through a lot of documentation.
Here is the component I wish to use, and the demo to it:
[reactour](https://github.com/elrumordelaluz/reactour)
[demo](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js)

**Would you like to work on the issue?**

Yes please, @anshumanv do you think this could be a relevant addition to our current product?

**Comment by mariobehling** [comment]
This is currently out of scope as the project is still changing a lot.
