### ISSUE TITLE
Add missing links to staticAppBar

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2205]
**Actual Behaviour**

Due to migration links in the overview page are missing.

**Expected Behaviour**

Add them

**Steps to reproduce it**

Go to: https://pr-2078-fossasia-susi-web-chat.surge.sh/overview and see the links

**Screenshots of the issue**

<img width="1439" alt="Screenshot 2019-06-06 at 4 01 37 AM" src="https://user-images.githubusercontent.com/18073126/58994935-e33fb180-880f-11e9-96e0-d6521a8dbad6.png">

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@mariobehling @akshatnitd @harsh-jindal where do we need to show these links(Overview, Devices, etc), earlier they were only present in About pages.

**Comment by harsh-jindal** [comment]
@fragm3 I think they shall be present in about pages only.

**Comment by akshatnitd** [comment]
@fragm3 They should be in About pages only.
