### ISSUE TITLE
Fix Settings in Mobile View

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi.ai#2211]
**Actual Behaviour**
UI of mobile view has become buggy after migration.

**Expected Behaviour**
Fix the UI in mobile view.

**Screenshots of the issue**
![Screenshot 2019-06-06 at 9 37 42 AM](https://user-images.githubusercontent.com/31013104/59006404-557bba80-883f-11e9-9ad6-761f43503247.png)

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
This has been fixed.
