### ISSUE TITLE
CSS Bugs

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi.ai#2219]
**Actual Behaviour**
- There are a lot of CSS bugs in the app. Also, many elements are not responsive.
List of components - 

- [x] Auth related components
- [x] Settings page
- [ ] About pages
- [x] Details page
- [x] Skill home(BrowseSkill, etc)
- [ ] Skill creator and Edit pages
- [ ] Admin pages
- [x] Dashboard

Feel free to add more pages, if I missed.

**Expected Behaviour**
All these bugs should be fixed.

**Would you like to work on the issue?**
I, @fragm3 @harsh-jindal

**Comment by akshatnitd** [comment]
Please pick 1 item and solve them one by one.

**Comment by akshatnitd** [comment]
Working on Auth related components now

**Comment by fragm3** [comment]
@akshatnitd I had already created a pr for some auth related components, https://github.com/fossasia/susi.ai/issues/2217

**Comment by fragm3** [comment]
@akshatnitd @harsh-jindal  is working on the skill detail page.

**Comment by akshatnitd** [comment]
@fragm3 Okay, make sure to cover all the Auth components in the PR. 
@harsh-jindal Okay, go ahead and test it thoroughly for tabs and  mobiles.

**Comment by akshatnitd** [comment]
I am working on the Settings page in that case.

**Comment by harsh-jindal** [comment]
@akshatnitd @fragm3 Yes I have already made a PR to fix footer and skill detail page. https://github.com/fossasia/susi.ai/pull/2201

**Comment by fragm3** [comment]
@akshatnitd I was thinking if we could also implement styled-components as well. It would be a  structured way if we fix CSS and add styled-components as well in the same PR.

**Comment by fragm3** [comment]
Proceeding with Dashboard bugs.

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Working on Admin pages

**Comment by fragm3** [comment]
Proceeding with Skill Home Page(BrowseSkill)

**Comment by samagragupta** [comment]
Can I work on Skill creator and Edit pages?

**Comment by fragm3** [comment]
@samagragupta sure, go ahead

**Comment by harsh-jindal** [comment]
@fragm3 I'll fix the settings page, If @akshatnitd has not started

**Comment by akshatnitd** [comment]
@harsh-jindal I am almost done with the PR. Was stuck in other issues, so couldn't open the PR.

**Comment by harsh-jindal** [comment]
@akshatnitd Okay.

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Working on About pages.
