### ISSUE TITLE
Warning while commiting

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2255]
**Actual Behaviour**

When a commit is made a waring is shown.
![Capture](https://user-images.githubusercontent.com/32234926/59243094-e4b41400-8c2b-11e9-80ca-7541498bb907.JPG)

**Expected Behaviour**

Remove that warning.

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Already fixed, update your fork. https://github.com/fossasia/susi.ai/issues/2238
