### ISSUE TITLE
Tab for skills

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi.ai#2256]
**Actual Behaviour**

The skill CMS is difficult to access as there is no tab for it in the website header.

**Expected Behaviour**

"Skill" tab can be added in the header.

**Would you like to work on the issue?**

Any GSoC student can take this up.

**Comment by harsh-jindal** [comment]
@AnupKumarPanwar On it.

**Comment by harsh-jindal** [comment]
@akshatnitd @mariobehling Shall I go ahead on this issue ?
