### ISSUE TITLE
Cookies policy is appearing everytime.

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi.ai#2257]
**Actual Behaviour**

Cookies policy is appearing at the bottom, every time the webpage loads.

**Expected Behaviour**

It should be shown to the user until the user accepts the policy.

**Steps to reproduce it**

1. Visit https://susi.ai/.
2. Accept the policy.
3. Reload the page.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10573038/59261424-12fd1800-8c5b-11e9-9fea-8b4b94b15c17.png)

**Would you like to work on the issue?**

No, anyone can take this.

**Comment by fragm3** [comment]
On it
