### ISSUE TITLE
iframe does not have title

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2265]
**Actual Behaviour**

iframe does not have a unique title. Many iframe errors are there after `npm start`.
![Capture](https://user-images.githubusercontent.com/32234926/59367242-50e06600-8d59-11e9-8ad4-814c9c6737c1.JPG)

**Expected Behaviour**

Providing a unique title to iframe

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please provide a screenshot for visual issues. Which iframe, where?
