### ISSUE TITLE
Fix SkillVersion Code

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2272]
**Actual Behaviour**

Buggy

**Expected Behaviour**

- Fix CSS

- Add FAB fixed to screen for `Compare Selected Version` as the list of commits is too long.

- Add Styled components.

- Sometimes the compare selected version doesn't work, find the bug

**Screenshots of the issue**

<img width="1144" alt="Screenshot 2019-06-12 at 8 43 25 PM" src="https://user-images.githubusercontent.com/18073126/59363407-c137b900-8d52-11e9-80e6-fe447dda21d6.png">

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Several PRs have tackled this. Therefore closing it.
