### ISSUE TITLE
Css fixes in skills description

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2280]
**Actual Behaviour**

Css bugs in skills description.

**Expected Behaviour**

- Fix mobile view in skills description.
- Remove scrolling
- Change SVG of edit icon

**Screenshots of the issue**

![Capture](https://user-images.githubusercontent.com/32234926/59546747-dbd78100-8f50-11e9-8f30-385ba06c09f7.JPG)

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@samagragupta Which browser the scroll bar is visible ?

**Comment by samagragupta** [comment]
@harsh-jindal Chrome

**Comment by harsh-jindal** [comment]
@samagragupta I was unable to reproduce the issue.
@fragm3 Does this exist for you ?
