### ISSUE TITLE
Use common dialog section for all dialog components

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2282]
**Actual Behaviour**

Currently present for some components

**Expected Behaviour**

Integrate with all components

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@akshatnitd should I proceed with this? Mostly admin related dialogs are left.

**Comment by akshatnitd** [comment]
Yes, go ahead

**Comment by fragm3** [comment]
@akshatnitd I am confused, if we need some data from component(for example from the state), how can I decouple the dialog?

**Comment by akshatnitd** [comment]
Check this PR, https://github.com/fossasia/susi.ai/pull/2250. You can now pass component methods to the common dialog component. For eg - Check remove device dialog.
