### ISSUE TITLE
Use thumbnail end point for StaticAppBar, TopAppBar for avatar

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2284]
**Actual Behaviour**

Not present. Uploading avatar results in a pixelated image in the account section, fix that

**Expected Behaviour**

Use thumbnail endpoint for StaticAppBar, TopAppBar for the avatar, once https://github.com/fossasia/susi_server/pull/1276 is merged. 

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
I hope you would not create a new endpoint in `apis/index.js` for it, and instead pass a param for it.

**Comment by fragm3** [comment]
@akshatnitd yes, passed param only
