### ISSUE TITLE
Reduce loading time by replacing gifs with images in Overview component

### ISSUE THREAD

**Issue by KSNINJA** [fossasia/susi.ai#2297]
**Actual Behaviour**
The loading time for first page is too high and performance too low for first interaction.
There are lot of gifs increasing load time.

**Expected Behaviour**
Fix this

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/26023139/59566194-36b8c780-907a-11e9-8a8a-2aee331a7db3.png)

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
As we will redesign the page from scratch we will solve these issues in the process. Therefore closing this.
