### ISSUE TITLE
Add Loader in missing places

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2299]
**Actual Behaviour**

 Loader missing in 

- Settings component
- Admin Component

**Expected Behaviour**

Add it in missing places

**Would you like to work on the issue?**

Yes

**Comment by Dilshaad21** [comment]
@fragm3 Is this issue still open? Can I take this up?

**Comment by fragm3** [comment]
@Dilshaad21 It requires access to Admin panel, so it will be better if I proceed with it. You can pick up issues like converting existing external CSS to styled-components. Thanks!
