### ISSUE TITLE
Unable to give feedback on SUSI Reply

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi.ai#2304]
**Actual Behaviour**
- Unable to give feedback on SUSI Reply

**Expected Behaviour**
- Fix the issue

**Would you like to work on the issue?**
Yes

**Comment by fragm3** [comment]
@akshatnitd I think this was picked up earlier and the conclusion was that it's yet to be implemented on the backend.

**Comment by akshatnitd** [comment]
This functionality was already present, it just logs the feedback of skills in a file on the backend.
