### ISSUE TITLE
Unusual behavior of dropdowns on settings page

### ISSUE THREAD

**Issue by PrP-11** [fossasia/susi.ai#2306]
**Actual Behaviour**
Clicking on dropdowns in settings menu has unusual behavior 

**Expected Behaviour**
The settings container should not move.

**Steps to reproduce it**
Click on language or avatar dropdown

**Screenshots of the issue**
![bug](https://user-images.githubusercontent.com/30981465/59586288-3531e280-9100-11e9-9159-29820399d68c.gif)

**Would you like to work on the issue?**
No

**Comment by fragm3** [comment]
@PrP-11 could tell the browser and its version. Its working fine for me.

**Comment by PrP-11** [comment]
Chrome - Version 75.0.3770.90 (Official Build) (64-bit)

**Comment by fragm3** [comment]
Unable to reproduce, thanks for reporting.
