### ISSUE TITLE
Empty the key when adding a config key

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2314]
**Actual Behaviour**

While adding a config key the text fields are not empty.

**Expected Behaviour**

While adding a config key the text fields should be empty.

**Steps to reproduce it**

![save](https://user-images.githubusercontent.com/32234926/59652324-eb520680-91aa-11e9-890e-ef4ac00073a1.gif)

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@samagragupta This is already done in https://github.com/fossasia/susi.ai/pull/2303
Close this issue
