### ISSUE TITLE
Fix bugs and mobile view in feedback page

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2324]
**Actual Behaviour**

- Mobile view is not proper
- the unnecessary close button is there
- While loading author name is shown

**Expected Behaviour**

- Fix mobile view
- Remove unnecessary close button
- Author name should be shown after loading 

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@samagragupta Screenshot ?

**Comment by samagragupta** [comment]
@harsh-jindal 
![Capture](https://user-images.githubusercontent.com/32234926/59736902-24f14300-9279-11e9-8c6f-05607780eddc.JPG)
![feed](https://user-images.githubusercontent.com/32234926/59736983-7c8fae80-9279-11e9-9948-b6726ab498de.gif)
![feed1](https://user-images.githubusercontent.com/32234926/59737031-b3fe5b00-9279-11e9-86c6-c3886464e4c1.gif)

**Comment by harsh-jindal** [comment]
@samagragupta This is already solved in #2323 .
Please close the issue and PR.
