### ISSUE TITLE
Host Images and GIF on CDN

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2327]
**Actual Behaviour**

Currently, images in the directory which increase the bundle size. And deploying and loading of the website takes more time

**Expected Behaviour**

Host Images and GIF on CDN

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@mariobehling @akshatnitd @harsh-jindal thoughts, please? We can use Amazon CloudFront, CloudFare or Cloudinary.

**Comment by akshatnitd** [comment]
Let's pick this up in the meeting.
