### ISSUE TITLE
Fix position of loader

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2338]
**Actual Behaviour**

The loader is not at the centre

**Expected Behaviour**

Loader should be at the centre of the page.

**Screenshots of the issue**

![Capture](https://user-images.githubusercontent.com/32234926/59898193-57cc4000-940d-11e9-915d-f0116dc73b3f.JPG)
![Capture1](https://user-images.githubusercontent.com/32234926/59898201-5e5ab780-940d-11e9-88e1-682831060d1d.JPG)

**Would you like to work on the issue?**

Yes

**Comment by samagragupta** [comment]
If more such bugs occur then, please mention.

**Comment by Dilshaad21** [comment]
Can I work on the issue?

**Comment by samagragupta** [comment]
@Dilshaad21 Go ahead 🚀

**Comment by Dilshaad21** [comment]
#2360
