### ISSUE TITLE
Fix logo on "Page not Found"

### ISSUE THREAD

**Issue by plxity** [fossasia/susi.ai#2348]
**Actual Behaviour**
![Capture](https://user-images.githubusercontent.com/28510494/59961549-d94bcd00-94f6-11e9-93ce-7ed2cc83e3ce.PNG)

**Expected Behaviour**

![Capture](https://user-images.githubusercontent.com/28510494/59961538-c46f3980-94f6-11e9-8179-ac449aedc5ff.PNG)

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes, I would like to work on this.

**Comment by Dilshaad21** [comment]
@plxity Can I work on this issue?

**Comment by plxity** [comment]
@Dilshaad21 I am working on this.

**Comment by akshatnitd** [comment]
@plxity Please create a PR for it, or let someone else do it.

**Comment by plxity** [comment]
@akshatnitd Apologies for the delay sir, I will create a PR.

**Comment by plxity** [comment]
@akshatnitd  There is some issue with 'yarn install'. Let someone do this till then I'll figure out what is the issue with Yarn install.

**Comment by fragm3** [comment]
Working on it.
