### ISSUE TITLE
Fix SUSI Chat in Mobile view

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2354]
**Actual Behaviour**

Buggy

**Expected Behaviour**

Make it mobile compatible

**Screenshots of the issue**

<img width="209" alt="Screenshot 2019-06-23 at 3 49 49 AM" src="https://user-images.githubusercontent.com/18073126/59969396-f8377700-9569-11e9-8068-cee0b918b917.png">

**Would you like to work on the issue?**

Yes

**Comment by samagragupta** [comment]
@fragm3 Can I work on this?

**Comment by fragm3** [comment]
@samagragupta Can't you see I have already opened a PR? ⬆️
