### ISSUE TITLE
Error while "Yarn install"

### ISSUE THREAD

**Issue by plxity** [fossasia/susi.ai#2366]
![Capture](https://user-images.githubusercontent.com/28510494/60014682-32566500-969f-11e9-9dc6-a421243d7a80.PNG)

I was facing an issue while yarn install. Can someone help with this error?

**Comment by samagragupta** [comment]
@plxity I think there is no proper internet connection.

**Comment by plxity** [comment]
@samagragupta No, that's not the reason I suppose. I have a stable net connection.

**Comment by akshatnitd** [comment]
Try deleting package-lock.json, yarn-lock.json and reinstall.

**Comment by akshatnitd** [comment]
Not reproducible
