### ISSUE TITLE
Fix mobile view in chat app

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2371]
**Actual Behaviour**

Not fixed

**Expected Behaviour**

Proper mobile view in the chat app

**Screenshots of the issue**

![Capture](https://user-images.githubusercontent.com/32234926/60066455-db936e80-9724-11e9-8c22-47d70eee2133.JPG)

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Not reproducible.

**Comment by fragm3** [comment]
Working fine for me. Closing

**Comment by samagragupta** [comment]
@akshatnitd @fragm3 I don't know, why the issue is not reproducing.
But still, there is no space between search and susi icon.
