### ISSUE TITLE
Remove TopAppBar, reuse StaticAppBar

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2373]
**Actual Behaviour**

Remove TopAppBar

**Expected Behaviour**

Reuse StaticAppBar

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please provide a more detailed description and screenshots. What do you want to change and why?

**Comment by fragm3** [comment]
@akshatnitd @mariobehling With recent changes in https://github.com/fossasia/susi.ai/pull/2370, the PR modifies the StaticAppBar code. Currently, we are using TopAppBar, which you see in the chat window and everywhere else, StaticAppBar is used. So once the PR https://github.com/fossasia/susi.ai/pull/2370 finalizes, I would reuse StaticAppBar and just add some code to toggle search bar if it's on the chat window, everywhere it would be off. Changing this would mean we will be using a single app bar across the app instead of 2.
