### ISSUE TITLE
Fix scroll on IconButton Click in AppBar

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2388]
**Actual Behaviour**

Clicking on menu bar icon scrolls to the top of the page, fix that

**Expected Behaviour**

**Steps to reproduce it**

Try clicking on 3 dots on the right side of the menu bar

**Screenshots of the issue**

<img width="207" alt="Screenshot 2019-06-27 at 9 22 55 PM" src="https://user-images.githubusercontent.com/18073126/60281032-c33c7300-9921-11e9-9d9a-001da2bd5fec.png">

**Would you like to work on the issue?**

Yes

**Comment by Dilshaad21** [comment]
@fragm3 Can I work on this bug if you are not currently working?

**Comment by fragm3** [comment]
@Dilshaad21 I have invested time in this, couldn't fix it, will try in some other approaches. You could also try to fix it.

**Comment by Dilshaad21** [comment]
Ok @fragm3 I'll let you know if it works for me. :+1:

**Comment by fragm3** [comment]
@Dilshaad21 I have fixed this, thanks!
