### ISSUE TITLE
Clicking on Username does not open up the settings in susi.ai/chat

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi.ai#2390]
**Actual Behaviour**
Currenlty if you got to susi.ai/chat and click on username, the settings does not open up.

**Expected Behaviour**
The settings should open up clikcing on the username.

**Steps to reproduce it**
Go to susi.ai/chat and click on username.

**Screenshots of the issue**
![Screenshot 2019-06-28 at 8 56 45 AM](https://user-images.githubusercontent.com/31013104/60315072-aedc9280-9982-11e9-84fd-7fa96ea7c9ee.png)

**Would you like to work on the issue?**
Yes

**Comment by Dilshaad21** [comment]
@harsh-jindal I would like to work on this issue?

**Comment by harsh-jindal** [comment]
@Dilshaad21 Sure go ahead

**Comment by Dilshaad21** [comment]
@harsh-jindal I have solved the bug PTAL
