### ISSUE TITLE
Videos not visible in Firefox

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2394]
**Actual Behaviour**

Videos not visible in Firefox browser

**Expected Behaviour**

Make videos visible

**Screenshots of the issue**

<img width="1031" alt="Screenshot 2019-06-28 at 8 53 14 PM" src="https://user-images.githubusercontent.com/18073126/60353054-d107fc00-99e6-11e9-88ad-142ac66cebfd.png">

**Would you like to work on the issue?**

Yes

**Comment by aman29271** [comment]
@fragm3 can I work on this issue?

**Comment by mariobehling** [comment]
This is working already. Thanks. Closing it therefore.
