### ISSUE TITLE
Fix Date in Message List

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2408]
**Actual Behaviour**

Date not present

**Expected Behaviour**

Earlier, a few months back, the messages were grouped in dates. Add date

**Screenshot**

<img width="716" alt="Screenshot 2019-06-30 at 2 26 04 AM" src="https://user-images.githubusercontent.com/18073126/60389434-75209e80-9ade-11e9-879a-464aec17b319.png">

Surge link: https://pr-1670-fossasia-susi-web-chat.surge.sh/

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@akshatnitd do we require this feature?

**Comment by akshatnitd** [comment]
@fragm3 We can have this, but I don't think it is a priority. If we are implementing it, make sure the date sticks until messages from that date are not over while scrolling.

**Comment by anishagg17** [comment]
@akshatnitd this issue has been resolved please close the issue
