### ISSUE TITLE
Fix Rating popover bug in Browse Skill

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi.ai#2416]
**Actual Behaviour**
Currently if you hover and place the cursor inside the rating popover and scroll the rating popovers scrolls down.

**Expected Behaviour**
Fix it.

**Steps to reproduce it**
Go to browse skill.
Click on any category.
Hover on the rating and place the cursor inside the rating popover and scroll.

**Screenshots of the issue**
![Screenshot 2019-07-02 at 11 45 38 PM](https://user-images.githubusercontent.com/31013104/60536563-219f9200-9d24-11e9-9b81-aff71a8c6553.png)

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
Cannot reproduce
