### ISSUE TITLE
Open up share dialog on clicking on share in Chat

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi.ai#2417]
**Actual Behaviour**
Currently if you click on share it directly takes you to twitter to share.

**Expected Behaviour**
A share dialog shall open up so that the user can choose to share on fb, twitter and linkedin.

**Steps to reproduce it**
go to chat.
click on share icon in the chat bubble.

**Would you like to work on the issue?**
Yes

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Shall I add this?

**Comment by fragm3** [comment]
Yes, would be nice
