### ISSUE TITLE
Simplify and enhance menus

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2423]
* Avoid the arrow ">" turning around. Take out the turning effect.
* Dropdown menu. Move the following items here:
   * Admin (and don't show submenu items in the dropdown menu)
   * About (and don't show submenu items in the dropdown menu)
* To the right of the dropdown menu show a question mark (like Facebook) link it to "Support" 
![Screenshot from 2019-07-02 23-51-40](https://user-images.githubusercontent.com/1583873/60549318-d043d280-9d24-11e9-994c-2c3f5f04239e.png)
* Make Menu clickable
   * Skills -> /skills
* Make skills submenu as follows
   * Dashboard
   * Browse Skills
   * Create Skill
   * Create Skill Bot
* Bottom Menu - Add items. The menu should have the following items:
  * About (Rename Overview to About)
  * Devices
  * Blog
  * API 
  * Code
  * Team
  * Support
![Screenshot from 2019-07-02 23-56-04](https://user-images.githubusercontent.com/1583873/60569893-a912f280-9d70-11e9-8d4e-cc95b64d87db.png)

**Comment by fragm3** [comment]
On it
