### ISSUE TITLE
Make Skills page to be the start page and add chat icon to the bottom right of all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2424]
We are now at the stage that SUSI.AI is more and more usable. Therefore we don't need to explain so much on the start page anymore. People should be able to visit the page click a sample text and see the result immediately. Therefore change the site as follows:
* Make /skills to be the start page
* Add a chat icon on the bottom right on all pages. On clicking it the icon expands to be a chat area of SUSI.AI on the bottom right.
![Screenshot from 2019-07-03 00-03-38](https://user-images.githubusercontent.com/1583873/60550065-0b470580-9d27-11e9-9a29-557b1341e045.png)
* Also provide a full screen option like Google Hangout. 
![Screenshot from 2019-07-03 00-09-27](https://user-images.githubusercontent.com/1583873/60549994-d76be000-9d26-11e9-9523-a6d14da84055.png)
* The full screen chat version should look the same as the current full page chat. It should also provide an option to move in the popup just like Google Hangout
![Screenshot from 2019-07-03 00-08-39](https://user-images.githubusercontent.com/1583873/60550027-f23e5480-9d26-11e9-838c-bde3db7b205f.png)

**Comment by harsh-jindal** [comment]
@mariobehling I'll take this up.
