### ISSUE TITLE
Substitute dropdown menu by "Login" and "Name with dropdown arrow" when logged in

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2425]
Please make the following changes:
* When user is not logged in show "Login" on the top right instead of the burger menu
* When the user is logged in show the name of the user and an arrow. Follow the same concept as Eventyay, please

![Screenshot from 2019-07-03 00-13-18](https://user-images.githubusercontent.com/1583873/60550429-3bdb6f00-9d28-11e9-833e-4d563e93ce18.png)

**Comment by samagragupta** [comment]
I will take this

**Comment by samagragupta** [comment]
@mariobehling Where should the `about` button go?

**Comment by mariobehling** [comment]
Just keep it there for now.

**Comment by mariobehling** [comment]
Or actually, can you make a dropdown on the (?) symbol on the menu and show "Support" and "About" here.
