### ISSUE TITLE
Implement Slider on Skills page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2427]
On Amazon there is a slider above the skills. Please implement the same on the Skills page. Create a slides for:
* Devices, add an image of a Raspi here -> link to https://susi.ai/devices (move "device page" here)
* Android app with a link to Playstore and Fdroid
* Developers: Setup SUSI.AI on Your Machine -> link to https://github.com/fossasia?utf8=✓&q=susi

Compare:
https://www.amazon.de/b?ie=UTF8&language=en_GB&node=10068460031

![Screenshot from 2019-07-03 12-42-36](https://user-images.githubusercontent.com/1583873/60585916-22224200-9d91-11e9-824f-6a7968efcccb.png)

**Comment by fragm3** [comment]
@mariobehling I'd like to take this up
