### ISSUE TITLE
The preview window doesn't give response based on the live skill.

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi.ai#2432]
**Actual Behaviour**
The preview window doesn't give response based on the live skill.

**Expected Behaviour**
There is an `instant` parameter in the `/chat.json` API. Please use it in the preview window of the skill and bot creator, so get the preview of live skill. Example of usage - https://github.com/fossasia/susi.ai/blob/3dbf8637aa3bf6c2ef73e45b7df8afd5063c9792/src/components/cms/SkillCreator/SkillViews/ConversationView.js

**Would you like to work on the issue?**
@harsh-jindal @fragm3

**Comment by fragm3** [comment]
@akshatnitd I'll pick this up
