### ISSUE TITLE
Direct Create Skill directly to Create Skill Wizard, Move My Skills page into Secondary Menu on Dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2439]
* Create Skills buttons direct to skills/skillCreator. Instead they should direct to /skills/skillWizard.
* The page at "skills/skillCreator" should be renamed to "/myskills" and
   * integrate it into the secondary menu on the dashboard (need to be created similar to Admin)
   * left-align the to be created secondary menu at /skills/dashboard, menu should have three items for now
       * Dashboard 
       * My Skills
       * Botbuilder

![Screenshot from 2019-07-04 11-09-14](https://user-images.githubusercontent.com/1583873/60655138-8a365e00-9e4d-11e9-8a8e-34927d110712.png)

**Comment by akshatnitd** [comment]
Working on it

**Comment by akshatnitd** [comment]
There are few questions - 
1) Do we rename the route to `/mskills`?
2) Can you please specify, which secondary menu in Admin page?

**Comment by mariobehling** [comment]
> @mariobehling There are few questions -
> 
> 1. Do we rename the route to `/myskills`?

Yes, please.

> 2. Can you please specify, which secondary menu in Admin page?

![Screenshot from 2019-07-04 17-57-40](https://user-images.githubusercontent.com/1583873/60678584-419a9700-9e85-11e9-9579-d4096d5e9a1a.png)

Please left align it.
