### ISSUE TITLE
Integrate Styled components in Preview Chat in BotBuilder

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2442]
**Actual Behaviour**

CSS being used

**Expected Behaviour**

Integrate Styled components in Preview Chat in BotBuilder

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@fragm3 If you have not started this, could you wait for #2465 to be completed and then work on this issue

**Comment by fragm3** [comment]
@harsh-jindal didn't saw your message. Anyways, we have decided to go with the chat window approach.
