### ISSUE TITLE
Mobile view in mobile settings

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2447]
**Actual Behaviour**

Mobile view in mobile settings is not proper

**Expected Behaviour**

Fix Mobile view in mobile settings

**Screenshots of the issue**

![Capture](https://user-images.githubusercontent.com/32234926/60685108-fb622980-9ebe-11e9-9ddc-fa22741749a7.JPG)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
There should not be a space in front of  ":"

Please follow international English, when you fix this. Thanks.
