### ISSUE TITLE
Extra Space in teams page

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2448]
**Actual Behaviour**

There is extra space in teams page on the right side of the screen.

**Expected Behaviour**

Make the cards at the centre

**Screenshots of the issue**

![Capture](https://user-images.githubusercontent.com/32234926/60686250-4848fe80-9ec5-11e9-9689-1847f991486d.JPG)

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@samagragupta Does this issue still exists ?

**Comment by samagragupta** [comment]
@harsh-jindal Yes, I will take this up in next PR.
