### ISSUE TITLE
Footer is not at the bottom of the page

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2449]
**Actual Behaviour**

Still, footer is not at the bottom of the page.

**Expected Behaviour**

The footer should be at the bottom of the page.

**Screenshots of the issue**

![Capture](https://user-images.githubusercontent.com/32234926/60696416-4b62df80-9f03-11e9-8ce6-f765f9e74722.JPG)

**Would you like to work on the issue?**

Yes

**Comment by harsh-jindal** [comment]
@samagragupta Make sure when you make changes for the footer, you check it is working fine everywhere in the web app.
