### ISSUE TITLE
Admin: Settings - Implement Mail Settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2454]
The SUSI.AI server has email settings build in currently. Please get these settings and implement a way to change them. Add the feature into the tab "Settings". (Please also rename "System Settings" to "Settings only.).

See screenshot below for details.
![Screenshot from 2019-07-05 15-46-13](https://user-images.githubusercontent.com/1583873/60726740-8cc3b100-9f3c-11e9-9639-ccb2329b48ca.png)

**Comment by fragm3** [comment]
@mariobehling I'll take this up, thank you
