### ISSUE TITLE
Admin Settings: Implement Subtab for Image Config and Add Details for Slider Images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2455]
The slider images are currently hardcoded into the frontend. This will change later. First step is to add information on the images into the admin settings.
* Please create a subtab similar to the open event frontend.

![Screenshot from 2019-07-05 15-52-30](https://user-images.githubusercontent.com/1583873/60726903-f217a200-9f3c-11e9-9541-27cd182bd9b1.png)

In the subtab add a list for 4 slider images with
   * info on dimension
   * storage location (which folder)
   * name of image
   * thumbnail of image

**Comment by fragm3** [comment]
@mariobehling working on it.

**Comment by fragm3** [comment]
@mariobehling The dimension's must be fixed for our slider to work properly in terms of positioning and image aspect ratio
