### ISSUE TITLE
Delete Heading in Admin area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2456]
Please delete the headings in the admin area. The secondary menu already indicates the page the user is accessing through the underlining of the current menu item.

Also: Left-align the submenu.

E.g. delete "Admin" here and the heading in all other tabs.
![Screenshot from 2019-07-05 16-56-38](https://user-images.githubusercontent.com/1583873/60730697-04e2a480-9f46-11e9-9416-09805d0ead90.png)

**Comment by harsh-jindal** [comment]
Working on it
