### ISSUE TITLE
Enhance search functionality

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2473]
Please change the text in the search bar to "Search for Skills" instead of "Search".

![Screenshot from 2019-07-06 19-15-30](https://user-images.githubusercontent.com/1583873/60759305-4006d580-a023-11e9-9820-b0416208fa6e.png)

Add filters as a drop down menu on the side within the search box with ticks:
* Search in
  * [ ] Names
  * [ ] Description
  * [ ] Examples
  * [ ] Code
  * [ ] Developers

Any other filter options that come to your mind?

Follow material UI but take inspiration from Amazon dropdown menu.

![Screenshot from 2019-07-06 19-20-11](https://user-images.githubusercontent.com/1583873/60759303-3bdab800-a023-11e9-9614-804ed742c819.png)

**Comment by fragm3** [comment]
I'll take this up

**Comment by fragm3** [comment]
@mariobehling Search By Code seems unnecessary, let's skip that search type

**Comment by mariobehling** [comment]
Please finalize this and implement the options as tick box. By default all should be ticked.
