### ISSUE TITLE
Admin: Action Buttons disappear on small screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2476]
On smaller laptop screens the action buttons disappear in the admin table. Expected: A line break should happen if the space is not enough.

Compare: https://susi.ai/admin/skills

![Screenshot from 2019-07-06 23-22-49](https://user-images.githubusercontent.com/1583873/60761276-532a9d00-a045-11e9-9157-cabc334372f8.png)

**Comment by fragm3** [comment]
On it
