### ISSUE TITLE
Device Page: Add configuration options / settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2488]
Please add the following options in the device page to configure local devices:
* [ ] tick box: Synchronize local skills with SUSI.AI skills database regularly. (default on)
   * [ ] button: Synchronize Now
* [ ] tick box: Synchronize (upload) private skills I create locally with my online account when online.
   * [ ] button: Upload Now
* [ ] button: "Link SUSI.AI account with device" when unlinked and show "Device linked to SUSI.AI account [user name here]" when linked plus a button "Unlink" - when people click this, then show a message "This will unlink your SUSI.AI local device from the SUSI.AI online account. You might loose data and configurations. Do you really want to proceed? Please type your username here."
* [ ] Section "Speech Recognition and Voice Output on Device"
    * [ ] For Speech Recognition (Speech to Text) use the service -> Add dropdown menu for Google, IBM Watson, etc.
   * [ ] For Voice Output (Text to Speech) use the service -> Add dropdown menu for Google, IBM Watson, etc.

**Comment by harsh-jindal** [comment]
On it
