### ISSUE TITLE
Take out the slug /skills from dashboard etc.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2489]
The skills slug is no longer needed to distinguish parts of the system. Please take it out from all links, e.g. the dashboard. Just link it directly to https://susi.ai/dashboard instead of https://susi.ai/skills/dashboard and do the same with the other links that include the /skills slug.

![Screenshot from 2019-07-07 21-01-25](https://user-images.githubusercontent.com/1583873/60772738-dbb74500-a0fa-11e9-9a3d-8b86d139de96.png)

**Comment by fragm3** [comment]
Working on it
