### ISSUE TITLE
Forgot password and sign up not working

### ISSUE THREAD

**Issue by alok760** [fossasia/susi.ai#2498]
**Actual Behaviour**

- If I try to reset my password, the forgot password method displays `Failed, Try Again`
![image](https://user-images.githubusercontent.com/14289201/60850389-bd416e80-a20c-11e9-9037-b2d0b74319f7.png)

- If i try to sign up, it says `Please verify that you are human` but there is no captcha.
![image](https://user-images.githubusercontent.com/14289201/60850487-422c8800-a20d-11e9-89c1-29872c2c83f8.png)

**Comment by akshatnitd** [comment]
@alok760 Can reproduce it now. Please confirm, if still happens to you, otherwise close it.

**Comment by alok760** [comment]
@akshatnitd This appears to be fixed now, Thanks
