### ISSUE TITLE
Icons overlapping 

### ISSUE THREAD

**Issue by plxity** [fossasia/susi.ai#2501]
**Actual Behaviour**

![Capture](https://user-images.githubusercontent.com/28510494/60909273-7484c680-a29b-11e9-8f6b-eb98449da141.PNG)

**Expected Behaviour**

Icons should not overlap in the accounts tab near the upload image section.

**Steps to reproduce it**

1) Login to your account
2) Check the accounts tab

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes, I would like to work on this!

**Comment by samagragupta** [comment]
For that `choose file` option should be removed. https://github.com/fossasia/susi.ai/issues/2481

**Comment by plxity** [comment]
@samagragupta So are you working on it?

**Comment by samagragupta** [comment]
https://github.com/fossasia/susi.ai/pull/2503#pullrequestreview-259865559

**Comment by samagragupta** [comment]
https://github.com/fossasia/susi.ai/pull/2503
