### ISSUE TITLE
Add Dashboard icon

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2505]
Add a Dashboard (linking to /dashboard) icon between the name dropdown and the right support icon.

Also delete the "skills" dropdown menu item from the top menu.

 ![Screenshot from 2019-07-10 13-34-13](https://user-images.githubusercontent.com/1583873/60966123-d3882100-a317-11e9-90eb-90cfec9e1368.png)

**Comment by samagragupta** [comment]
@mariobehling Here you said it to add dashboard above settings.
https://github.com/fossasia/susi.ai/pull/2482#issuecomment-509942540

**Comment by mariobehling** [comment]
Yes, good. The dashboard is an important item. So, we also need an icon for that here. And please delete the skills dropdown menu item.

**Comment by samagragupta** [comment]
@mariobehling Then where will `Create skill` and `Create Bot` should go?
![Capture](https://user-images.githubusercontent.com/32234926/60967220-c1b67600-a337-11e9-830b-16645c753d29.JPG)

**Comment by mariobehling** [comment]
Please focus on this issue here. We have other parts on the front page.

**Comment by samagragupta** [comment]
I will do that.
