### ISSUE TITLE
Rename /Botbuilder to /mybots and alter UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2506]
Please change the URL slug /botbuilder to /mybots

In the menu rename "botbuilder" to "My Bots"

In the UI move "My bots" to the top and "Pick a Template" below.

![Screenshot from 2019-07-10 13-52-00](https://user-images.githubusercontent.com/1583873/60967093-1e0a9d00-a31a-11e9-98a8-b63419345c64.png)

**Comment by samagragupta** [comment]
I will do this.
