### ISSUE TITLE
Move search bar to top of page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2509]
Skills and chat are the centre of the SUSI.AI service. Therefore we want to make skills accessible on every page by providing a search on the top. This also follows design implementations of Facebook and Amazon.

Please move the search bar to the top menu bar and in the bar show "Search Skills".

![Screenshot from 2019-07-11 10-10-24](https://user-images.githubusercontent.com/1583873/61033637-2d462500-a3c4-11e9-8845-977fca753407.png)

![Screenshot from 2019-07-11 10-09-47](https://user-images.githubusercontent.com/1583873/61033643-30411580-a3c4-11e9-96d8-38da73785fea.png)

**Comment by fragm3** [comment]
Will work in this
