### ISSUE TITLE
Change and add more slides to front page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2510]
Change:
1. Set up SUSI.AI on your local machine -> Set up your own smart speaker with SUSI.AI
Button with GitHub icon: [Download Installer]
URL: https://github.com/fossasia/susi_installer/releases
2. Available on Linux -> Runs on many devices
Icons: Web, Android, iOS, Linux

Add slides:
1. Login and create your own skills or bots on the fly.
URL: Open My Skills page
Button: No button
2. No secret recording of your voice!
✔ Respects your privacy
✔ Open Source code
✔ No Backdoors 
Button: Learn More
URL: -> /about
3. "Hey SUSI, play Shakira on YouTube"
URL: Opens Chatbox with Shakira YouTube Video
Button: Try it here

**Comment by fragm3** [comment]
On it

**Comment by fragm3** [comment]
![000-min-1](https://user-images.githubusercontent.com/18073126/61071948-ef7ee600-a42f-11e9-8899-1c14461a9a79.png)

![000-min](https://user-images.githubusercontent.com/18073126/61071949-ef7ee600-a42f-11e9-8776-61d161ce0c91.png)

![001-min-1](https://user-images.githubusercontent.com/18073126/61071950-f0177c80-a42f-11e9-9d7a-6f856d956de7.png)

![001-min](https://user-images.githubusercontent.com/18073126/61071952-f0177c80-a42f-11e9-9ea5-c24f27ed3a32.png)

![002-min-1](https://user-images.githubusercontent.com/18073126/61071953-f0177c80-a42f-11e9-9ab9-a1c652d89b94.png)

![002-min](https://user-images.githubusercontent.com/18073126/61071954-f0b01300-a42f-11e9-90ec-20536b853330.png)

**Comment by mariobehling** [comment]
Looks good. Some small changes:

![000-min-1](https://user-images.githubusercontent.com/18073126/61071948-ef7ee600-a42f-11e9-8899-1c14461a9a79.png)
Please increase text size a bit and center vertically.


![001-min-1](https://user-images.githubusercontent.com/18073126/61071950-f0177c80-a42f-11e9-9d7a-6f856d956de7.png)
Change to: 
"Play Shakira on YouTube" 
(Otherwise it does not actually work)
Also include the quotations marks and change this slide to have the text in a bubble like we have it on the skills detail page. Alexa also does it similarly.

![Screenshot from 2019-07-11 22-19-10](https://user-images.githubusercontent.com/1583873/61082650-336eec80-a42a-11e9-9f03-87d4d4759f62.png)
https://www.amazon.com/alexa-skills/b?ie=UTF8&node=13727921011

**Comment by fragm3** [comment]
![000-min](https://user-images.githubusercontent.com/18073126/61088128-30d5bc80-a455-11e9-93ca-966c6c85d74b.png)

![001-min](https://user-images.githubusercontent.com/18073126/61087973-c290fa00-a454-11e9-8a4e-283dfa087cc2.png)

**Comment by fragm3** [comment]
@mariobehling I have uploaded these images on admin panel.
