### ISSUE TITLE
Add speech box for skill example sentences on front, cat and all pages with skills

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2511]
Add a speech box for skill example sentences to the front page skills, category pages and all pages that show skills same as the skill detail page and link this speech box to provide answers in the chat box.

![Screenshot from 2019-07-11 12-20-52](https://user-images.githubusercontent.com/1583873/61043474-a51d4b00-a3d6-11e9-8337-0acba60e2735.png)

![Screenshot from 2019-07-11 12-20-15](https://user-images.githubusercontent.com/1583873/61043483-a9e1ff00-a3d6-11e9-8df8-3733698f0d3f.png)

**Comment by harsh-jindal** [comment]
I'll take this up
