### ISSUE TITLE
Icon and name not portrayed as expected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2513]
There are several issues with the icon and name of the user on the top menu bar:
* Personal icon is not shown even though it is in the user account
* Icon is slightly cut off on top 
* Icon and name are not in the middle vertically in the menu bar

![Screenshot from 2019-07-11 12-46-07](https://user-images.githubusercontent.com/1583873/61044955-15799b80-a3da-11e9-9dcc-483bc403d909.png)

**Comment by fragm3** [comment]
On it

**Comment by mariobehling** [comment]
Issue is not solved. Additionally now the white dropdown slightly overlaps with the above menu bar after one of the previous PRs. 

![Screenshot from 2019-07-12 20-59-35](https://user-images.githubusercontent.com/1583873/61152213-14369480-a4e8-11e9-942e-bc48e63e41d2.png)

**Comment by fragm3** [comment]
@mariobehling will pick this up together with other PR changes
