### ISSUE TITLE
Add list of System Skills above "Staff Picks" on start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2514]
Listing system skills on the front page would be useful to show people the capabilities of SUSI.AI.

Please implement a row with system skills on the front page above the "Staff Picks".

![Screenshot from 2019-07-11 14-05-44](https://user-images.githubusercontent.com/1583873/61049746-8bcfcb00-a3e5-11e9-8725-ded247ff7e52.png)

**Comment by harsh-jindal** [comment]
I'll take this up
