### ISSUE TITLE
Show the control webpage on the devices section of the webclient(smart speaker)

### ISSUE THREAD

**Issue by alok760** [fossasia/susi.ai#2520]
On the smart speaker, the web client(local-pages branch) runs on `localhost:7070` and the control webpage runs on the same server but on the `/control` endpoint i.e. `localhost:7070/control`

- Display the control webpage under the devices section of the WebClient, when the client is running on the smart speaker(local-pages branch)

- The control webpage
![image](https://user-images.githubusercontent.com/14289201/61091719-d6daf400-a460-11e9-9421-f8cbaefdda77.png)

- Add control webpage here : 
![image](https://user-images.githubusercontent.com/14289201/61091080-6e8b1300-a45e-11e9-9772-c0d1c059792e.png)

**Comment by akshatnitd** [comment]
@alok760 Where can I fid the code to the UI in the sceenshot? We can build that UI in this repo itself.

**Comment by alok760** [comment]
@akshatnitd it can be found here - https://github.com/fossasia/susi_installer/blob/development/raspi/soundserver/soundserver.py
Thank You

**Comment by alok760** [comment]
To implement this natively 
buttons and sliders in the control webpage should be implemented directly in the web client. 
* control webpage -https://github.com/fossasia/susi_installer/blob/development/raspi/soundserver/templates/control.html


The endpoints for each button is present on the same server in which the webclient(susi.ai) is running.
The endpoints are listed in this flask server - 
* Endpoints : flask server -https://github.com/fossasia/susi_installer/blob/development/raspi/soundserver/soundserver.py

**Comment by akshatnitd** [comment]
I will work on it.

**Comment by akshatnitd** [comment]
Working on it.
