### ISSUE TITLE
Add All Option in Search Functionality

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2522]
**Actual Behaviour**

Not present

**Expected Behaviour**

Add an option to search all parameters like example, skill, description

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@mariobehling @akshatnitd @harsh-jindal need your suggestions for it. Amazon uses `all` for categories, I don't know whether it would be useful in our case and it would not be clear to the user, what All means as there is no a specific category in the search

**Comment by mariobehling** [comment]
Amazon is just a reference. We can do better if we have ideas to do better. As stated in the earlier issues, please implement the same feature but with a tick box. I restated this in a comment here: https://github.com/fossasia/susi.ai/issues/2473

Closing this issue. Please finalize https://github.com/fossasia/susi.ai/issues/2473 by implementing the tick boxes.
