### ISSUE TITLE
Admin: Fix and Improve Skills Overview Table

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2525]
1. The second table row has the filters for the tables. Please move them to be part of the heading and implement missing filters.
2. Make all rows sortable

Compare: https://susi.ai/admin/skills
![Screenshot from 2019-07-12 10-05-10](https://user-images.githubusercontent.com/1583873/61112706-c3de1900-a48c-11e9-83f6-37d379427d72.png)

**Comment by fragm3** [comment]
@mariobehling It is fixed for the library `material-table` we are using, filters can't be shifted up
