### ISSUE TITLE
Add "Create" and chat icon to top menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2528]
Please add a "Create" item and a chat icon to the top menu bar to the right hand side of the user name/email.

On clicking the Chat Icon
* open the chat window
* if the chat box is already open, close it when the user clicks the chat icon

Scrolling over "Create" should result in a submenu opening showing:
* Create Skill -> https://susi.ai/skillWizard
* Create Bot -> https://susi.ai/botbuilder/botwizard (or the updated link)

Also compare to Facebook
![Screenshot from 2019-07-11 10-09-47](https://user-images.githubusercontent.com/1583873/61152482-d5eda500-a4e8-11e9-88a0-6185dca3ea93.png)

**Comment by samagragupta** [comment]
On it.
