### ISSUE TITLE
Clicking on "Create" on the left side it results in disappearing the scroll bar of the site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2530]
When the user clicks on the blue create button, the scroll page on the right side of the screen disappears.

![Screenshot from 2019-07-12 23-20-14](https://user-images.githubusercontent.com/1583873/61159271-c3309b80-a4fb-11e9-934e-e0f3bccfebf6.png)

**Comment by fragm3** [comment]
@mariobehling unable to reproduce this issue
