### ISSUE TITLE
Change the style of the language dropdown and make it smaller

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2531]
Please take inspiration of the UI of Amazon for the language dropdown menu. Even if our functionality is different the UI can be implemented in a similar way.

![Screenshot from 2019-07-12 23-15-46](https://user-images.githubusercontent.com/1583873/61159333-f70bc100-a4fb-11e9-90f0-c154e904a449.png)

**Comment by fragm3** [comment]
I'll take this up after https://github.com/fossasia/susi.ai/pull/2527 merges

**Comment by mariobehling** [comment]
The current way of selecting multiple languages is also good. Just change the UI to make it smaller somehow. Thanks.

**Comment by fragm3** [comment]
@mariobehling I could show EN, etc smaller version in after language is selected, just like amazon
