### ISSUE TITLE
Redirect to Browse skills search on search enter

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2532]
**Actual Behaviour**

With PR https://github.com/fossasia/susi.ai/pull/2527, we can enhance it further

**Expected Behaviour**

We can enhance it further for other pages, by redirecting to skills page results on the keyboard enter key

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@mariobehling @akshatnitd @harsh-jindal need your input

**Comment by akshatnitd** [comment]
Yes, go ahead with it.
