### ISSUE TITLE
Dashboard: Different size of gray area padding

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2534]
Decrease the size of the gray padding area below the secondary dashboard menu. Please make padding area in "My Skills" the same size as other pages.

![Screenshot from 2019-07-13 11-32-18](https://user-images.githubusercontent.com/1583873/61169874-851a9280-a562-11e9-964b-d1cff69fdac5.png)

![Screenshot from 2019-07-13 11-32-38](https://user-images.githubusercontent.com/1583873/61169871-7e8c1b00-a562-11e9-9018-e6cf878ad656.png)

**Comment by samagragupta** [comment]
on it.

**Comment by mariobehling** [comment]
@samagragupta Please solve previous issues you claimed first, before claiming new issues.
