### ISSUE TITLE
Enhance Admin Skills Section

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2539]
**Actual Behaviour**

Only active, deleted, reported skills present

**Expected Behaviour**

Add a table for:

1. Reviewed Skills
2. System Skills 

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@mariobehling how about extending your issue https://github.com/fossasia/susi.ai/issues/2477 and adding a reviewed skills section as well?

**Comment by mariobehling** [comment]
@fragm3 I have not tested in detail if there are issues with reviewed skills. As far as I can see it works.
