### ISSUE TITLE
Admin: Slider Page buggy

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2544]
![Screenshot from 2019-07-14 15-22-56](https://user-images.githubusercontent.com/1583873/61184276-2d585600-a64c-11e9-8bc1-1ec38a031f50.png)

Please fix the following issues:
* table view results in cursor on smaller screens. Expected: if area is too small make a line break
* Add slider is "Config button". Expected "Add Slider"
* Table is limited to 5 entries. Expected: Simply show all entries and get rid of choice of 5, 10, or more rows. We don't need choice. Please show all.

![Screenshot from 2019-07-14 15-30-01](https://user-images.githubusercontent.com/1583873/61184294-57117d00-a64c-11e9-9e08-9c07a82143ef.png)

On "Edit" popup:
* Edit Slideshow -> Edit Slider
* Rename "Redirect Url" to "Link to"
* Try to reduce height of content to avoid scroll bars, e.g. space around preview image and space above buttons
* Edit Button - do you mean "Save" instead of "Edit"? On the left show "Cancel" and on the right show "Save" on the bottom.

**Comment by akshatnitd** [comment]
Already fixed
