### ISSUE TITLE
Admin Dashboard: Show User and Skill Statistics

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2550]
The information on user activities is limited on the admin dashboard.

Please implement a chat for user information with the following:
* Logins over time
* User registration over time
* Skill edits over time
* Skill creations over time
* Any other interesting information

![Screenshot from 2019-07-14 18-11-28](https://user-images.githubusercontent.com/1583873/61186225-1a9d4b80-a663-11e9-87e8-4983174146a7.png)

**Comment by fragm3** [comment]
We can add skill used over time
