### ISSUE TITLE
Admin: Add Bots Tab 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2551]
The admin area has an overview of skills. However bots are missing. Please implement a tab "Bots".

Compare: https://susi.ai/admin/skills
![Screenshot from 2019-07-14 19-03-37](https://user-images.githubusercontent.com/1583873/61186837-466fff80-a66a-11e9-99d7-3318b08e6bb8.png)

**Comment by harsh-jindal** [comment]
Will take this up
