### ISSUE TITLE
Only allow usernames with up to 51 characters

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2555]
Someone put in a username with hundreds of characters. This could potentially be used by hackers. Please allow only usernames up to 51 characters (also open a related issue on the server).

This policy is similar to Facebook.

https://stackoverflow.com/questions/8078939/what-is-the-maximum-length-of-a-facebook-name

**Comment by fragm3** [comment]
@mariobehling this will be handled in https://github.com/fossasia/susi_server/issues/1306. Do tell more points that come up regarding this
