### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi.ai#2572]
**Actual Behaviour**
Clicking on 
Farming
FOSSASIA
"When it will rain"

leads to 
Personal Finance
https://susi.ai/Business%20and%20Finance/Personal%20Finance/en

**Expected Behaviour**

Right link.

**Steps to reproduce it**
https://susi.ai/category/All
Filter Last 90 days.

**Comment by mariobehling** [comment]
Do you have a screenshot?

**Comment by tabesin** [comment]
![Farmingbild](https://user-images.githubusercontent.com/10114907/61248677-de95e380-a753-11e9-8e61-9df8b8d862aa.png)


Reproduce Select ALL Last 90 days. Second entry is farming. Leads to Personal Finance skill link above.

**Comment by akshatnitd** [comment]
Fixed
