### ISSUE TITLE
Improve Dashboard Conformity across pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2578]
* Dashboard page link "Create Skill" button to create skills only (not bots!)
* On My Skills page (https://susi.ai/myskills) 
   * change headings to H1 and 
   * move "Create a new skills" to the end of the list.
* On My Bots page (https://susi.ai/mybots):
  * take out "My Bots" heading (it is repetitive)
  * change other headings to H1
   * move "Create a new bot" to the end of the list.
* On all pages decrease gray area padding below secondary menu
![Screenshot from 2019-07-15 22-17-24](https://user-images.githubusercontent.com/1583873/61246123-68db4900-a74e-11e9-83e9-afc0bdb4e1af.png)

**Comment by samagragupta** [comment]
I will work on this

**Comment by harsh-jindal** [comment]
Taking this up.

**Comment by samagragupta** [comment]
@harsh-jindal I am working on this.
I will create a PR on this today

**Comment by harsh-jindal** [comment]
@samagragupta I haven't seen you working on this checked your last 2 days scrums before taking it up. You had commented 11 days ago on this. I am almost done with this issue. Please try to solve the remaining issues taken up by you quickly.
