### ISSUE TITLE
Skills filter page - fix design and filters

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2580]
* Align Sort by, and Skills per page
* Delete option to choose page on top
* Show the current sorting option when opening the page
* Fix filter "top rated" - it should show the skills that are top-rated, but it shows the skills that are rated by most users
* Add a filter "Most rated", which actually shows the skills that are rated by the most people

![Screenshot from 2019-07-15 22-23-50](https://user-images.githubusercontent.com/1583873/61246827-10a54680-a750-11e9-9a24-ce4d9ae16202.png)

**Comment by mariobehling** [comment]
I have added more details to the issue itself.

**Comment by fragm3** [comment]
Thanks!
