### ISSUE TITLE
Clear between headline and **** selection

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi.ai#2581]
**Actual Behaviour**

A "clear" link is placed between the "Avg. Customer Review" headline and 
```
****  & Up
***   & Up
**     & Up
*      & Up
```

**Expected Behaviour**
It needs to be clear what the clear link relates to.

**Steps to reproduce it**
Click 4 Stars on https://susi.ai/

**Comment by harsh-jindal** [comment]
Will take this up.

**Comment by akshatnitd** [comment]
I think `Clear` is quite obvious. It was done following Alexa's approach.
