### ISSUE TITLE
Slider - lots of artefacts

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi.ai#2583]
**Actual Behaviour**
The current slider image (screenshot below) has too strong artefacts.
![bannerartefakts](https://user-images.githubusercontent.com/10114907/61250147-439f0880-a757-11e9-96e5-44d41aa3ad9b.png)

**Expected Behaviour**
Better visual quality. Also the check marks are not in line and distance differs. Language and case is unclear.

**Comment by fragm3** [comment]
Updated the slider, closing
