### ISSUE TITLE
SLIDER - Fonts inconsistent

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi.ai#2584]
**Actual Behaviour**

The slider images use different but similar sans-serif fonts.

**Expected Behaviour**

Use the same font and style.

**Comment by mariobehling** [comment]
Actually this is a feature to attract attention. There are different design schools and approaches. It is not really a bug.

**Comment by tabesin** [comment]
It's not a feature here, it is bad design and shows that no one is paying attention to detail.
