### ISSUE TITLE
Include libraries/components/css in repo instead of calling it from external sources

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2585]
We have external dependencies like https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.2/leaflet.css. Instead of making this an external dependency, please include it in the repository itself. We are using CNDs anyways for this repo, but if we run the site locally it will only work if people are not connected to the Internet. Also some people dont want to use external libraries for privacy reasons. Please take out dependencies whereever possible therefore.

**Comment by akshatnitd** [comment]
Working on it
