### ISSUE TITLE
Admin: Dashboard - Provide sufficient space for numbers in color boxes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2586]
The current color boxes are only suitable for three digit numbers. Please change the style to be usable for larger numbers.

![Screenshot from 2019-07-16 01-30-11](https://user-images.githubusercontent.com/1583873/61255564-6b976780-a769-11e9-96b9-5703deb465bc.png)

**Comment by harsh-jindal** [comment]
Will take this up
