### ISSUE TITLE
Add Wolfram Alpha to admin config

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2606]
SUSI.AI is using a number of APIs, which should be configurable through the admin UI. Specifically SUSI.AI is using Wolfram Alpha for console services. Please add an abstraction layer to the SUSI.AI server and add the option to add a key in the admin config tab.

![Screenshot from 2019-07-16 22-28-35](https://user-images.githubusercontent.com/1583873/61327384-13b83980-a819-11e9-92b7-6cc849dd1cb0.png)

**Comment by fragm3** [comment]
Working on it

**Comment by mariobehling** [comment]
The Wolfram Alpha key does not show up on the live site. Therefore this issue is not finished.

![Screenshot from 2019-07-29 11-38-38](https://user-images.githubusercontent.com/1583873/62038143-7a642c80-b1f5-11e9-8417-45df380ae108.png)

**Comment by akshatnitd** [comment]
@mariobehling @Orbiter We need to replace the value of Wolfram Alpha API key from the config of the deployed instance of SUSI.AI server. Can you help with that?

**Comment by fragm3** [comment]
@mariobehling this issue is done, you just have to replace the wolframalphaKey in admin panel.

**Comment by mariobehling** [comment]
Ahh ok. Thanks!
