### ISSUE TITLE
Slideshow: Rework the "play shakira" slide using a picture

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2609]
Create a slide for the "Play Shakira" slide using the Shakira image here: https://www.imdb.com/title/tt6837496/mediaviewer/rm2201896704

**Comment by fragm3** [comment]
![000](https://user-images.githubusercontent.com/18073126/61405472-8b5c9600-a8f7-11e9-9bc4-da057d1ea71f.png)

**Comment by akshatnitd** [comment]
Done
