### ISSUE TITLE
Admin: Add Devices Tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2611]
The admin area has an overview of skills. However devices are missing. Please implement a tab "Devices".

Include as much information as possible in the table. Also add the connected user info to the account and provide a link to the device page.

Compare: https://susi.ai/admin/skills
![Screenshot from 2019-07-14 19-03-37](https://user-images.githubusercontent.com/1583873/61186837-466fff80-a66a-11e9-99d7-3318b08e6bb8.png)

**Comment by harsh-jindal** [comment]
@mariobehling Connected devices info of users is available in the users tab. You want a separate tab listing all the devices connected. Am I right ?

**Comment by harsh-jindal** [comment]
Taking this up.
