### ISSUE TITLE
Admin: Add options for Matomo and Google Analytics

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2612]
Currently we are collecting site info using atomo.anomic.de/piwik.js:1. Please implement config options for analytics tools in the admin section. So, admin users can add the Google or Matomo key. Open an issue and PR on the server to store the info accordingly.

**Comment by fragm3** [comment]
@mariobehling unable to find any related keys. Google Analytics is not setup I think.

**Comment by mariobehling** [comment]
Matomo is not implemented as expected. There is a site-ID added as a config option, but there is no option to enter the actual site to connect to. The goal is to be able to configure this independently, instead you still have the site hardcoded.

**Comment by mariobehling** [comment]
![Screenshot from 2019-07-29 11-27-44](https://user-images.githubusercontent.com/1583873/62037389-ff4e4680-b1f3-11e9-899c-4392f1923df9.png)

Where is an option to choose the location of the website of the Matomo installation to connect with?

**Comment by mariobehling** [comment]
![Screenshot from 2019-07-29 11-29-54](https://user-images.githubusercontent.com/1583873/62037562-4c321d00-b1f4-11e9-95e8-11b49d909f39.png)
 I found it in the same table in another area. This does not make sense. The user needs to be able to see and edit everything at ones.

**Comment by mariobehling** [comment]
Please change as follows:
* Change table headers to show: Key Name | URL/Script | Key Value | Actions
* Delete S.No (It is not needed)

**Comment by fragm3** [comment]
Okay, will make the changes

**Comment by fragm3** [comment]
Will implement these changes on the backend after https://github.com/fossasia/susi_server/pull/1355 is merged.

**Comment by mariobehling** [comment]
The implementation of the top and side spacing of the table is not following the common design laid out in the skill admin page yet. Therefore reopening it.

![Screenshot from 2019-08-05 11-24-49](https://user-images.githubusercontent.com/1583873/62454024-d4c03880-b773-11e9-9fc5-bac7256bd50e.png)

**Comment by fragm3** [comment]
Fix in other PR, closing.
