### ISSUE TITLE
Footer: Increase gray area bottom by about 30-40 px to show the menu above the chat icon

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2613]
The contact link is currently hidden by the chat icon on top. Please increase gray area bottom by about 30-40 px to show the menu above the chat icon when scrolling it up.

![Screenshot from 2019-07-17 11-08-27](https://user-images.githubusercontent.com/1583873/61362977-75ad8900-a883-11e9-91e4-b97f83d079b5.png)

**Comment by samagragupta** [comment]
Will do it.
