### ISSUE TITLE
Options to stop a skill, reduce the volume of playing music

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2614]
When the web client uses the sound output, there is no way to stop the output. How could we achieve this and stop the sound output in regards to:
* stop music from playing
* stop reading out long articles

How to use the stop or pause command?

**Comment by fragm3** [comment]
@mariobehling we can have a button to stop the currently playing audio

**Comment by mariobehling** [comment]
Sure, there are buttons for YouTube already. Would be good to have it for other skills too. Final goal would be to stop this with a voice command "stop".

**Comment by fragm3** [comment]
@mariobehling Okay, I'll try implementing it
