### ISSUE TITLE
Mobile: clicking on example bubble opens answer but previous messages are not available

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2623]
Clicking on the example bubble opens a chat screen with the answer only. There are no previous interactions and no scroll bar.

![Screenshot_2019-07-17-19-41-33-876_com android chrome](https://user-images.githubusercontent.com/1583873/61398430-47a06700-a8cc-11e9-9ba7-07c665f403aa.png)

**Comment by harsh-jindal** [comment]
@mariobehling From the server only last 5 message pairs(q & a) when the chat is loaded (i.e. on toggle of the chat bubble) are sent. I have tested and I am unable to reproduce the bug pointed out by you. The scrollbar will only appear if the messages exceed the height of the viewport screen.
Can you please check again if you have still have the issue ?
