### ISSUE TITLE
Fix bugs related to skillcreation and botcreation and followups

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2644]
**Actual Behaviour**

The skillcreation, botcreation is not robust. Once a user has created skills, not able to see the skills in Dashboard

**Expected Behaviour**

Fix related bugs

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Some issues pointed by @Orbiter 
For example,
if I start editing in the edit window, there is a strange effect where the cursor jumps to the end of the editing line and the first letter I typed is behind the cursor
storage is not possible without an image
after storage the image is not visible
I cannot find the skill after storage in the web front-end (its not searchable and is not browsable)

**Comment by fragm3** [comment]
For point 1: I am having no issues for editing a skill, the problem comes only for skill: https://susi.ai/Communication/EnglishAIMLL/edit/en. The code is of 17,000 lines in that skill so it takes time. For other skills, it's working completely fine

For point 2: Should we allow creation without an image?

For point 3: Working fine for me

For point 4: Looking more into this

**Comment by mariobehling** [comment]
> Storage is not possible without an image.

@fragm3 Yes, storage should be possible without an image.

**Comment by fragm3** [comment]
Search issue on server side, no problem from frontend
