### ISSUE TITLE
Menu Bar icons on the right disappear on small screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2656]
When user emails or a long name is displayed on the top menu bar the top right icons disappear. To do:
* reduce size of search bar a bit
* show only given name. If names are still longer show ".." after 21 characters.

![Screenshot from 2019-07-22 22-57-30](https://user-images.githubusercontent.com/1583873/61665153-9b4bef80-acd4-11e9-81b2-a09cccf2b609.png)

**Comment by harsh-jindal** [comment]
@mariobehling Will take this up.
