### ISSUE TITLE
Fix scroll behaviour in chat app

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2665]
**Actual Behaviour**

- If user search, for example, the scroll to bottom animation happens
- On trying an example, the chat window goes to the top

**Expected Behaviour**

Should be at bottom by default

**Would you like to work on the issue?**

Yes

**Comment by tanujvyas10** [comment]
hello @fragm3 ,i am new to this group ,i want to contribute too,can i work on this bug ?
Reply soon ,thank you
