### ISSUE TITLE
menu under "?" is not completely inside the screen 

### ISSUE THREAD

**Issue by tanujvyas10** [fossasia/susi.ai#2671]
**Actual Behaviour**
menu that pops by hovering on "?" is not completely inside the screen 
![susi1](https://user-images.githubusercontent.com/48439116/61859943-bdb55700-aee6-11e9-8eb7-cf99f212fefa.jpg)
**Expected Behaviour**
menu should be completely inside the the screen

**Would you like to work on the issue?**
Yes , i would like to work on it

**Comment by tanujvyas10** [comment]
@fragm3  Hello sir,i dont have good knowledge of github ,i am getting problem in creating the PR , i have fixed the bug but when i am creating the pr its showing the following
![prerr](https://user-images.githubusercontent.com/48439116/61895239-d5fd9400-af2f-11e9-8805-8caa9a69f714.jpg)

**Comment by fragm3** [comment]
@tanujvyas10 Error can be navigated through the link: https://travis-ci.org/fossasia/susi.ai/builds/563643831?utm_source=github_status&utm_medium=notification.

I think you force committed your code, prettier formatting is done while pushing your code, make sure you **do not add --no-verify** while committing

**Comment by tanujvyas10** [comment]
@fragm3  i have commited the code in the forked repo online  because it was a small change (and i was getting problem in cloning the repo in my system).But it cannot able to pass the travis-ci checks,i have tried alot and even make changes according to the travis-ci detail link in which the errors are mentioned but its showing the same problem again and again,may be if you get time, you may help me via teamviewer ,if you dont mind.My gmail is :- tanujvyas10@gmail.com.Thank you .Reply soon

**Comment by tanujvyas10** [comment]
@fragm3  thank you for your help sir , i have successfully created my PR,Please review my work
