### ISSUE TITLE
Show LoginsOverTime and SignUpOverTime in AdminPanel

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi.ai#2685]
**Actual Behaviour**
Not present. Fixed the issue on server side in https://github.com/fossasia/susi_server/pull/1340

**Expected Behaviour**
Add it.

*Would you like to work on the issue?**
Yes

**Comment by fragm3** [comment]
@harsh-jindal it's already added, once the API works, you'l be able to see them in admin panel
