### ISSUE TITLE
Enhance preview chat

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2686]
**Actual Behaviour**

Currently, only the bubble is shown

**Expected Behaviour**

Enhance current chat preview

Options:

1. Play Youtube video
2. Play SoundCloud song
3. Show me an image
4. Tell me a joke

Simple chat now, and basic 3-4 chat select options user can see:

Design Idea 1:
<img width="231" alt="Screenshot 2019-07-27 at 11 24 02 PM" src="https://user-images.githubusercontent.com/18073126/61997981-d11f1880-b0c6-11e9-8feb-2396e5f290dd.png">
<img width="416" alt="Screenshot 2019-07-27 at 11 24 30 PM" src="https://user-images.githubusercontent.com/18073126/61997982-d1b7af00-b0c6-11e9-9e16-32f7299f2a5c.png">

Idea 2, For first time user:

<img width="401" alt="Screenshot 2019-07-27 at 11 27 59 PM" src="https://user-images.githubusercontent.com/18073126/61997983-d1b7af00-b0c6-11e9-80b1-5710529d1f2e.png">

We can show the top used skills:

<img width="381" alt="Screenshot 2019-07-27 at 11 31 59 PM" src="https://user-images.githubusercontent.com/18073126/61997985-d2e8dc00-b0c6-11e9-8915-91d96e9ca292.png">

Idea 3:

<img width="408" alt="Screenshot 2019-07-27 at 11 34 17 PM" src="https://user-images.githubusercontent.com/18073126/61998010-2824ed80-b0c7-11e9-920d-0a28e6fac01e.png">
<img width="430" alt="Screenshot 2019-07-27 at 11 34 49 PM" src="https://user-images.githubusercontent.com/18073126/61998011-2824ed80-b0c7-11e9-9b60-0917426c67d5.png">

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
@mariobehling @akshatnitd @Orbiter @harsh-jindal please share your points.

**Comment by mariobehling** [comment]
Yes, I think you understand now where we are heading. The examples you are giving here need a lot of work. We need to allow people to add their config/settings preferences as a chat for example. We also need a skill "What can I with SUSI.AI"

**Comment by harsh-jindal** [comment]
I think idea 3 looks good. We can have the options suggested by you show up in the list when the user first time opens the chat along with a message like `Hey, I'm SUSI.AI ! Here are a few things I can do` or something like that. This can be the first step IMO, as we already have skills for the options listed in issue description.

**Comment by akshatnitd** [comment]
Here is an issue that also talks about it - 
https://github.com/fossasia/susi.ai/issues/2113
