### ISSUE TITLE
Fix the language popover 

### ISSUE THREAD

**Issue by chauhanparth210** [fossasia/susi.ai#2691]
**Actual Behaviour**
When you de-select all the languages it  displays "-" and  popover  is not closed .

**Expected Behaviour**
When you de-select all the language , by default it should display English and close the popover.

**Screenshots of the issue**
![Screenshot](https://user-images.githubusercontent.com/35137224/62002531-c34bb080-b123-11e9-986f-254a8a458010.png)

**Would you like to work on the issue?**

**Comment by abhi1381** [comment]
hey @chauhanparth210, I want to work on this issue #2691

**Comment by tmw9** [comment]
Hey @mariobehling  @chauhanparth210 , if this issue is still open, and no one is working on it, Can I take it up?

**Comment by Dilshaad21** [comment]
@chauhanparth210 can I take up this issue

**Comment by chauhanparth210** [comment]
@Dilshaad21 Ok I am not working on it so go ahead..
