### ISSUE TITLE
Settings page breaking on local device

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2695]
**Actual Behaviour**

@akshatnitd as discussed, the settings page breaks

**Expected Behaviour**

Find a fix for it

**Steps to reproduce it**

While trying to connect through env variable

**Would you like to work on the issue?**

Yes

**Comment by alok760** [comment]
![image](https://user-images.githubusercontent.com/14289201/62004467-09fcd300-b143-11e9-9059-b69b08435db7.png)

**Comment by akshatnitd** [comment]
Working on it to resolve it quickly
