### ISSUE TITLE
Add webpack, react-loadable to improve performance

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2702]
**Actual Behaviour**

As the project is getting bigger, it would be a good point to integrate webpack which would allow us to load components asynchronously.

**Expected Behaviour**

Webpack will reduce the initial load time by splitting the code into modules and we can asynchronously load the code using `react-loadable`. It will help in optimizing better web performance

It will help us import inline SVG's(required for slideshow)

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
That would be great. CRA internally uses Webpack. You need to check out how can we add a custom webpack config.

**Comment by kpulkit29** [comment]
@fragm3 would like to work on this issue.

**Comment by akshatnitd** [comment]
@kpulkit29 You can work on it.
