### ISSUE TITLE
Unnecessary notification below password in the Login Panel

### ISSUE THREAD

**Issue by tanujvyas10** [fossasia/susi.ai#2704]
**Actual Behaviour**
In the Login panel, below password, it show the error notification -"Password should be at least 6 to 64 characters",which is totally unnecessary because user have to input the exact password that he/she used during signup.

**Expected Behaviour**

The following password error notification should be removed 

**Screenshots of the issue**
![pass_Comm](https://user-images.githubusercontent.com/48439116/62019757-e9358b80-b1dd-11e9-8473-7519aa182997.jpg)

**Would you like to work on the issue?**
Yes ,i would like to work on it

**Comment by mayankraghuwanshi** [comment]
I want to take up this issue. 
@mariobehling 
@harsh-jindal

**Comment by tanujvyas10** [comment]
@mayankraghuwanshi hello Mayank , i have proposed the PR for this issue, but the mentors didn't accept it due to some reason. I want to work on it again, Please let me resolve this issue.
@mariobehling @harsh-jindal, is this issue appropriate to work on,If yes i want to work on this issue again, if you allow me. Reply soon, Thank you

**Comment by mayankraghuwanshi** [comment]
@tanujvyas10 ok, you can continue.

**Comment by anishagg17** [comment]
@akshatnitd it has been resolved by  #3280
