### ISSUE TITLE
Getting email link for "Forget password" even for a unregistered email address

### ISSUE THREAD

**Issue by tanujvyas10** [fossasia/susi.ai#2705]
**Actual Behaviour**
When a user is selecting "forget password" and entering the unregistered email address,he/she is still getting the email for reset the password.

**Expected Behaviour**
When a unregistered person go for "forget password" and enters a unregistered email , the person should get a notification under the email label that "User is not registered."

**Screenshots of the issue**
![unreg2](https://user-images.githubusercontent.com/48439116/62020688-9958c380-b1e1-11e9-9e9d-7069f3018563.jpg)
![unreg1](https://user-images.githubusercontent.com/48439116/62020690-99f15a00-b1e1-11e9-8e5b-b6d29b40f52e.jpg)

**Would you like to work on the issue?**
Yes i would like to work on this issue

**Comment by akshatnitd** [comment]
An error shows up for me if user is already registered. Please reopen the issue, if it still exists.
