### ISSUE TITLE
Admin Dashboard: Show box "Devices" and "Devices over Time"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2706]
In the admin dashboard, please add:
1. A box "Devices" with info:
* Number of All devices
* Number of Connected Devices
* Number of Inactive Devices
* Number of Deleted Devices
* Number of Users that have Devices Connected (users can connect several devices, so this number is relevant as well)
2. A chart with Connected Devices over Time
![Screenshot from 2019-07-29 08-46-52](https://user-images.githubusercontent.com/1583873/62027403-ea66b880-b1dd-11e9-8030-07642574774e.png)

**Comment by harsh-jindal** [comment]
Taking this up.
Will create make a PR for the data on the server.

**Comment by harsh-jindal** [comment]
@mariobehling Can you please explain what do you mean by inactive devices? Also user can delete the device and it back with same macId. So do we need to have the number of deleted devices data ? If we want to avoid the above scenario then even after deleting the device we will need to store the data for it, which is not a good option.

**Comment by harsh-jindal** [comment]
Currently in PR made on the server I am displaying number of connected devices and device users. https://github.com/fossasia/susi_server/pull/1351

**Comment by mariobehling** [comment]
> @mariobehling Can you please explain what do you mean by inactive devices?

Please show the info if device is "currently" connected/online or if it is not connected/offline/cannot be reached at this moment.
