### ISSUE TITLE
Make Admin Dashboard subtabs uniform, use material-table

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2709]
The skills tabs "Deleted" and "Reported" at https://susi.ai/admin/skills are not following the same structure as the previous tabs. Please add missing columns and follow the same design and structure for all tabs in admin panel, use material-table

![Screenshot from 2019-07-29 09-47-40](https://user-images.githubusercontent.com/1583873/62030752-12f2b080-b1e6-11e9-88f3-854c3b406675.png)

**Comment by fragm3** [comment]
Working on it
