### ISSUE TITLE
My Devices: Add "Date Added", "Last Connected" date and "IP Address"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2714]
In the My Devices table (https://susi.ai/mydevices) and actual device page (https://susi.ai/mydevices/[MAC Address] please change the following:
* Change column order as follows: Name | Room | Location | MAC Address | Date Added | Last Connected | IP Address
* Include columns date added, last connected, IP Address (Dates should include time, IP Address shows last used IP address)
* Make each column sortable

![Screenshot from 2019-07-29 10-25-20](https://user-images.githubusercontent.com/1583873/62033471-4d5f4c00-b1ec-11e9-9a4c-09812e74b166.png)

**Comment by harsh-jindal** [comment]
@akshatnitd @fragm3 @mariobehling IP address and last connected means ip at the time of login and the last login time into the account respectively. Right? So if a user has many devices to one account how to identify each one of them uniquely?

**Comment by fragm3** [comment]
@harsh-jindal just implement basic functionality. Edge cases could be handled in further PR's
