### ISSUE TITLE
Chat box: Opening it does not go to end of conversation and Top icon does not close chat box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2718]
![Screenshot from 2019-07-29 11-46-19](https://user-images.githubusercontent.com/1583873/62038754-9f0cd400-b1f6-11e9-8d23-bd5fa9ea910c.png)

Please fix the following:
1. Opening the chat box does not go to end of conversation. 
2. Top icon does not close chat box when the chat box is open.

**Comment by samagragupta** [comment]
On it

**Comment by fragm3** [comment]
@mariobehling The chat preview closes on the close icon, 1st is present

**Comment by samagragupta** [comment]
@fragm3 The chat icon on the header is not closing the chat window.

**Comment by fragm3** [comment]
It is actually not a bug, chat icon is supposed to open the chat, not toggle it

**Comment by samagragupta** [comment]
@fragm3 https://github.com/fossasia/susi.ai/pull/2699#issuecomment-515927930

**Comment by akshatnitd** [comment]
@fragm3 Make it to toggle. Also, the maximise button click broken UI.

**Comment by samagragupta** [comment]
@fragm3 As @mariobehling mentioned: https://github.com/fossasia/susi.ai/pull/2699#issuecomment-515927930

**Comment by fragm3** [comment]
Thanks, working on it

**Comment by mariobehling** [comment]
No, yet working.

**Comment by fragm3** [comment]
@mariobehling I was working on this, had to leave in middle due to samagra and turns out he didn't solve it and PR got merged as well. Looking into this.
