### ISSUE TITLE
Buttons and Dropdowns: Make them uniform: Spacing, Size, Alignment, Color

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2722]
Please make all buttons uniform as follows:
* Keep the same space between icons and text in button (current spacing is often too large, please adjust it as well)
* Ensure all buttons have the same color in standard view and on scroll over (Create button on the start page appears darker on scroll over than scrolling over the top menu items for example)
* Make all buttons the same height and same spacing to the left and right (keep a minimum size of buttons as well so it fits nicely into the design of the page)
* Add icons where they are missing, e.g. Create dropdown menu
* Align all text/icons in buttons in center
* Make any other changes to keep all buttons consistent.

Some screenshots to portray inconsistencies of buttons and dropdowns below:

![Screenshot from 2019-07-29 18-39-59](https://user-images.githubusercontent.com/1583873/62066244-05164d00-b231-11e9-961b-00e68d56122a.png)
![Screenshot from 2019-07-29 18-39-46](https://user-images.githubusercontent.com/1583873/62066245-05aee380-b231-11e9-834d-58faeecb2e94.png)
![Screenshot from 2019-07-29 18-38-57](https://user-images.githubusercontent.com/1583873/62066248-05aee380-b231-11e9-8038-2c08684b5acd.png)
![Screenshot from 2019-07-29 18-39-16](https://user-images.githubusercontent.com/1583873/62066246-05aee380-b231-11e9-882e-0c883220537e.png)
![Screenshot from 2019-07-29 18-38-53](https://user-images.githubusercontent.com/1583873/62066249-05aee380-b231-11e9-9e72-f4d127e2b30e.png)
![Screenshot from 2019-07-29 18-38-46](https://user-images.githubusercontent.com/1583873/62066250-05aee380-b231-11e9-9a8e-9e3a3f30ab36.png)

**Comment by chauhanparth210** [comment]
@mariobehling  I am doing to do it.

**Comment by AuraOfDivinity** [comment]
I'd like to work on this issue.
