### ISSUE TITLE
Fix the dual audio bug and console log errors

### ISSUE THREAD

**Issue by chauhanparth210** [fossasia/susi.ai#2728]
**Actual Behaviour**
When you "play xxx(shakira) on youtube" type on susi assistant and go for full screen mode , it plays two individual audio of that video and continuous playing video and display errors on console too.

**Expected Behaviour**
It simply pause the video and not playing dual audio while switching from susi assistant to full screen mode.

**Screenshots of the issue**
![Screenshot (13)](https://user-images.githubusercontent.com/35137224/62103855-5c60ff80-b2bb-11e9-8832-3173ad653ce5.png)

**Would you like to work on the issue?**
Yes

**Comment by chauhanparth210** [comment]
I am not able to register and log in into the system, plz help me !!

**Comment by fragm3** [comment]
@chauhanparth210 try now

**Comment by chauhanparth210** [comment]
Ok @fragm3  I will try.

**Comment by chauhanparth210** [comment]
Hello @fragm3, I will definitely try to solve this bug.

**Comment by mariobehling** [comment]
This is working now. Great! Closing it therefore.
