### ISSUE TITLE
Dropdown: Below dashboard link add "My stuff"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2733]
In the dropdown menu below "Dashboard" add
* My Skills
* My Bots
* My Devices
* A divider below "My Devices"

![Screenshot from 2019-07-29 18-38-46](https://user-images.githubusercontent.com/1583873/62119268-7a306380-b2bf-11e9-9c78-85cd11e05a42.png)

**Comment by samagragupta** [comment]
On it.
