### ISSUE TITLE
Chat box: Full Screen Mode no longer working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2736]
The full screen mode moves the chat box behind the page content and the chat icon disappears.

![Screenshot from 2019-07-30 12-50-45](https://user-images.githubusercontent.com/1583873/62123721-d350c500-b2c8-11e9-8016-033668818522.png)

**Comment by samagragupta** [comment]
It's working for me.
![Capture](https://user-images.githubusercontent.com/32234926/62124032-de1a5280-b2e6-11e9-8917-62d799c39bb4.JPG)

**Comment by harsh-jindal** [comment]
Working on it.
