### ISSUE TITLE
Make Create Pages and Add Device Page more Consistent

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2738]
The design of the create and add device page is inconsistent. The first row of the page has a different spacing. Device page has a gray background area. Below is a screenshot for the bot page. Please:
* design bot and create skill page according to this layout
* implement a gray background as shown in the picture (following the device page).
* For a new skill or bot always show the category "General" as pre-selected
* For a new skill or bot always show the language "English" as pre-selected
* Design the skill or bot name field in the same way as category and language field
* Make the field locations responsive (on large screen they should show up next to each other and move to the next line when there is not enough space, e.g. when the preview area is shown)
* Show the SUSI.AI logo in the picture field with a + sign on the bottom right corner (or sth. similar / If the user does not have their own picture, it can simply show the SUSI.AI logo)

![Screenshot from 2019-07-30 15-32-10](https://user-images.githubusercontent.com/1583873/62134801-6e559900-b2e1-11e9-934e-b43bce48e432.png)

The screenshot shows the full page view without the preview box. Keep the preview box area with the white background as is.

**Comment by fragm3** [comment]
@mariobehling there is no category called general, would could be other default alternatives for category?

**Comment by mariobehling** [comment]
> @mariobehling there is no category called general, would could be other default alternatives for category?

Ok, please choose "Knowledge" as default.

**Comment by fragm3** [comment]
Okay, thank you
