### ISSUE TITLE
Create Skills and Bot: Minimize space needed for dropdown choices and improve (i) icon

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2741]
Category, language and skills name should require less space. In an earlier version of the page the form field names were listed above the field.

1. Please implement it in the same way again.
Something similar to this:
![Screenshot from 2019-07-31 01-47-29](https://user-images.githubusercontent.com/1583873/62173499-902d3b00-b336-11e9-94e5-da5de14c0a92.png)

2. Regarding the i - icon
* Increase the size
* Make it blue
* For the tool tip and link displayed use the same colors as used on the top menu dropdown

**Comment by samagragupta** [comment]
Will do it.

**Comment by fragm3** [comment]
@mariobehling I am already working on this: https://github.com/fossasia/susi.ai/pull/2740

**Comment by mariobehling** [comment]
@fragm3 Well, we need you guys to coordinate each other a bit more. I guess @samagragupta should just finish his part now and you can integrate his work.
