### ISSUE TITLE
Add device setup page for SUSI smart speaker

### ISSUE THREAD

**Issue by alok760** [fossasia/susi.ai#2742]
When the speaker is booted for the first time. The web client on `ip-of-speaker:7070`
should display the the device page setup.

currently this page is available on `ip-of-speaker:7070/setup` : https://github.com/fossasia/susi_installer/blob/development/raspi/controlserver/templates/setup.html

The flask server which serves both the webclient and the setup page: https://github.com/fossasia/susi_installer/blob/development/raspi/controlserver/controlserver.py

**Comment by alok760** [comment]
I have added /check_ap endpoint that returns {"status": "True"} if the device is in Access Point mode. https://github.com/fossasia/susi_installer/pull/80

**Comment by alok760** [comment]
The preferred plan is - 
* when the webpage is loaded, use javascript and check if the device is in access point mode using the /check_ap endpoint
* If true redirect to the integrated setup page

**Comment by fragm3** [comment]
@alok760 Thanks, working on it.
