### ISSUE TITLE
Add device configuration options to the control page for the Smart Speaker

### ISSUE THREAD

**Issue by alok760** [fossasia/susi.ai#2743]
![image](https://user-images.githubusercontent.com/14289201/62197156-33c91c00-b334-11e9-8f36-f882b4a663dd.png)
Add the following configuration options to the control options-
* Set Speech To Text(STT) and Text To Speech(TTS)
* Set Hotword engine
* Enable/Disable the wake button

The endpoint (`/config`) for these methods are already available in https://github.com/fossasia/susi_installer/blob/development/raspi/controlserver/controlserver.py

**Comment by alok760** [comment]
@fragm3 
STT can have values: `google` or `watson` or `bing` or `pocketsphinx`
TTS should can values: `google` or `watson` or `flite`
wakebutton should have values: `y` or `n`  
hotword should have values: 'Snowboy' or `PocketSphinx`

**Comment by fragm3** [comment]
Thanks, great help @alok760
