### ISSUE TITLE
Message Bubble generated twice on test example in mobile view

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi.ai#2747]
**Actual Behaviour**
Currently if you click on test skill example in mobile view the answer bubble appears twice.

**Expected Behaviour**
Fix it.

**Steps to reproduce it**
Open susi.ai in mobile view.
Click on any test skill example bubble.

**Screenshots of the issue**
![Screenshot 2019-07-31 at 9 13 16 PM](https://user-images.githubusercontent.com/31013104/62226606-1057ad00-b3d8-11e9-9ea4-b4d2558bb337.png)

**Would you like to work on the issue?**
Yes

**Comment by harsh-jindal** [comment]
@fragm3 Can you take a look at this. I tried fixing it but it has some weird behaviour because the generateMessage works once for the preview state but for the mobile view it executes twice.

**Comment by fragm3** [comment]
Okay, working on it

**Comment by fragm3** [comment]
Working fine for me:
<img width="433" alt="Screenshot 2019-08-01 at 2 56 22 AM" src="https://user-images.githubusercontent.com/18073126/62249415-fb930d80-b407-11e9-9b84-8c46b6cc4759.png">
