### ISSUE TITLE
Create Skills/Bots Page: Make Preview Consistent with Standard Chat Box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2751]
For the preview window on https://susi.ai/skillWizard and https://susi.ai/botWizard please reuse the standard chat box of the system.

![Screenshot from 2019-07-31 20-17-48](https://user-images.githubusercontent.com/1583873/62237014-81936200-b3d0-11e9-94d7-6889cb185e34.png)

**Comment by harsh-jindal** [comment]
@mariobehling Do we need to keep two chatbubbles on this page one inside preview and one that is present at the bottom right of every page?

**Comment by harsh-jindal** [comment]
Also can I update the preview chat code to make it look like the current one because reusing the current chatapp code is a bit tricky as we are handling it state by redux, so if i click on one chatbubble both will open. Else I will have to define separate functions and then pass to the component to use.
@akshatnitd @fragm3 Your views on this.

**Comment by fragm3** [comment]
@harsh-jindal The chat bubble will be hidden after PR https://github.com/fossasia/susi.ai/pull/2723 is merged. We will be showing only preview in this page

**Comment by fragm3** [comment]
@harsh-jindal I can pick this up if you want

**Comment by mariobehling** [comment]
Please make the preview look more closely to the front page chat box.
* Use the same width and height. 
* Make the right side area with a white background. (While the using the gray area as a background was a good idea to make things look consistent, we don't fit the whole box on small screens when following this approach. 
* Also therefore, please reduce the space between the word "Preview" and the chat box below and fit the chat box in the same area as on the front page.
![Screenshot from 2019-08-05 10-52-55](https://user-images.githubusercontent.com/1583873/62452342-44342900-b770-11e9-9722-3e2a1568f9e3.png)
* When minimizing the chat preview expand the right-side to the same distance/spacing to the browser edge as the device page (it was implemented like that before)
![Screenshot from 2019-08-05 10-53-53](https://user-images.githubusercontent.com/1583873/62452327-3aaac100-b770-11e9-8ac3-1d86400287ca.png)
