### ISSUE TITLE
Create Skill: Add Slider button to offer choice of Open Source / Public Skill vs. Private Skill

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2763]
Let's prepare the option for Open Source/Public Skills vs. Private Skills. On the skill create page https://susi.ai/skillWizard:
* provide a slider button in the top form area "Open Source and Public Skill (pre-selected) to be switched "on"
* when switched off show "Private Skill"
* behind that show a question mark "?". Clicking on this shows the following text: "Open Source Skills will show in the public directory and are editable by everyone just like a Wikipedia article. Private skills are only editable by the creator/owner of the skill. They are not listed in the public directory and can currently only be used by the creator/owner."

**Comment by chauhanparth210** [comment]
@mariobehling  Sir I want to try this and by tomorrow I will mostly commit it and if I facing any obstetrical I will defiantly ping you . Thank you sir.

**Comment by harsh-jindal** [comment]
@chauhanparth210 IMO let the developers handle this issue, please try to take on issues labeled as bug or for first time contributors.

**Comment by chauhanparth210** [comment]
Ok @harsh-jindal

**Comment by harsh-jindal** [comment]
@mariobehling Clicking on the `?` should show a tooltip or open a modal ?

**Comment by mariobehling** [comment]
* Please stick to International English. Add a space in front of "(".
* Use an icon for "?" instead of text.
* Show the UI working. Currently the user is not able to slide.
