### ISSUE TITLE
Admin: Enhance message table

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2785]
Please change the message tab https://susi.ai/admin/messages table at as follows:
* Between "Trigger" and "Email Message" add column "Subject".
* Add column "View" on the very right. By clicking on view show a pop-up with the recipient type, subject and email.

![Screenshot from 2019-08-05 10-00-55](https://user-images.githubusercontent.com/1583873/62449016-755d2b00-b769-11e9-98f5-0d2e2ea91e32.png)

**Comment by fragm3** [comment]
@mariobehling wouldn't the second point be redundant, we are showing the exact same data in table also

**Comment by mariobehling** [comment]
Exactly, it is redundant at the moment, but it will not be redundant in future for longer and advanced messages. We are designing the UI with future requirements in mind.
