### ISSUE TITLE
Bottom of the page is not proper

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2786]
**Actual Behaviour**
Bottom of the page is not proper

**Expected Behaviour**

The footer should be implemented properly

**Steps to reproduce it**

https://susi.ai/admin/bots

**Screenshots of the issue**

![Capture](https://user-images.githubusercontent.com/32234926/62449830-abf66e00-b788-11e9-8925-d9237ae51931.JPG)

**Would you like to work on the issue?**

Yes

**Comment by samagragupta** [comment]
@mariobehling Should I remove footer or not?

**Comment by mariobehling** [comment]
I think no need for footer here currently.
