### ISSUE TITLE
Admin Message Tab: Add "Captcha" column with checkbox

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2796]
In the admin message at https://susi.ai/admin/messages tab please add a column with the option to activate or deactivate captcha.

![Screenshot from 2019-08-06 23-47-24](https://user-images.githubusercontent.com/1583873/62579760-e35a3d00-b8a4-11e9-8c7b-a17c5e6b8dfa.png)

**Comment by fragm3** [comment]
@mariobehling The table follows a certain pattern and rendering 1 specific checkbox won't be possible. This can be done in a new tab, without table

**Comment by mariobehling** [comment]
Please implement a checkbox for each message, e.g. enable it for one message, but not enable it for another message. This is the goal of the issue. I see the first PR you make does not actually tackle the issue.

**Comment by fragm3** [comment]
@mariobehling I got your point from comment, but the issue confused me. Will look into it.

**Comment by mariobehling** [comment]
Ok, thanks. I will try to formulate things more clearly in future.
