### ISSUE TITLE
Not getting Image from server(farmering.jpg)

### ISSUE THREAD

**Issue by chauhanparth210** [fossasia/susi.ai#2797]
**Actual Behaviour**
SUSI server is not able to sent the photo  "farmering.jpg" 

**Expected Behaviour**
It should be return an image "farmaring.jpg" 

**Screenshots of the issue**

![Screenshot (23)](https://user-images.githubusercontent.com/35137224/62605443-be52e200-b917-11e9-8c96-c085ad6bc8e4.png)

**Would you like to work on the issue?**
No

**Comment by chauhanparth210** [comment]
using url: https://api.susi.ai/cms/getImage.png?model=general&language=en&group=Utilities&image=images/farmaring.jpg  will return an image.

**Comment by Dilshaad21** [comment]
@chauhanparth210 can I take this issue?

**Comment by chauhanparth210** [comment]
Ok @Dilshaad2

**Comment by chauhanparth210** [comment]
Ok @Dilshaad21

**Comment by Dilshaad21** [comment]
@chauhanparth210 No such error is appearing in my browser when I tried to reproduce it.

**Comment by chauhanparth210** [comment]
@Dilshaad21, that's true , no such error is appearing in my browser too. (maybe someone solved it already)
