### ISSUE TITLE
UI/UX issue in Rating and Feedback Form Component 

### ISSUE THREAD

**Issue by theaayush8999** [fossasia/susi.ai#2808]
**Actual Behaviour**
Clicking on the star ratings brings Feedback form only without any rating option

**Expected Behaviour**
Clicking on the star ratings must bring both rating and feedback options.

**Steps to reproduce it**
1. Open Susi.ai web app
2. Scroll to Skill cards on home page
3. Click on the star rating icons 

**Screenshots of the issue**
![Screenshot from 2019-08-10 10-05-25](https://user-images.githubusercontent.com/32022442/62817550-740b7400-bb56-11e9-9efd-1f6fdbbe0dc0.png)
![Screenshot from 2019-08-10 10-00-11](https://user-images.githubusercontent.com/32022442/62817552-7bcb1880-bb56-11e9-8ef7-263a12d0a581.png)

**Would you like to work on the issue?**
YES

**Comment by AuraOfDivinity** [comment]
Is this issue still being worked on? If not I would like to work on it! :)
