### ISSUE TITLE
Improve documentation of SUSI.AI

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2811]
**Actual Behaviour**

Currently, documentation is old. Due to recent architecture changes, the documentation needs to be changed.

**Expected Behaviour**

Update and improve documentation 

**Would you like to work on the issue?**

Yes

**Comment by abhi1381** [comment]
I am willing to work on this issue.

**Comment by fragm3** [comment]
@abhi1381 already created a PR, do pick up another issue from the issue tracker, thanks

**Comment by abhi1381** [comment]
ok, thanks
