### ISSUE TITLE
Error from React Piwik

### ISSUE THREAD

**Issue by theaayush8999** [fossasia/susi.ai#2822]
**Actual Behaviour**
While running SUSI.ai on the local machine  gives error from Piwik

**Expected Behaviour**
Running susi.ai with no error on the Local Machine

**Steps to reproduce it**
1. Run 'yarn run start' on with the Latest Master Branch

**Screenshots of the issue**
![Screenshot from 2019-08-11 17-49-54](https://user-images.githubusercontent.com/32022442/62833807-3ac02a80-bc62-11e9-9904-a47097f80f06.png)

**Would you like to work on the issue?**
No

**Comment by fragm3** [comment]
Fixed in PR https://github.com/fossasia/susi.ai/pull/2820, thanks for reporting 👍
