### ISSUE TITLE
Hide Sort option when no skills are present

### ISSUE THREAD

**Issue by plxity** [fossasia/susi.ai#2825]
**Actual Behaviour**

![Capture](https://user-images.githubusercontent.com/28510494/62839899-3bcb7900-bcaf-11e9-860a-9abda90d2fac.PNG)

**Expected Behaviour**

When no skills are present, hide sort & filter option.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes, I would like to work on this.

**Comment by Dilshaad21** [comment]
@plxity may I take this issue if you are currently not working on it?

**Comment by plxity** [comment]
@Dilshaad21 I am working on it.
