### ISSUE TITLE
 Load groups action failed + Cannot read property 'staffPicks' of undefined

### ISSUE THREAD

**Issue by theaayush8999** [fossasia/susi.ai#2826]
**Actual Behaviour**
Getting error -  Load groups action failed + Cannot read property 'staffPicks' of undefined

**Expected Behaviour**
Running the master branch on the local machine without error

**Steps to reproduce it**
1. Clone master branch
2. Run "Yarn run start" for local host

**Screenshots of the issue**

![Screenshot from 2019-08-12 13-00-29](https://user-images.githubusercontent.com/32022442/62851015-5b3fc180-bd02-11e9-9769-23a92bd3e4f5.png)
![Screenshot from 2019-08-12 13-00-16](https://user-images.githubusercontent.com/32022442/62851020-60047580-bd02-11e9-8502-fdf0eaca5740.png)

**Would you like to work on the issue?**
YES

**Comment by akshatnitd** [comment]
Hey @theaayush8999 , the error was due to the server being down. Can you add error handling for that call, as we don't want users to see that page, when server doesn't work.

**Comment by theaayush8999** [comment]
Ok, thanks

**Comment by theaayush8999** [comment]
I am new to Fossaisa and Susi.ai. So it will take time for me to understand the codebase. If anyone else wants to fix this problem, go ahead.
Thanks

**Comment by harsh-jindal** [comment]
I'll fix this.
