### ISSUE TITLE
Admin Dashboard: Erroneous dates in analytics 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2829]
The dates in the analytics sections are erroneous. Please see below.

![Screenshot from 2019-08-12 14-05-06](https://user-images.githubusercontent.com/1583873/62863885-6f87bc80-bd0a-11e9-8a9a-4e79fac8647f.png)

**Comment by fragm3** [comment]
@mariobehling issue already present: https://github.com/fossasia/susi.ai/issues/2823
