### ISSUE TITLE
Use different library for table in Admin section

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi.ai#2830]
**Actual Behaviour**
Currently the current library material-table has some restrictions.

**Expected Behaviour**
Find some other library which meets our requirement.

**Would you like to work on the issue?**
Will work on this after through discussion with the mentors as we had shifted to this library from antd table 2 months back.

**Comment by fragm3** [comment]
I have looked into many libraries and packages, couldn't find anyone better than what we are currently using.

**Comment by mariobehling** [comment]
We have more data in most tables than what we can display in in one line. We need a library that can support tables with multiple lines. I can't be that there is not a solution to display multiple lines in a table row in React.js.

**Comment by fragm3** [comment]
@mariobehling there is expansion panel's present, but that again would be really subjective to use. If it was possible, would have done it
