### ISSUE TITLE
Admin: Bugs in message tab, link not working, missing email text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2838]
There are bugs in the message tab at https://susi.ai/admin/messages
1. "View" pop up should show two sections
  * on top "On Screen Message"
  * below "Email Message"
    * Also change "Subject" to "Email Subject" for better understanding
![Screenshot from 2019-08-13 02-15-18](https://user-images.githubusercontent.com/1583873/62906766-5d406980-bd70-11e9-989d-1c17336989cb.png)
2. Password Change Email Text is missing in the table.
3. On screen message is missing for "Modify Skill"
4. Modify Skill "View" link is not working
![Screenshot from 2019-08-13 02-09-58](https://user-images.githubusercontent.com/1583873/62906644-e6a36c00-bd6f-11e9-9863-70ed64f913ba.png)
5. View Password and Password Reset show the same email message
![Screenshot from 2019-08-13 02-26-37](https://user-images.githubusercontent.com/1583873/62907079-e015f400-bd71-11e9-9852-ecb8855c4986.png)
6. "Resend Account Verification Link" and "Sign Up" show the same email message
![Screenshot from 2019-08-13 02-26-05](https://user-images.githubusercontent.com/1583873/62907108-fa4fd200-bd71-11e9-96b4-a0bb6c2e1c68.png)

**Comment by fragm3** [comment]
@mariobehling confused in point#1, two section as in, do you want the content to be divided into 2 sections? Please elaborate point 1

**Comment by mariobehling** [comment]
Current implementation is confusing. You wrote "message details".
Show
1. Everything about "On screen messages"
2. Show "Message Details" -> Email Message

Dont mix things.

**Comment by fragm3** [comment]
Okay, got it
