### ISSUE TITLE
User Settings: Password area shows "Captcha" error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2839]
There should not be a catpcha error on the password settings page.

![Screenshot from 2019-08-13 02-39-16](https://user-images.githubusercontent.com/1583873/62907466-a5ad5680-bd73-11e9-9ed8-c78798fff135.png)

**Comment by fragm3** [comment]
@mariobehling it is fixed now, https://github.com/fossasia/susi.ai/pull/2837
