### ISSUE TITLE
Chat box: Videos don't show up fully

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#2840]
Clicking on "Play Shakira" on the top slider show the videos mostly hidden if there are previous interactions. Expected: It should show the video screen in its entirety.
![Screenshot from 2019-07-29 10-10-27](https://user-images.githubusercontent.com/1583873/62032257-89dd7880-b1e9-11e9-9a9a-de42d79d4664.png)

**Comment by samagragupta** [comment]
@mariobehling Will do it.
