### ISSUE TITLE
Speech Output bug

### ISSUE THREAD

**Issue by chauhanparth210** [fossasia/susi.ai#2849]
**Actual Behaviour**

- When you change Settings->Speech->Speech Output Language to "Google UK English Female (en-GB)"  it displays  "Google UK English Male (en-GB)" but the sound played as  demonstration it's **female voice**

- When you change Settings->Speech->Speech Output Language to "Google UK English Male (en-GB)"  it displays  "Google UK English Male (en-GB)" but the sound played as  demonstration it's **female voice**

- In both of the case it plays only  "Google UK English Female (en-GB)" voice and shows that   both the option for male and female selected on dropdown

**Expected Behaviour**
For both individual case, it should play individual voice respectively and should display the current selected voice language on dropdown.

**Screenshots of the issue**
![Screenshot (25)](https://user-images.githubusercontent.com/35137224/63020079-ba483680-beba-11e9-9ff0-74c061a0755e.png)

**Would you like to work on the issue?**
Yes

**Comment by kpulkit29** [comment]
@chauhanparth210 Are you working on it?

**Comment by chauhanparth210** [comment]
No

**Comment by kpulkit29** [comment]
I guess for any change it plays the same sound
