### ISSUE TITLE
Fix select language field

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi.ai#2854]
**Actual Behaviour**

Length is not fixed and dropdown icon

**Expected Behaviour**

Fix the length and make proper dropdown icon.

**Screenshots of the issue**

![Capture](https://user-images.githubusercontent.com/32234926/63073285-cc22eb80-bf45-11e9-8b9d-c1805fd68722.JPG)

**Would you like to work on the issue?**

Yes

**Comment by Dilshaad21** [comment]
@samagragupta can I take this issue?
