### ISSUE TITLE
Wrong Message in My Analytics

### ISSUE THREAD

**Issue by theaayush8999** [fossasia/susi.ai#2857]
**Actual Behaviour** 
"Your skill has not been used, make sure to improve your skill to attract more users." message is shown to users who haven't created any skills yet.

**Expected Behaviour**
 should show "You haven't created any skill yet. [Create skill Button]"

**Steps to reproduce it**
1. Create a new account 
2. Go to My Analytics Section in Dashboard.

**Screenshots of the issue**
 
![Screenshot from 2019-08-15 19-42-06](https://user-images.githubusercontent.com/32022442/63101479-bbe72c80-bf96-11e9-9ad3-bd439dbdef74.png)

**Would you like to work on the issue?**
Yes

**Comment by JoyLubega** [comment]
@theaayush8999 are you still working on this? can I pick it up?

**Comment by kpulkit29** [comment]
Since the issue creator is not replying I am starting to work on it.
