### ISSUE TITLE
Fix devices tab table scroll

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi.ai#2860]
**Actual Behaviour**

Currently, devices tab in admin has a scroll

**Expected Behaviour**

Remove scroll

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
This is not solved yet. Rather than hiding information, please also implement this with line breaks.

![Screenshot from 2019-08-16 05-34-12](https://user-images.githubusercontent.com/1583873/63141855-9f271500-bfe7-11e9-8ea9-58486dad1e99.png)

**Comment by samagragupta** [comment]
@fragm3 @mariobehling It is still not fixed.
![Capture](https://user-images.githubusercontent.com/32234926/63213440-01882e80-c12a-11e9-8daf-aa19332e40fd.JPG)

**Comment by fragm3** [comment]
Feel free to take it up
