### ISSUE TITLE
Empty Screen - VoicePlayer error

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi.ai#2881]
This error can only be reproduced in Chrome and it appears randomly.
It can be temporarily fixed by restarting of Chrome, but after some time it re-appears.

The error appears then in two situations:
- click on the chat symbol in the bottom right, or
- if the chat window is already open, input one line

The effect is, that the whole browser window goes blank, filled white.

Using the chrome javascript console the error can be discovered:

`VoicePlayer.js:32 Uncaught (in promise) TypeError: Failed to set the 'rate' property on 'SpeechSynthesisUtterance': The provided float value is non-finite.`

<img width="1726" alt="Bildschirmfoto 2019-08-26 um 10 44 11" src="https://user-images.githubusercontent.com/238730/63677997-850ee300-c7ee-11e9-93d1-e533cbf44ea8.png">

<img width="1726" alt="Bildschirmfoto 2019-08-26 um 10 44 25" src="https://user-images.githubusercontent.com/238730/63678010-8b04c400-c7ee-11e9-95f6-e05140a0a0a4.png">

**Comment by Orbiter** [comment]
priority high because this is a showstopper!

**Comment by chauhanparth210** [comment]
Sir, I got the same error for "PITCH"(Which already reported to issue) because of  settings->Speech->Speech Output Rate  is set to lowest value and you have to set it to some value and save it and for "PITCH" the server is not able to save  the value of "PITCH".
