### ISSUE TITLE
Last 90 Days: no result - Uncaught (in promise) 

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi.ai#2886]
- open susi.ai
- log in
- click on "Last 90 Days"

https://susi.ai/?creation_date&duration=90

-> no results a re shown. The following error appears in debugger:

![bug1](https://user-images.githubusercontent.com/238730/63783070-a7872600-c8ec-11e9-957d-e7957d3227cc.png)

**Comment by fragm3** [comment]
@Orbiter unable to reproduce the bug.

**Comment by harsh-jindal** [comment]
@Orbiter Unable to reproduce bug. Can be fixed if reproduced by someone later.

**Comment by akshatnitd** [comment]
Can't reproduce this issue. Closing it.
