### ISSUE TITLE
Fix overflow issue in table in Add your website in Bot Builder

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/susi.ai#2894]
**Actual Behaviour**
Currently the table overflows the dimension.

**Expected Behaviour**
Fix it.

**Screenshots of the issue**
![Screenshot 2019-08-29 at 8 50 38 AM](https://user-images.githubusercontent.com/31013104/63907764-42414b00-ca3a-11e9-9893-e8ffdb63eb24.png)

**Would you like to work on the issue?**
Yes

**Comment by Tanish0019** [comment]
Hello, is this issue fixed? if not can I work on it?

**Comment by harsh-jindal** [comment]
@Tanish0019 you can go ahead with it.
