### ISSUE TITLE
Scroll button appears when content does not overflow

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#2900]
**Actual Behaviour**

Scroll button appears even when content in it does not overflow.

**Expected Behaviour**

Scroll button should not appear in that case.

**Screenshots of the issue**

![Screenshot from 2019-09-04 18-35-1121](https://user-images.githubusercontent.com/45489945/64258820-899d6f00-cf45-11e9-8536-ed25f49245ee.png)

**Would you like to work on the issue?**

Yes

**Comment by skarthikeyan96** [comment]
@Dilshaad21 is the issue already fixed?
