### ISSUE TITLE
The circled part in the language selector is not working properly.

### ISSUE THREAD

**Issue by tanujvyas10** [fossasia/susi.ai#2902]
**Actual Behaviour**

The circle part of the language selector is not working properly.

**Expected Behaviour**

Whole language selector button should work properly as a whole unit
**Steps to reproduce it**

**Screenshots of the issue**
![1](https://user-images.githubusercontent.com/48439116/64486771-1d758080-d24f-11e9-95ee-ce3613cb5a00.jpg)

**Would you like to work on the issue?**

yes

**Comment by garvitkhandelwal** [comment]
@tanujvyas10  Still working on this?

**Comment by garvitkhandelwal** [comment]
@AakashMallik Can I take this issue since this user is not responding?

**Comment by tanujvyas10** [comment]
@AakashMallik sir working on it.

**Comment by tanujvyas10** [comment]
@AakashMallik  sure go ahead
