### ISSUE TITLE
Search did not match position

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#2909]
**Actual Behaviour**

The "Search did not match any" appears in a odd manner aligned at the top left corner of the page.

**Expected Behaviour**

The whole search did not match text should come at the centre of the page.

**Screenshots of the issue**

![xccc](https://user-images.githubusercontent.com/45489945/64972702-5e147000-d8c7-11e9-8f8a-b363cefd7f63.png)

**Would you like to work on the issue?**

Yes

**Comment by garvitkhandelwal** [comment]
@Dilshaad21  Are you working on this?

**Comment by JoyLubega** [comment]
is anyone working on this, I want to pick it up

**Comment by Dilshaad21** [comment]
@JoyLubega I think @garvitkhandelwal asked first for this issue. If he is not working on it then you can surely go ahead with it.

**Comment by garvitkhandelwal** [comment]
@Dilshaad21  @JoyLubega  I'll take this issue. Thanks

**Comment by kpulkit29** [comment]
@Dilshaad21 This issue is already solved  you might close this.
