### ISSUE TITLE
SUSI chatbot

### ISSUE THREAD

**Issue by darkthunder007** [fossasia/susi.ai#2912]
[**Actual Behaviour**

The ouput should be related to the users words

<img width="864" alt="df" src="https://user-images.githubusercontent.com/53977169/65376294-c5616400-dcbb-11e9-8eed-d6e86ef683af.png">

**Expected Behaviour**

To be able to give better answers to single words like why,what.

**Steps to reproduce it**

Type 'what','how' SUSI will give unrelated answers.

**Would you like to work on the issue?**

Yes

**Comment by garvitkhandelwal** [comment]
I guess for these things you need to open a issue in susi server repository.

**Comment by darkthunder007** [comment]
I put the issue in the susi server repository issue #1401

**Comment by mariobehling** [comment]
As this is a server issue I am closing this here.
