### ISSUE TITLE
Center Align text when there are no analytics

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#2915]
**Actual Behaviour**

The text "Your skill has not been used, make sure to improve your skill to attract more users."
is algned to the left when there are no analytics.

**Expected Behaviour**

It should be center aligned.

**Steps to reproduce it**

1.Go to susi.ai
2.Go to dashboard.

**Screenshots of the issue**

![analytics](https://user-images.githubusercontent.com/45489945/65431732-907a1c00-de37-11e9-8cd3-6aac83e86706.png)

**Would you like to work on the issue?**

Yes

**Comment by vishaldhull09** [comment]
i would like to work on this issue
