### ISSUE TITLE
Default avatar not selected in settings

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#2919]
**Actual Behaviour**

Default avatar is set as avatar but not showing selected in settings/user

**Expected Behaviour**

By default "default" avatar should be shown as current avatar and selected as well. 

**Steps to reproduce it**
1.Go to settings
2.Go to account

**Screenshots of the issue**

**Actual**
![im2](https://user-images.githubusercontent.com/45489945/65608078-44f87700-dfcb-11e9-93d0-02cbdaa35569.png)

**Expected**
![im1](https://user-images.githubusercontent.com/45489945/65608104-4e81df00-dfcb-11e9-82bb-f71da5e3349e.png)

**Would you like to work on the issue?**
Yes

**Comment by shagunarora** [comment]
Sir can I solve this issue?

**Comment by Dilshaad21** [comment]
@shagunarora I am currently working on it.

**Comment by shagunarora** [comment]
ok sir but I have found a solution to it can I share it maybe if it helps.
