### ISSUE TITLE
Merge Materials Icon CSS file

### ISSUE THREAD

**Issue by realabbas** [fossasia/susi.ai#2922]
**Actual Behaviour**
I ran a test on the **susi.ai website**. I found that it is making an **extra request** for material icons CSS file which contains a very less amount of code, but still, its request is being counted

**Screenshots of the issue**

![Screenshot (1172)](https://user-images.githubusercontent.com/43527087/65787833-744be700-e177-11e9-9ea7-b10531dbd510.png)

**The score is 92%**

![Screenshot (1171)](https://user-images.githubusercontent.com/43527087/65787834-744be700-e177-11e9-9aaf-9cfd450690d5.png)

**The file has less amount of code, still, it's being counted as one request** 
Merging the CSS file with the other files will increase the **Page Speed** and **minimize the server** requests by 1.

**Would you like to work on the issue?**
Yes, I would like to work on this. 

Report: https://gtmetrix.com/reports/susi.ai/CJZZWmkK

**Comment by akshat0047** [comment]
I would like to do it.. @akshatnitd

**Comment by realabbas** [comment]
@mariobehling Claim this bug. Would like to do it

**Comment by anishagg17** [comment]
@akshatnitd it has been resolved
