### ISSUE TITLE
Errors while editing custom theme 

### ISSUE THREAD

**Issue by shagunarora** [fossasia/susi.ai#2923]
**Actual Behaviour**
In susi.ai settings -> theme ->custom theme ->edit theme
when selecting color it is working fine.  Moment after selecting color it shows errors. 

Error when setting color of chat header

![Screenshot from 2019-09-28 17-02-58](https://user-images.githubusercontent.com/35228934/65815880-76af4f00-e212-11e9-834e-a3adf8387a17.png)
here in above screenshot I am selecting color of chat header it is working fine.

![Screenshot from 2019-09-28 17-03-08](https://user-images.githubusercontent.com/35228934/65815882-76af4f00-e212-11e9-95bc-830ce70a5be7.png)
After selecting the color if I click anywhere else on website then above error occurs.  

Similarly other error occurs while setting color for different components of chat box like while changing color of background ..
![Screenshot from 2019-09-28 16-59-22](https://user-images.githubusercontent.com/35228934/65815937-40260400-e213-11e9-81f3-4574750f4b76.png)
working fine till selecting color

![Screenshot from 2019-09-28 16-58-31](https://user-images.githubusercontent.com/35228934/65815936-3f8d6d80-e213-11e9-9f83-b51729248d99.png)
Now error after clicking anywhere on website

**Expected Behaviour**

It should not show any error should work fine while selecting color.

**Would you like to work on the issue?**

Yes I would like to work on this issue

**Comment by AuraOfDivinity** [comment]
I came across this issue yesterday while trying to change the theme.  Has any progress been made with regard to this issue @shagunarora ?

**Comment by shagunarora** [comment]
@AuraOfDivinity  I have tried a bit till now but unable to make anything. I am still working on it. But if you want to take up this issue go ahead .
