### ISSUE TITLE
Chat header color not getting changed.

### ISSUE THREAD

**Issue by AuraOfDivinity** [fossasia/susi.ai#2937]
**Actual Behavior**

Header color does not change to the selected color in the custom theme color picker.

**Expected Behavior**

Header should change it's color to the selected color of the custom theme.

**Steps to reproduce it**

1. Go to setting -> Theme -> Custom Theme  -> Edit theme.
2. Select a color for the chat header. 
3. Save the changes.

**Screenshots of the issue**

![HeaderThemeNotChanging](https://user-images.githubusercontent.com/31003923/66264054-df528900-e81b-11e9-8b37-ca51ef9bff9f.gif)

**Would you like to work on the issue?**

Yes

**Comment by vishaldhull09** [comment]
can i work on this issue?

**Comment by AuraOfDivinity** [comment]
@vishaldhull09  Sure go ahead!

**Comment by Jackent2B** [comment]
I want to work on this. Should I?
