### ISSUE TITLE
Hover effect on language button

### ISSUE THREAD

**Issue by Pranshu2780** [fossasia/susi.ai#2943]
**Actual Behaviour**

On hovering text cursor is coming

**Expected Behaviour**

On hovering click cursor should come

**Screenshots of the issue**

![s](https://user-images.githubusercontent.com/47604864/66656182-1df0a500-ec5b-11e9-987f-e8a8bf8497bb.PNG)

**Would you like to work on the issue?**

Yes

**Comment by Dilshaad21** [comment]
@Pranshu2780 this issue is already covered in #2902

**Comment by mariobehling** [comment]
Closing it as a duplicate.
