### ISSUE TITLE
Fix allignment in mobile view

### ISSUE THREAD

**Issue by plxity** [fossasia/susi.ai#2946]
**Actual Behaviour**

![Screenshot from 2019-10-13 05-23-50](https://user-images.githubusercontent.com/28510494/66709062-e4628b80-ed79-11e9-80b8-c703be886559.png)

**Expected Behaviour**

Like, Dislike, share button and time should be aligned properly.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

**Comment by pcsingh** [comment]
On setting style="width: 30px;" in the div of share button or tick button it will align it self.

![issue #2946](https://user-images.githubusercontent.com/44555033/66711453-c01ea300-eda9-11e9-8702-66e67299e35d.png)
