### ISSUE TITLE
Allignment issue with scroll bar

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#2947]
**Actual Behaviour**

The vertical scroll bar comes over close button while selecting colors in custom theme.

**Expected Behaviour**

It should not come over it.

**Steps to reproduce it**

1. Go to settings
2. Go to Theme
3. Select Custom theme->Edit theme.

**Screenshots of the issue**

![newr](https://user-images.githubusercontent.com/45489945/66716314-f24ff500-ede9-11e9-97a5-69ced6396b80.png)

**Would you like to work on the issue?**

Yes

**Comment by vaibhavmathur13** [comment]
I would like to work on this

**Comment by Dilshaad21** [comment]
Sure go ahead

**Comment by snitin315** [comment]
@vaibhavmathur13  are you still working on this issue? if not, can i work on this issue?

**Comment by Shruti6814** [comment]
@snitin315  Are you still working on it? Can I work on it if you are not working on it now.

**Comment by vaibhavmathur13** [comment]
@Shruti6814 I'm already working on this issue.

**Comment by snitin315** [comment]
@Shruti6814 , @vaibhavmathur13  has already made PR for this issue. Now the discussion is moved there. He is working on the issue.
