### ISSUE TITLE
Edit feedback issue

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#2948]
**Actual Behaviour**

While editing the feedback of a skill the previous feedback does not appear in the textbox.

**Expected Behaviour**

Previous feedback must appear when a user tries to edit feedback.

**Screenshots of the issue**

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/45489945/66716538-6d1a0f80-edec-11e9-96ca-233392604a71.gif)

**Would you like to work on the issue?**
 
Yes, I would like to work on this issue

**Comment by RocktimSaikia** [comment]
can i work on it ?

**Comment by Dilshaad21** [comment]
I'm working on it currently.
