### ISSUE TITLE
Skill bug

### ISSUE THREAD

**Issue by darkthunder007** [fossasia/susi.ai#2952]
**Actual Behaviour**

When you type, 'what?', the bot responds 'Sad to hear it'.

**Expected Behaviour**

The new skill 'asking questions'  is supposed to change the bot response to ' I did not understand, please rephrase your question clearly'.

**Steps to reproduce it**

Type, 'what?'. Observe the response.
**Screenshots of the issue**

![SharedScreenshot](https://user-images.githubusercontent.com/53977169/66762899-77a7d800-eec4-11e9-8b7a-d4ffdb1969a8.jpg)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Issues like that need to be resolved by fixing skills and the server. This repo is just for the front-end. Therefore closing it.
