### ISSUE TITLE
No error message displayed when try to submit an empty feedback form.

### ISSUE THREAD

**Issue by plxity** [fossasia/susi.ai#2960]
**Actual Behaviour**

No error message is displayed when you try to submit an empty feedback form for a skill while editing.

**Expected Behaviour**

It should display an error message.

**Steps to reproduce it**

For reference visit https://susi.ai/Communication/EnglishAIMLL/en and add feedback & then edit your comment. While submitting an empty form, no error message will be displayed. 

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes, I would like to work on this.

**Comment by Dilshaad21** [comment]
@plxity can I take this issue?

**Comment by plxity** [comment]
@Dilshaad21 I am working on it.

**Comment by Dishebh** [comment]
@plxity can i take this issue? Also, the link mentioned description doesn't load up, can you pls update it as well?
