### ISSUE TITLE
Placeholders in dark mode not visible

### ISSUE THREAD

**Issue by kpulkit29** [fossasia/susi.ai#2978]
**Actual Behaviour**

When changed to dark mode placeholders in settings are not visible

**Expected Behaviour**

It should be contrasting to the colors of dark theme

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

![Screenshot 2019-10-21 at 10 29 22 PM](https://user-images.githubusercontent.com/20151526/67226436-8822fa00-f452-11e9-9cf9-a15d7bb5e7c4.png)

**Would you like to work on the issue?**

Yes

**Comment by paras151** [comment]
Has this issue been solved?
If not can i work on thsis?

**Comment by kpulkit29** [comment]
@paras151 This issue would be solved when dark mode is integrated with createMUITheme. So it is kind of a duplicate issue. I would close this issue
