### ISSUE TITLE
Sorting skill by Name(A-Z) is sorting in (Z-A) 

### ISSUE THREAD

**Issue by aman29271** [fossasia/susi.ai#3008]
**Actual Behaviour**

Sorting Susi skill by Name(A-Z) is instead sorting in (Z-A)

**Expected Behaviour**

It should sort in Name(A-Z) order.

**Steps to reproduce it**

Go to https://susi.ai/category/All 
And Select sort by to Name(A-Z).

**Screenshots of the issue**

![Screenshot from 2019-10-30 16-05-47](https://user-images.githubusercontent.com/30979779/67850981-7bc42e80-fb2f-11e9-9ff9-5ab9183f68eb.png)

**Would you like to work on the issue?**

Yes

**Comment by plxity** [comment]
@aman29271 are you working on this? or can I take this up?

**Comment by plxity** [comment]
@aman29271 I am taking this up.

**Comment by plxity** [comment]
@aman29271 That is not an issue. The arrow adjacent to dropdown shows whether it's descending or
ascending.
@akshatnitd We shall close this up.

**Comment by akshatnitd** [comment]
@pipix51 The issue is valid. The default behaviour when we select `Name(A-Z)` should be ascending.

**Comment by kpulkit29** [comment]
@aman29271  are you still working on it?

**Comment by aman29271** [comment]
@kpulkit29 yes

**Comment by Dishebh** [comment]
@aman29271 can I take the issue pls?

**Comment by aman29271** [comment]
@Dishebh go ahead

**Comment by NitinBhasneria** [comment]
@aman29271 Looks like @Dishebh has taken many issues and not working so can I take this issue?
@Dishebh If you are working then please respond...

**Comment by Dishebh** [comment]
@NitinBhasneria working on it.

**Comment by anishagg17** [comment]
@aman29271 can I take the issue pls?
@Dishebh It's more than 4 days no effort has been shown by you

**Comment by Dishebh** [comment]
Sure, go ahead.

**Comment by ShubhamChaudharyy** [comment]
@aman29271 if u aren't working on this issue can i take up?

**Comment by anishagg17** [comment]
@ShubhamChaudharyy i am working on it

**Comment by NimishGopal** [comment]
@anishagg17 Are you working on it? If not, please give me a go-ahead.
