### ISSUE TITLE
Raise error when empty feedback form saved in edit feedback

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3014]
**Actual Behaviour**

When empty feedback is saved in `editfeedback` no error is raised 

**Expected Behaviour**

Error should be raised in that case.

**Screenshots of the issue**

![cd](https://user-images.githubusercontent.com/45489945/68067103-51a98100-fd68-11e9-8a2a-c2a17267d427.png)

**Would you like to work on the issue?**

Yes

**Comment by plxity** [comment]
@Dilshaad21 Duplicate issue #2960 
and I have already raised a PR #2956. Please check.

**Comment by Dilshaad21** [comment]
Ok @plxity closing pr...
