### ISSUE TITLE
Network call for every keydown(Search skill)

### ISSUE THREAD

**Issue by kpulkit29** [fossasia/susi.ai#3015]
**Actual Behaviour**
Currently for every keydown there is a request made to the server api when the user searches a skill

**Expected Behaviour**

There should be a debounce here as sending network call on every keydown effects the performance

**Steps to reproduce it**

- Open the homepage
- Type something in the search skill input box
- Open dev tools and notice the calls being send when you type

**Would you like to work on the issue?**
Yes

**Comment by plxity** [comment]
@kpulkit29 There is already a debounce of 100ms and that's fine.

**Comment by kpulkit29** [comment]
Closing this issue as there is a debounce already.
