### ISSUE TITLE
Remove unnecessary horizontal scroll in Countrywise usage  

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3025]
**Actual Behaviour**

An unnecessary horizontal scroll is there in the country wise usage of susi skill.

**Expected Behaviour**

It should not overflow horizontally.

**Screenshots of the issue**

![fvd](https://user-images.githubusercontent.com/45489945/68325295-18b63700-00ef-11ea-8450-965a837b923b.png)

**Would you like to work on the issue?**
Open for first time contributors

**Comment by plxity** [comment]
@Dilshaad21 This PR has already raised for this. #3006.
You may close this issue.

**Comment by Dilshaad21** [comment]
Ok @plxity
