### ISSUE TITLE
Show map along with the link for map type response

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi.ai#3026]
**Actual Behaviour**
- Currently only the link is being shown for the map.

**Expected Behaviour**
- Show map along with the link as was shown previously.

**Steps to reproduce it**
Type `Where is Singapore?` into the chat box.

**Screenshots of the issue**
<img width="378" alt="Screenshot 2019-11-07 at 12 00 03 PM" src="https://user-images.githubusercontent.com/12656846/68365325-54381c00-0156-11ea-8c3a-faa8e18d6635.png">

**Would you like to work on the issue?**
Anyone is free to pick this task.

**Comment by AuraOfDivinity** [comment]
I'll work on this issue! @akshatnitd
