### ISSUE TITLE
Not able to chat

### ISSUE THREAD

**Issue by chauhanparth210** [fossasia/susi.ai#3031]
**Actual Behaviour**
App is crash while chatting.

**Expected Behaviour**
It should not crash while chatting.

**Screenshots of the issue**
![Screenshot (58)](https://user-images.githubusercontent.com/35137224/68525019-60a5ab80-02f3-11ea-8e2f-9f2d32913dd5.png)

**Would you like to work on the issue?**
Yes

**Comment by AuraOfDivinity** [comment]
@chauhanparth210 This issue was fixed here https://github.com/fossasia/susi.ai/commit/4c14c8ce2f0c7670ea7d63fea5c26ef8c6041499 .

**Comment by chauhanparth210** [comment]
@AuraOfDivinity   thank you and I am closing this issue.
