### ISSUE TITLE
Footer not properly aligned on mobile

### ISSUE THREAD

**Issue by kpulkit29** [fossasia/susi.ai#3033]
**Actual Behaviour**

The Footer links are not properly aligned on mobile

**Expected Behaviour**

The links should be aligned in columns

**Screenshots of the issue**
![Screenshot 2019-11-09 at 7 47 07 PM](https://user-images.githubusercontent.com/20151526/68529965-0411b300-032a-11ea-8afa-ca353646a526.png)

**Would you like to work on the issue?**

Yes

**Comment by poojagl85** [comment]
Can I work on this issue?

**Comment by kpulkit29** [comment]
I am still working on it

**Comment by poojagl85** [comment]
![opensource](https://user-images.githubusercontent.com/53204850/68541274-5d79f080-03c3-11ea-9376-4187c52a4096.png)
I tried to resolve it.

**Comment by poojagl85** [comment]
I
![footer](https://user-images.githubusercontent.com/53204850/68541471-edb93500-03c5-11ea-9236-e8e498bba0dc.png)
 tried it.

**Comment by kpulkit29** [comment]
@poojagl85  I will make a PR later. You can definetely start working on it if I am not.
