### ISSUE TITLE
Search bar close button not appearing in small mobile views.

### ISSUE THREAD

**Issue by AuraOfDivinity** [fossasia/susi.ai#3048]
**Actual Behaviour**

The search bar close button is not appearing in small mobile views. (Sizes < 350)

**Screenshots of the issue**

![1](https://user-images.githubusercontent.com/31003923/68764156-26fcd980-0640-11ea-8f13-7e56b1105f29.png)

**Would you like to work on the issue?**

Yes

**Comment by kpulkit29** [comment]
@AuraOfDivinity  are you still working on it.

**Comment by AuraOfDivinity** [comment]
@kpulkit29  Feel free to start working on it!

**Comment by meliodas113** [comment]
Hi. Can I work on this issue?

**Comment by kpulkit29** [comment]
Go ahead

**Comment by AuraOfDivinity** [comment]
@meliodas113  Sure!

**Comment by meliodas113** [comment]
Thank you.
