### ISSUE TITLE
The profile icon should be placed at extreme left instead of center.

### ISSUE THREAD

**Issue by poojagl85** [fossasia/susi.ai#3056]
**Actual Behaviour**

The profile icon should be placed at extreme left instead of center once the user is logged in. It looks weird in center.

**Expected Behaviour**

The profile icon should be placed at extreme right.

**Screenshots of the issue**

![Screenshot_20191115-075235_Chrome](https://user-images.githubusercontent.com/53204850/68916921-1490b600-078e-11ea-9510-c821b2bc1801.jpg)

**Would you like to work on the issue?**

Yes

**Comment by Dishebh** [comment]
@poojagl85 @akshatnitd if it is up for grabs, can I take it?

**Comment by poojagl85** [comment]
@Dishebh you can take this.

**Comment by NitinBhasneria** [comment]
@poojagl85 Is @Dishebh  taking up for this issue or should I contribute to this, please?

**Comment by Dishebh** [comment]
@NitinBhasneria you may take up the issue.

**Comment by NitinBhasneria** [comment]
Ok I am taking this issue

**Comment by altaha-ansari** [comment]
@poojagl85 Is this issue available for me to work on?

**Comment by NitinBhasneria** [comment]
Actually I am not confirmed if this issue is valid. If you know then you can go ahead.

**Comment by akshatnitd** [comment]
@NitinBhasneria @altaha-ansari Yes, it is a valid issue. Also, can you use `+` icon in-place of `Create` in mobile view?

**Comment by NitinBhasneria** [comment]
Ok so I will be working on it. And wiol certainly complete it by a day or two.

**Comment by altaha-ansari** [comment]
@NitinBhasneria ohk but if you won't later, then do notify.

**Comment by NitinBhasneria** [comment]
Ok then you can work on this issue I am leaving it.

**Comment by mariobehling** [comment]
No need.
