### ISSUE TITLE
Filter by avg. customer rating not available in mobile view

### ISSUE THREAD

**Issue by AuraOfDivinity** [fossasia/susi.ai#3057]
**Actual Behaviour**

Currently filtering by the avg. user rating is not available in mobile views. 

**Expected Behaviour**

All forms of filtering available in the web view must be available in the mobile view.

**Screenshots of the issue**

![2](https://user-images.githubusercontent.com/31003923/68922535-e321e580-07a1-11ea-9850-cdc6ff2898ab.png)

**Would you like to work on the issue?**

Yes

**Comment by kpulkit29** [comment]
@AuraOfDivinity are u still working on this?

**Comment by akshatnitd** [comment]
We probably would like to build it using some other way. Maybe, show all the filters on a drawer.

**Comment by anishagg17** [comment]
> We probably would like to build it using some other way. Maybe, show all the filters on a drawer.

Okay sir , I am working on it and would soon update the fix
