### ISSUE TITLE
Next and Previous buttons of the blog not displayed.

### ISSUE THREAD

**Issue by AuraOfDivinity** [fossasia/susi.ai#3059]
**Actual Behaviour**

The Next and previous buttons (implemented in the index.js) of the blog aren't displayed as expected and because of this the users are unable to navigate/view older blog posts as expected.  

**Expected Behaviour**

Users should be able to view all the blog posts that have been published.

**Screenshots of the issue**

(Notice no Previous or Next Fab buttons in the bottom)
![NoButtons](https://user-images.githubusercontent.com/31003923/68942458-a4565480-07ce-11ea-952e-e78cb84c5647.png)

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Already fixed. Closing it.
