### ISSUE TITLE
Pagination needed only when it exceeds a certain limit 

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3070]
**Actual Behaviour**

Currently, pagination appears unnecessarily even though feedbacks can be displayed in that single page.

**Expected Behaviour**

It should appear only when the total feedbacks exceeds the limit to fit within a page. 

**Screenshots of the issue**

![cdcd](https://user-images.githubusercontent.com/45489945/69006116-c081ff00-0950-11ea-97de-788e6c20f2a0.png)

**Would you like to work on the issue?**
Yes

**Comment by kpulkit29** [comment]
But the button are disabled, isn't it self-explanatory

**Comment by kpulkit29** [comment]
@Dilshaad21  Are you still working on this.

**Comment by Dilshaad21** [comment]
No, I'm currently not. You can go ahead :rocket:
