### ISSUE TITLE
Many images on the /blog page are only half visible in mobile view. 

### ISSUE THREAD

**Issue by poojagl85** [fossasia/susi.ai#3073]
**Actual Behaviour**

Many images on the [https://susi.ai/blog] page are only half visible in mobile view.

**Expected Behaviour**

Images should be completely visible in mobile view.

**Screenshots of the issue**
Only some screenshots I have shown but their are many. Need to make the images mobile responsive.
![image1](https://user-images.githubusercontent.com/53204850/69008811-b114ad00-0974-11ea-9b12-0780d01cac52.png)

![image2](https://user-images.githubusercontent.com/53204850/69008813-b540ca80-0974-11ea-9542-31de07f9f842.png)

![image3](https://user-images.githubusercontent.com/53204850/69008815-ba9e1500-0974-11ea-80cf-0cc2a1c321d3.png)

![image4](https://user-images.githubusercontent.com/53204850/69008816-bd990580-0974-11ea-9aa2-9d75034761db.png)

**Would you like to work on the issue?**
Yes

**Comment by Dishebh** [comment]
@poojagl85 can I pls take the issue?

**Comment by poojagl85** [comment]
I have already done the PR

**Comment by poojagl85** [comment]
@akshatnitd please review
