### ISSUE TITLE
icons on chat window should have a title

### ISSUE THREAD

**Issue by himanshu010** [fossasia/susi.ai#3079]
**Actual Behaviour**

The icons on the chat window does not have a title and they doesn't show title on hovering
**Expected Behaviour**

screenshot:
![Screenshot (61)](https://user-images.githubusercontent.com/43860289/69239003-42775f80-0bbf-11ea-90a7-7bf8368c9ab1.png)

**Steps to reproduce it**

1. Go to https://susi.ai/
2. Click on chat button
3. Hover on search or fullscreen icon

**Would you like to work on the issue?**

Yes I will work on this issue

**Comment by paras151** [comment]
I am new to opensource , I would like to take up this issue

**Comment by himanshu010** [comment]
> 
> 
> I am new to opensource and want to contribute, I would like to take up this issue

@paras151 okk you can take it

**Comment by kushaggarwal** [comment]
I am new to open source and want to contribute 
I would like to resolve this issue if unsolved 
please help thanks

**Comment by paras151** [comment]
> I am new to open source and want to contribute
> I would like to resolve this issue if unsolved
> please help thanks

Well Kush, I've already made a pr regarding this issue,I am sure you can find many other isuues.

**Comment by kushaggarwal** [comment]
Okay Thanks

**Comment by himanshu010** [comment]
@paras151 Nice work
