### ISSUE TITLE
No warning messages when empty bot_name field is given

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3081]
**Actual Behaviour**

Currently in `Add a new skill to your bot` page new bot gets created without a bot_name.
 
**Expected Behaviour**

A `warning` message must be given when empty fields are getting submitted.

**Screenshots of the issue**

![final_5dd581766c42b80013bfc1f0_91560](https://user-images.githubusercontent.com/45489945/69265595-84b89500-0bef-11ea-9f16-9513363eb0b8.gif)

**Would you like to work on the issue?**

Yes

**Comment by kpulkit29** [comment]
@Dilshaad21  Are you still working on this?
