### ISSUE TITLE
Unusual categories shown which don't have any skill related to them

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3082]
**Actual Behaviour**

![Hnet-image](https://user-images.githubusercontent.com/43617894/69316495-f67bf780-0c5e-11ea-84df-5001f6b14e8f.gif)

Categories which don't match any skills are shown
 

**Expected Behaviour**

Categories with no Skills should not be displayed

**Steps to reproduce it**

click on categories in sidebar

**Would you like to work on the issue?**
Yes

**Comment by iharshit009** [comment]
It's also working fine @anishagg17, I think there may be some dependencies issue in you code structure.

**Comment by Dishebh** [comment]
@anishagg17 if it is up for grabs, can I take it?

**Comment by anishagg17** [comment]
yep bro you may work on it
