### ISSUE TITLE
Refine by rating isn't working

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3083]
**Actual Behaviour**

![Hnet-image](https://user-images.githubusercontent.com/43617894/69316992-f8928600-0c5f-11ea-8db1-414e9534a30f.gif)

Refine by Avg. Customer Review feature of sidebar isn't showing any skill

**Expected Behaviour**

skills with relevant ratings should be shown

**Steps to reproduce it**

select any filter underneath  Avg. Customer Review section

**Would you like to work on the issue?**

YES

**Comment by iharshit009** [comment]
It's working fine here @anishagg17
