### ISSUE TITLE
Not landing into 1st page of search results

### ISSUE THREAD

**Issue by iharshit009** [fossasia/susi.ai#3087]
**Actual Behaviour**

The pages remain the same even if the search results are varied.

**Expected Behaviour**

On varying the search results, it should land on page 1 of search results.

**Steps to reproduce it**
Go to particular rating results and change the page, after that try to change the rating and check out the result page. 

**Screenshots of the issue**

![Screencast-from-Saturday-23-November-2019-12_00_38-IST](https://user-images.githubusercontent.com/44135316/69451826-50c3a800-0d86-11ea-9aaf-af7152650927.gif)

**Would you like to work on the issue?**

Yes

**Comment by kpulkit29** [comment]
@iharshit009  I would like to work on it.

**Comment by simranaggarwal1999** [comment]
Can I work on this issue?

**Comment by simranaggarwal1999** [comment]
@iharshit009  I have resolved the issue. Kindly review my pull request.

**Comment by simranaggarwal1999** [comment]
@iharshit009 I have resolved the issue. Kindly review my pull request.
