### ISSUE TITLE
alignment of buttons is not proper in mobile

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/susi.ai#3088]
**to reproduce**
go to "http://localhost:3000/about" scroll down
**Screenshots of the issue**
![Screenshot from 2019-11-23 08-41-50](https://user-images.githubusercontent.com/56407566/69472239-7e800f80-0dcd-11ea-8df0-c225e95f1312.png)

**Would you like to work on the issue?**
yes

**Comment by Dishebh** [comment]
@maze-runnar if it is up for grabs, can I take it?

**Comment by maze-runnar** [comment]
go ahead

**Comment by anishagg17** [comment]
@Dishebh Are you still working on it i will like to work on it

**Comment by kpulkit29** [comment]
@anishagg17 I would like to work on it.

**Comment by anishagg17** [comment]
> @anishagg17 I would like to work on it.

okay @kpulkit29
