### ISSUE TITLE
creator of skill should not be able to rate his own skill

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/susi.ai#3089]
creator of skill should not be able to rate his own skill

![Screenshot from 2019-11-23 08-55-28](https://user-images.githubusercontent.com/56407566/69472427-43cba680-0dd0-11ea-9250-9176dc5cc613.png)

**Would you like to work on the issue?**
yes

**Comment by Pep-DEV101** [comment]
May i work on it

**Comment by paras151** [comment]
I need help in getting the the username of the logged in user using his email or vice-versa.Is there any api which i can use ? Please help/

**Comment by anishagg17** [comment]
I am taking this issue @maze-runnar

**Comment by anishagg17** [comment]
@maze-runnar I am working on this issue
