### ISSUE TITLE
Improper alignment of message when "no skill is found"

### ISSUE THREAD

**Issue by paras151** [fossasia/susi.ai#3093]
**Actual Behaviour**

When a user searches for a skill and the skill with the name searched is not found then following message is displayed.

![Screenshot (8)](https://user-images.githubusercontent.com/47773353/69662380-479a4a00-10aa-11ea-8d79-e67e9f306f7c.png)

We can see that the alignment of the 2 bulletted points is not correct.

**Expected Behaviour**

The 2 bulletted points should be aligned properly under the heading like this:

![Screenshot (7)](https://user-images.githubusercontent.com/47773353/69662508-803a2380-10aa-11ea-95c2-f9a99a45f99a.png)

**Steps to reproduce it**

The problem is due to the inheritance property of the 'text-align' property in CSS.
The sub-elements i.e. the bullet points are also inheriting the text-align:center property and are being displayed in center according to the user's window

**Screenshots of the issue**

Added above for better understanding

**Would you like to work on the issue?**

Yes, would definately like to work on this issue

**Comment by ABHIJITBURMAN** [comment]
@paras151 Yes, would definately like to work on this issue.

**Comment by paras151** [comment]
> @paras151 Yes, would definately like to work on this issue.

Well, I've already made a pull request request regarding this issue

**Comment by paras151** [comment]
Can anyone please review and comment if this is a valid issue or not @AuraOfDivinity @kpulkit29

**Comment by kpulkit29** [comment]
@paras151 The bullet points in the no skill found message are not aligned properly so I believe you can work on it.

**Comment by paras151** [comment]
> @paras151 The bullet points in the no skill found message are not aligned properly so I believe you can work on it.

I've already aligned the bullet points as you can see in the screenshot under 'Expected Behaviour'.

**Comment by Dishebh** [comment]
@paras151 can i work on the issue?

**Comment by anishagg17** [comment]
@paras151 can i work on the issue?

**Comment by anishagg17** [comment]
@paras151 i want to work on the issue?
