### ISSUE TITLE
Buttons are overflowing out of div in mobile-view

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/susi.ai#3095]
Steps to reproduce :
 Go to : https://susi.ai/botWizard 
Switch to mobile view And see error .
![Screenshot from 2019-11-28 22-42-28](https://user-images.githubusercontent.com/56407566/69824020-a5589e80-1230-11ea-8145-5e5104585d7d.png)

**Would you like to work on the issue?**

yes

**Comment by kushaggarwal** [comment]
Hey is this issue still open

**Comment by maze-runnar** [comment]
@kushaggarwal  i am on it  .
