### ISSUE TITLE
Fix the Sidebar 

### ISSUE THREAD

**Issue by rajat2502** [fossasia/susi.ai#3096]
**Actual Behaviour**
The sidebar should be fixed as when the main content of the page is large then to navigate using sidebar the user has to scroll to the top and then find the respective link.

**Expected Behaviour**
The sidebar should be fixed and made scrollable.

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/42200276/69918591-ffa86800-1499-11ea-8758-2a3f80accb7f.png)

**Would you like to work on the issue?**
Yes

I am new to this project so if you can tell me the files to work then I can work on this.

**Comment by dmahajan980** [comment]
I would like to work on this issue.
