### ISSUE TITLE
Sidebar and Navbar alignment and scaling issues

### ISSUE THREAD

**Issue by milekag01** [fossasia/susi.ai#3099]
**Actual Behaviour**

Content of sidebar shifts at the last when we try to see it on mobile and does not show the subheadings of the content in the sidebar. Also, the user has to swipe all the way down to see the sidebar content. 
Also, Navbar is not scaling properly while using it on a mobile phone. Also, once you focus on the SUSI AI logo in mobile and then unfocus, you can see that the SUSI AI logo is gone even if you switch to fullscreen(desktop screen size) unless you toggle the sidebar.

![susi1](https://user-images.githubusercontent.com/34967908/70197970-79a74e00-1733-11ea-9a09-859b5ec8d8f8.png)
![susi2](https://user-images.githubusercontent.com/34967908/70197969-79a74e00-1733-11ea-8d52-837b6841fd36.png)
![susi3](https://user-images.githubusercontent.com/34967908/70197968-790eb780-1733-11ea-9284-3c06648fc1a0.png)
![susi5](https://user-images.githubusercontent.com/34967908/70197967-790eb780-1733-11ea-9fa4-659e06b1c7b1.png)

**Expected Behaviour**

If we can use a toggle sidebar we can resolve this issue easily. Also, as a user, I would like to see the sidebar content on the top instead of what is currently happening. So having an icon up on the top while using the web app on mobile will solve this issue. As for the navbar, there should be a proper dropdown to show all the links and search bar.

**Steps to reproduce it**

Open https://susi.ai/dashboard in your mobile or in the dev tools, use toggle device toolbar and reduce the width of the screen.

**Would you like to work on the issue?**

Yes.

**Comment by milekag01** [comment]
@mariobehling Is this a valid issue?

**Comment by akshatnitd** [comment]
This issue is no more valid.
