### ISSUE TITLE
Skills Page: Delete Button - Don't show "More Examples"  or "Less"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#3100]
The skills pages show a button "More Examples" or "Less". Please only show all examples. Don't show a button at all.

![Screenshot from 2019-12-08 01-56-57](https://user-images.githubusercontent.com/1583873/70382539-354bc600-195e-11ea-9309-605e4426d0b9.png)

**Comment by paras151** [comment]
I'd like to take up on the issue

**Comment by paras151** [comment]
I wanted to ask that is there a problem if , my branch that i propose to merge is 1 commit ahead which is the required commit and 3 commits behind fossasia:master.
