### ISSUE TITLE
Edit Skill heading not showing up on Edit Skill Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#3103]
The Create Skill page has a heading "Create Skill". The edit skill page is identical except for "Create Skill" it should show "Edit Skill". Please get the heading back.

![Screenshot from 2019-12-11 23-03-22](https://user-images.githubusercontent.com/1583873/70686657-4b82ba80-1cad-11ea-896e-e121e9d8d202.png)

![Screenshot from 2019-12-12 07-04-25](https://user-images.githubusercontent.com/1583873/70686796-a7e5da00-1cad-11ea-8f07-131d39af8bb6.png)

**Comment by chauhanparth210** [comment]
@mariobehling  I am taking this issue.

**Comment by kpulkit29** [comment]
@chauhanparth210  are you working on it?
