### ISSUE TITLE
unable to create account on sus.ai

### ISSUE THREAD

**Issue by royan0007** [fossasia/susi.ai#3109]
**Actual Behaviour**

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by royan0007** [comment]
i am unable to login on sus.ai

**Comment by plxity** [comment]
@royan0007 Signup functionality is working fine. Try signing up again.

**Comment by akshatnitd** [comment]
Can't reproduce this issue. Closing it.
