### ISSUE TITLE
Smooth scrolling  & disappearance of down button

### ISSUE THREAD

**Issue by chauhanparth210** [fossasia/susi.ai#3114]
**Actual Behaviour**
* While chatting  with the bot, the smooth scrolling is not working for down navigation button.  
* Reaching at the end of chat part, the down navigation button is not disappear.

**Expected Behaviour**
* Smooth scrolling should be working for down navigation button 
* Down navigation should be disappear while it reaching at end of the chat conversation.  

**Screenshots of the issue**
![captured](https://user-images.githubusercontent.com/35137224/70971585-554e5880-20c7-11ea-879f-ccff579e7a59.gif)

**Would you like to work on the issue?**
Yes

**Comment by simranaggarwal1999** [comment]
Can I work on it?

**Comment by simranaggarwal1999** [comment]
Hey I have resolved the issue

**Comment by simranaggarwal1999** [comment]
@chauhanparth210 Could you please review my pull request

**Comment by simranaggarwal1999** [comment]
@chauhanparth210  Hey! I have solved the issue. Kindly review my pull request.

**Comment by simranaggarwal1999** [comment]
@chauhanparth210 Hey! I have solved the issue. Kindly review my pull request.
