### ISSUE TITLE
Theme color for mobile devices

### ISSUE THREAD

**Issue by MuhammadWasif** [fossasia/susi.ai#3116]
**Actual Behaviour**
Currently, there's no specific theme for the web app.
**Expected Behaviour**
There should be a theme color that matches the theme of SUSI.AI web app.
**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Low priority and not a focus currently. We have enough issues that really need attention. Please help to keep the team focused on actual issues that impact the users more substantially. Thanks.
