### ISSUE TITLE
Feature to delete a skill created by the user.

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3119]
**Actual Behaviour**

Currently, there is no feature to delete skills created by the user.

**Expected Behaviour**

It should not be the case as the user should be allowed to delete his/her skill. 

**Would you like to work on the issue?**

Yes

**Comment by DipanshiB** [comment]
Is this issue open for contributing? Can I take it up or is someone working on it? @Dilshaad21

**Comment by akshatnitd** [comment]
This feature is already there and is there with the admins.

**Comment by Dilshaad21** [comment]
:+1: Ok it's fine then.
