### ISSUE TITLE
Change SUSI Widget reply to Hi

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi.ai#3120]
**Actual Behaviour**
On sending **Hi** to the SUSI bot widget replies with the following message:
`
Well hello and welcome to the Fossasia Google Code-in Website. How may I help you ?
`

Why is it specifically saying **Google Code-in Website**?

**Expected Behaviour**

It should not specifically mention Google Code-in. 

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/10573038/71107806-d997fd00-21e7-11ea-854e-bd522a26fd85.png)

**Comment by pranavkarthik10** [comment]
This is based on a skill someone wrote in which hi is a query. Due to conflicts between skills this is the chosen answer for the query hi.

**Comment by AnupKumarPanwar** [comment]
But that doesn't look good. That skill should be modified.

**Comment by antonyalex** [comment]
I am working on it

**Comment by plxity** [comment]
@AnupKumarPanwar This issue doesn't belong to this Repository. You may close this.
