### ISSUE TITLE
Bots are misbehaving

### ISSUE THREAD

**Issue by NishithP2004** [fossasia/susi.ai#3135]
**Actual Behaviour**
The SUSI.AI bot added to the site is not proper.On typing a 'hi' message it replies to another context not pertaining to the site.
This same error is seen in all the preview bots created by an individual.

**Expected Behaviour**
The bot should give info pertaining to the site or respond the same as data provided by an individual.

**Steps to reproduce it**
Open the susi.ai site and type an 'hi' message to the added preview bot.

**LogCat for the issue**

**Screenshots of the issue**
![Screenshot (26)](https://user-images.githubusercontent.com/34577844/71359945-39a9ed00-25b4-11ea-8ff8-da57986a8eb6.png)
![Screenshot (27)](https://user-images.githubusercontent.com/34577844/71360221-1469ae80-25b5-11ea-91c5-67a635f18da4.png)

**Would you like to work on the issue?**

**Comment by akshatnitd** [comment]
This issue has bee fixed.
