### ISSUE TITLE
No auto-scrolling of the chat in the preview. 

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3136]
**Actual Behaviour**

The SUSI chat in the preview section of `Create a Susi skill` has no feature of auto-scrolling.

**Expected Behaviour**

It should have the feature to auto-scroll as the user continues the conversation.

**Screenshots of the issue**

![final_5e00bf9dfb4b130013a8fb80_331494](https://user-images.githubusercontent.com/45489945/71360511-226bff00-25b6-11ea-8cf4-8e4ea701efe0.gif)

**Would you like to work on the issue?**

Yes

**Comment by aahel** [comment]
i would like to work on this issue
