### ISSUE TITLE
Fix alignments in team page

### ISSUE THREAD

**Issue by kumuditha-udayanga** [fossasia/susi.ai#3151]
**Description**
In the current team page, the "Project managers" and "Project founders" sections are not aligned properly.

**Actual Behaviour**

<img width="849" alt="Screenshot 2019-12-26 at 21 48 36" src="https://user-images.githubusercontent.com/27630091/71482652-c90c0600-2829-11ea-9a3b-fc1a1d40b00c.png">

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/27630091/71482689-eb058880-2829-11ea-8ded-5d50e69162ef.png)

**Steps to reproduce it**
1. Navigate to the team page.

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
It is not a valid issue, the design is intentional.
