### ISSUE TITLE
Social Icons in Blog section requires attention

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3156]
**Actual Behaviour**
There are a few icons in social section also there is no space in between them.
Also the cursor doesn't show any responsive change as we hover over them

**Expected Behaviour**

Share to whatsapp, Telegram should be available

**Would you like to work on the issue?**

YES
**ScreenShot:**
![Screenshot 2019-12-27 at 9 59 46 PM](https://user-images.githubusercontent.com/43617894/71524581-34baa580-28f4-11ea-83b2-47490666449d.png)

**Comment by Dishebh** [comment]
@anishagg17 if it is up for grabs, can I take it?

**Comment by anishagg17** [comment]
Bro my pull request is under consideration, I am made the pr only review is left
