### ISSUE TITLE
Making navigation bar sticky

### ISSUE THREAD

**Issue by plxity** [fossasia/susi.ai#3158]
**Actual Behaviour**

Currently, the navigation bar is not sticky.

**Expected Behaviour**

The navigation bar should be sticky as it would help the users to access its feature from any part of the page.

**Would you like to work on the issue?**

Yes, I am working on this issue.

**Comment by aahel** [comment]
I am working on this issue.

**Comment by akshatnitd** [comment]
Currently, the app bar doesn't stick all the time while scrolling, but shows up when you try to scroll upwards. This is the standard pattern being followed nowadays. Hence, closing the issue.
