### ISSUE TITLE
Bottom to Top Button

### ISSUE THREAD

**Issue by aryamanpuri** [fossasia/susi.ai#3162]
**Actual Behaviour**

There is no Bottom to Top Button.

**Expected Behaviour**

There should be a Button which will take the user to the Top

**Comment by anishagg17** [comment]
on which page you faced this issue... 
Can you please upload **screenshot**

**Comment by aryamanpuri** [comment]
@anishagg17 Generally there is this kind of button on every website.
You can see on the Home Page itself.
> on which page you faced this issue...
Take it as an enchancement

**Comment by snitin315** [comment]
@aryamanpuri , I guess we have back to top button on many pages , you have to be specific on which page you didn't find it.

**Comment by aryamanpuri** [comment]
> you have to be specific on which page you didn't find it.

localhost:3000 | https://susi.ai

**Comment by snitin315** [comment]
There is back to top button on homepage , it appears after some scrolling next to the chat bot icon.

**Comment by aryamanpuri** [comment]
@snitin315

**Comment by snitin315** [comment]
> @snitin315 can you upload s screenshot

![Screenshot from 2019-12-29 21-19-38](https://user-images.githubusercontent.com/46647141/71570522-86814c80-2afb-11ea-9fba-48958b1c72ed.png)
