### ISSUE TITLE
Missing contributors  section in team section

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3163]
**Actual Behaviour**
There is no contributors section

**Would you like to work on the issue?**
YES , if the contributors section is required

**Comment by anishagg17** [comment]
@akshatnitd  Is it required?

**Comment by Sid911** [comment]
I think it should be there 😄... Let's see what others have to say about it..

**Comment by alekhgupta1441** [comment]
Contributors have played a significant role in development of this website .So, I think this improvement should be done.
