### ISSUE TITLE
Basic installation steps missing in README

### ISSUE THREAD

**Issue by snitin315** [fossasia/susi.ai#3167]
**Actual Behaviour**
Currently README.md does not have installation steps to setup the project locally . This can create trouble for beginners who are new to open source and trying to set up the project locally.

**Expected Behaviour**
Required installation steps must be added in README.md .

**Additional Context**
I will work on this issue

**Comment by Rishi007-web** [comment]
Yah! You are right.
I am a beginner and I am facing issues in setup a project locally.
So, please add the installation step.

**Comment by snitin315** [comment]
@Rishi007-web  working on it , will file a PR ASAP

**Comment by Rishi007-web** [comment]
OK, Thanks
