### ISSUE TITLE
Content Loader in main page not fit for large screens

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3168]
**Actual Behaviour**

The content loader in the main page is not fit for large screen sizes.

**Expected Behaviour**

It should adjust the size dynamically according to the screen size.

**Screenshots of the issue**

![un](https://user-images.githubusercontent.com/45489945/71567868-48c6f880-2ae8-11ea-8065-c9eb84774428.png)

**Would you like to work on the issue?**

Yes

**Comment by Rishi007-web** [comment]
I think it's work fine on a 15.6-inch laptop.

![content_loader](https://user-images.githubusercontent.com/57035408/71568419-1966ba80-2aed-11ea-8c9e-008925430fe9.png)

**Comment by Dilshaad21** [comment]
Ya, but it should be fine for all the screen sizes.

**Comment by kpulkit29** [comment]
@Dilshaad21 Can I work on this.
