### ISSUE TITLE
Contact button lacks a back top top button

### ISSUE THREAD

**Issue by MuhammadWasif** [fossasia/susi.ai#3185]
**Actual Behaviour**
There's no **Back to Top** button on Contact Page
**Expected Behaviour**
_Back to Top_ button is available on every page but it's not on _Contact_ page
**Steps to reproduce it**
Go to [susi.ai/contact](https://susi.ai/contact) and scroll. You'll not see any _Back to Top_ button

**Would you like to work on the issue?**
Yes

**Comment by varun14gb** [comment]
I would like to work on this issue.
