### ISSUE TITLE
Empty Blog page rendered

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3188]
**Actual Behaviour**

![Screenshot 2020-01-02 at 3 57 28 PM](https://user-images.githubusercontent.com/43617894/71662818-cc971400-2d78-11ea-8c49-a9300e7aea46.png)

**Steps to reproduce it**
Goto last page on Blog section

**Would you like to work on the issue?**
Yes

**Comment by Jayashree-panda** [comment]
Hi @anishagg17 
Actually the blogs are getting rendered, just taking a while.
![Screenshot from 2020-01-02 20-42-48](https://user-images.githubusercontent.com/33364652/71674145-835aba80-2da0-11ea-8b1d-6e1a370bf612.png)
![Screenshot from 2020-01-02 20-42-51](https://user-images.githubusercontent.com/33364652/71674152-86ee4180-2da0-11ea-82bf-a4a460357649.png)

**Comment by anishagg17** [comment]
@Jayashree-panda please read steps to reproduce it

**Comment by Jayashree-panda** [comment]
@anishagg17 Sorry but I couldn't understand the need to reproduce?
