### ISSUE TITLE
Login fails when user enters email in capital

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3196]
**Actual Behaviour**
![Hnet-image (2)](https://user-images.githubusercontent.com/43617894/71727103-3f7aba80-2e5f-11ea-9148-c4aa6f0e5967.gif)

Login fails when user enters email in capital

**Expected Behaviour**

if user enters email in capital login action should be completed

**Steps to reproduce it**

try logging in with email in capital letters

**Would you like to work on the issue?**
Yes

**Comment by kpulkit29** [comment]
Isn't this the desired behaviour ?

**Comment by anishagg17** [comment]
> Isn't this the desired behaviour ?

No
