### ISSUE TITLE
No need of chat with susi on navbar

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3227]
**Actual Behaviour**

There are two ways to open chat with susi
• via navbar
• via chat buble
 Both of them are present on every page 

**Expected Behaviour**

Navbar should not have option for chat

**Would you like to work on the issue?**
 
Yes

**Comment by simranaggarwal1999** [comment]
@anishagg17  Can I work upon this issue?

**Comment by anishagg17** [comment]
> @anishagg17 Can I work upon this issue?

Go ahead

**Comment by simranaggarwal1999** [comment]
@anishagg17 Kindly review my pull request.

**Comment by akshatnitd** [comment]
Please get issues confirmed before working on them.

**Comment by simranaggarwal1999** [comment]
@akshatnitd But I asked before working on this issue.
