### ISSUE TITLE
Development Environment not loading

### ISSUE THREAD

**Issue by DipanshiB** [fossasia/susi.ai#3243]
**Actual Behaviour**

Upon running the start script in the terminal, the react server starts and the browse skills home route loads up on the browser. However before it gets completely loaded, errors show up. Upon checking the console, 12 errors are showing up, and no page is being loaded. 

**Expected Behaviour**

Till a few days ago the website was loading correctly, I was able to go through the webpages and browse skills and use the chatbot. The pages should get rendered correctly.

**Screenshots of the issue**

![Screenshot from 2020-01-09 20-00-41](https://user-images.githubusercontent.com/41778043/72091650-ace28b80-3336-11ea-928d-2d35e08806b8.png)

![Screenshot from 2020-01-09 20-00-44](https://user-images.githubusercontent.com/41778043/72091664-b4a23000-3336-11ea-955b-aa7a0b018011.png)

![Screenshot from 2020-01-09 20-00-47](https://user-images.githubusercontent.com/41778043/72091739-de5b5700-3336-11ea-96c5-499008ef891d.png)

**Would you like to work on the issue?**

Yes, I am trying to work on it. However I do request anyone else facing the same issue to comment below with their specifications so that it's easier to come to a conclusion.

**Comment by anishagg17** [comment]
Please don't duplicate issue #3221

**Comment by DipanshiB** [comment]
Oh right, I did not notice it was opened already.
