### ISSUE TITLE
prevent rapid firing of searches

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3244]
**Actual Behaviour**

as each alphabet is changed in the search bar a new search is rendered . Which leads to many searches 

**Expected Behaviour**

should use least searches while the user is still typing a search query 
Debounce may be used to fix this behaviour

**Would you like to work on the issue?**

Yes

**Comment by kpulkit29** [comment]
@anishagg17  denounce is already implemented .

**Comment by kpulkit29** [comment]
This issue can be closed as debounce is already implemented

**Comment by anishagg17** [comment]
bro I will surely close it as soon as the server is back up again and I check up
