### ISSUE TITLE
API response should not leave the website blank

### ISSUE THREAD

**Issue by kpulkit29** [fossasia/susi.ai#3245]
**Actual Behaviour**

The website goes blank due to unexpected response from the API . Some missing checks cause it to go blank.  At some places the code is directly accessing object properties which can always be error prone and may cause the following code to break. Currently the app.js file in reducer and SkillCardScrollList.js throw error  whenever the API is down.

**Expected Behaviour**

Checks should be there instead of directly accessing the object properties

**Screenshots of the issue**

<img width="664" alt="Screenshot 2020-01-10 at 4 18 13 PM" src="https://user-images.githubusercontent.com/20151526/72148911-f9c27280-33c7-11ea-99b1-12ffc23785fa.png">
<img width="1261" alt="Screenshot 2020-01-10 at 4 19 43 PM" src="https://user-images.githubusercontent.com/20151526/72148912-f9c27280-33c7-11ea-8453-1fcdb6739386.png">

**Would you like to work on the issue?**

yes

**Comment by anishagg17** [comment]
Please don't duplicate issue #3221
