### ISSUE TITLE
Give z-index to the scrollTopButton

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3249]
**Actual Behaviour**

The screenshot below shows the current behaviour of the `scrollTopButton` which is not as expected.

**Expected Behaviour**

Set `z-index` to set it to the top of everything else.

**Screenshots of the issue**

![Screenshot from 2020-01-11 13-03-23](https://user-images.githubusercontent.com/45489945/72200756-575fc900-3473-11ea-9607-693a650c1eda.png)

**Would you like to work on the issue?**
Yes

**Comment by arrbxr** [comment]
@Dilshaad21 Can I work upon this issue?
