### ISSUE TITLE
Username not getting displayed in the NavBar

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3253]
**Actual Behaviour**

Username is not getting displayed in the navbar.

**Expected Behaviour**

It should not be the case it should get displayed.

**Screenshots of the issue**
![Screenshot from 2020-01-11 14-52-34](https://user-images.githubusercontent.com/45489945/72202134-1327f500-3482-11ea-9d2c-59220a84ec9b.png)

**Would you like to work on the issue?**

Yes

**Comment by Dishebh** [comment]
@Dilshaad21 @anushkamittal can I take this up?

**Comment by mohitm15** [comment]
@Dilshaad21 Non - reproducible

**Comment by Dishebh** [comment]
@Dilshaad21 pls close the issue. It has already been fixed.

**Comment by Dilshaad21** [comment]
I think this some problem related with the server. Closing.
