### ISSUE TITLE
Password gets auto cleared if it doesn't match

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3267]
**Expected Behaviour**

Password should not be cleared if it doesn't match

**Steps to reproduce it**

Add wrong password while logging in

**Screenshots of the issue**

![Hnet com-image (5)](https://user-images.githubusercontent.com/43617894/72217450-c44a9000-3553-11ea-8c2e-fbdd826e8d69.gif)

**Would you like to work on the issue?**

Yes

**Comment by Sulekhiya** [comment]
Are you working on the issue?

**Comment by anishagg17** [comment]
If you want to work on it You can

**Comment by Sulekhiya** [comment]
Okay, I am working on it!

**Comment by akshatnitd** [comment]
Invalid issue. The correct behavior is clearing it.

**Comment by Sulekhiya** [comment]
Okay Cool !!
