### ISSUE TITLE
Bugs in custom theme dialog

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3273]
**Actual Behaviour**

save button is neither disabled nor given a loader 
missing set background colour of chat text
Message Image URL does not gives preview of image

![Screenshot 2020-01-13 at 5 54 27 PM](https://user-images.githubusercontent.com/43617894/72255839-c7b24a00-362d-11ea-927d-ff1d870a7337.png)
this is the util used to render message in chat box , It clearly shows a background colour necessity which was not passed

**Steps to Reproduce**

goto settings->theme->custom theme
try saving changes (you will notice no change in save button)
you will notice no option for messages background 
Also, image preview is not available

**Would you like to work on the issue?**

Yes

**Comment by harsh253** [comment]
Hi @anishagg17 . Can you please mention the steps to reproduce this issue ?
