### ISSUE TITLE
Gif is not previewed in chat with susi

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3284]
**Actual Behaviour**

Gif is not previewed in chat with susi

**Expected Behaviour**

Gif like map should be previewed in chat with susi

**Steps to reproduce it**

type gif angry in chat 
 
**Screenshots of the issue**

![Screenshot 2020-01-14 at 7 58 09 PM](https://user-images.githubusercontent.com/43617894/72352395-32d04f00-3708-11ea-9612-ef8a821b98eb.png)

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
Discuss the approach before solving this.

**Comment by anishagg17** [comment]
Sir i have implemented it


![Screenshot 2020-01-16 at 1 22 18 PM](https://user-images.githubusercontent.com/43617894/72504127-3a583b00-3863-11ea-90f3-6e3b841996da.png)

**Comment by anishagg17** [comment]
I used generateGifBubble which was commented out with adjustments
