### ISSUE TITLE
Feature to zoom images in chat

### ISSUE THREAD

**Issue by kpulkit29** [fossasia/susi.ai#3285]
**Actual Behaviour**

No option to zoom images as off now

**Expected Behaviour**

There should be an option to zoom images on hover.

**Screenshots of the issue**

<img width="394" alt="Screenshot 2020-01-15 at 1 01 03 AM" src="https://user-images.githubusercontent.com/20151526/72375700-953e4500-3732-11ea-8d5e-ff2ab06bb244.png">

**Would you like to work on the issue?**

yes

**Comment by simranaggarwal1999** [comment]
is this issue open now ? 
Can I work on it?

**Comment by kpulkit29** [comment]
I am working on it.

**Comment by Dishebh** [comment]
@kpulkit29 can i take up the issue?

**Comment by kpulkit29** [comment]
I am working on it

**Comment by tewarig** [comment]
Can I work on it?

**Comment by snitin315** [comment]
> Can I work on it?

Sure, Go ahead.

**Comment by tewarig** [comment]
@sachin235 
![issue](https://user-images.githubusercontent.com/54894783/81839619-6cee1800-9565-11ea-805c-26db62e02a9a.gif)
this is what I have made.. is it okay? 😸

**Comment by snitin315** [comment]
The image should zoom om hover as said in issue.

**Comment by tewarig** [comment]
finally, is it done @sachin235 thanks for your help.
![final](https://user-images.githubusercontent.com/54894783/81849716-92cee900-9574-11ea-84c3-1e44f7728241.gif)

**Comment by akshatnitd** [comment]
This feature is not required. Hence, closing.
