### ISSUE TITLE
add contributions best practice section in Readme.md

### ISSUE THREAD

**Issue by snitin315** [fossasia/susi.ai#3288]
**Actual Behaviour**
Cuurently we dont have such section guiding beginners for best pracices

**Expected Behaviour**
The section should be available in README.md

**Would you like to work on the issue?**
YES

**Comment by kunakl07** [comment]
I like to contribute towards this issue.
Could you please guide me further

**Comment by snitin315** [comment]
@kunakl07 I have already made PR for the issue ,  you can check on some other issues.
