### ISSUE TITLE
No footer in settings section

### ISSUE THREAD

**Issue by anishagg17** [fossasia/susi.ai#3298]
**Actual Behaviour**

No footer in settings section

**Screenshots of the issue**

![Screenshot 2020-01-16 at 10 19 06 PM](https://user-images.githubusercontent.com/43617894/72544946-3998c680-38ae-11ea-971b-359e8c144887.png)

**Would you like to work on the issue?**

Yes

**Comment by Dishebh** [comment]
@anishagg17 if you're not working, can I take up this issue pls?

**Comment by anishagg17** [comment]
Bro I am working on it
