### ISSUE TITLE
Button overflow

### ISSUE THREAD

**Issue by Dishebh** [fossasia/susi.ai#3304]
**Actual Behaviour**
The `Create Skill` button overflows on Dashboard page on small screens.

**Expected Behaviour**
The button should not overflow.

**Steps to reproduce it**
- Login and go to on dashboards page.
- Check the page on small screens, you will see the button overflow in x-direction.

**Screenshots of the issue**
![Screenshot from 2020-01-17 16-52-47](https://user-images.githubusercontent.com/43489708/72624626-50522280-396d-11ea-9834-b732eca6f146.png)

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
This issue is invalid. We don't need to check screen sizes less than 320px.
