### ISSUE TITLE
"Scroll to top" floating action button is covered up by skillcard elements

### ISSUE THREAD

**Issue by rico-et22** [fossasia/susi.ai#3309]
**Actual Behaviour**
The "scroll to top" floating action button (`ScrollToTop` component) is being covered up by some skill card elements, such as image, comment and stars. This happens due to z-index problems

**Expected Behaviour**
The "scroll to top" button should go over these elements, being clearly visible all the time

**Steps to reproduce it**
- Start a susi.ai server
- Open a local susi.ai site and scroll down
- Watch the "scroll to top" button getting covered up by skill card elements

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/28688352/72651833-02491900-3985-11ea-9ff7-1a38aff600a6.png)

**Would you like to work on the issue?**
Yes

**Comment by anishagg17** [comment]
A pr, issue has already been made to fix it please close this issue
Reffer to #3250
