### ISSUE TITLE
Adjust the social profiles buttons

### ISSUE THREAD

**Issue by Dishebh** [fossasia/susi.ai#3321]
**Actual Behaviour**
The social profile buttons aren't responsive with the page.

**Expected Behaviour**
The social profile icons should adjust their alignment as and when the page resolution changes.

**Steps to reproduce it**
- Go to the `Share On the Social Media` option in settings and tune the screen resolutions.

**Screenshots of the issue**
![Screenshot from 2020-01-18 21-47-30](https://user-images.githubusercontent.com/43489708/72667435-02f3b500-3a42-11ea-8723-b7a37730eaf3.png)

**Would you like to work on the issue?**
Yes

**Comment by arghac14** [comment]
@Dishebh can I work on this?

**Comment by Dishebh** [comment]
@arghac14 Pls wait until the pr gets reviewed. Till then, you can find another issue to work on. Thanks.
