### ISSUE TITLE
Fixing issues regarding social icons in 'Share about SUSI' menu

### ISSUE THREAD

**Issue by tobehonest** [fossasia/susi.ai#3326]
**Actual Behavior**
Here are few problems in this menu :
1. The text box does not cover problem space.
2. Hovering on social media icons works in Firefox but not on chrome.
3. The hover actions(in Firefox) and click actions doesn't match.

**Expected Behavior**

1. Text box must cover at least 90% of the box
2. Hover actions must be same for both the browsers, in chrome no hovering action is seen.
3. Same needs to be corrected

**Steps to reproduce it**

Goto : Settings->Share About SUSI->

1. Hover over the social media buttons and press left on them(keep it pressed for 3). SS have been added.

**Screenshots of the issue**

Hover + Click :
![Firefox click and hover conflict](https://user-images.githubusercontent.com/42002993/72676788-34f52d80-3abb-11ea-810a-269fcceee48f.png)

On hovering in firefox:
![Firefox hover vs google chrome hover](https://user-images.githubusercontent.com/42002993/72676789-37578780-3abb-11ea-8f35-8449750549f3.png)
No action on hovering in chrome:
![Firefox hover vs google chrome hover](https://user-images.githubusercontent.com/42002993/72676791-39214b00-3abb-11ea-8b6e-64bc9c118620.png)

Textbox size :
![Textbox wrap](https://user-images.githubusercontent.com/42002993/72676841-b056df00-3abb-11ea-98e5-cc2e2124a392.png)

**Would you like to work on the issue?**

Yes

**Comment by Akshit-Patel** [comment]
if it's open for a grab, can i work on this?

**Comment by tobehonest** [comment]
@Akshit-Patel I have already made a pull request for this issue. Till then, you can find another issue to work on. Thanks.
