### ISSUE TITLE
Scroll up button misbehaves

### ISSUE THREAD

**Issue by tobehonest** [fossasia/susi.ai#3343]
**Actual Behaviour**
![Screenshot from 2020-01-20 13-32-26](https://user-images.githubusercontent.com/42002993/72742105-0cf6ee80-3bcf-11ea-8895-14d6bcb1ee70.png)

**Expected Behaviour**

Scroll up button should be hidden in such cases

**Would you like to work on the issue?**

Yes

**Comment by elit-altum** [comment]
Along with this, the scroll to bottom button keeps on displaying on mobile screens even when the chat is at the bottom
![ScrollBottomNotWorking](https://user-images.githubusercontent.com/41413622/73673748-376ba000-46d5-11ea-8e2f-97f1245bdb7f.PNG)

**Comment by tobehonest** [comment]
This one is fixef
