### ISSUE TITLE
Fix forgot password modal in 'password' tab of settings.

### ISSUE THREAD

**Issue by plxity** [fossasia/susi.ai#3347]
**Actual Behaviour**

As of now when a user opens the password tab in settings and clicks on forgot your password link. The modal opens up which shows an option for login. This option should not be visible as user is already logged in.
![Screenshot from 2020-01-21 02-41-08](https://user-images.githubusercontent.com/28510494/72758533-1ac16980-3bf9-11ea-81f2-b9a3ea1aa6f1.png)

![Screenshot from 2020-01-21 02-42-00](https://user-images.githubusercontent.com/28510494/72758547-21e87780-3bf9-11ea-8847-bc8844b5e012.png)

**Expected Behaviour**

Login option should not be visible to the user.

**Steps to reproduce it**
1) Go to password tab in settings
2) Click on forgot your password.
3) A modal will open up. It will have an option for login

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes, I am working on this.

**Comment by Dishebh** [comment]
@plxity are you still working on the issue? If not, can I take it? Seems to me you are already working on some other issue.

**Comment by plxity** [comment]
@Dishebh This is already fixed. The PR is merged.
