### ISSUE TITLE
Navigation not visible properly in various devices.

### ISSUE THREAD

**Issue by meliodas113** [fossasia/susi.ai#3352]
**Actual Behaviour**

Navigation bar is not completely responsive.

**Expected Behaviour**

Navigation bar should be completely responsive in all devices.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

![Screenshot 2020-01-21 at 8 01 58 PM](https://user-images.githubusercontent.com/46742717/72813227-0167fe00-3c89-11ea-9a79-00bc71436cbf.png)

![Screenshot 2020-01-21 at 8 02 33 PM](https://user-images.githubusercontent.com/46742717/72813258-0b89fc80-3c89-11ea-8491-0bf3d2472e95.png)

![Screenshot 2020-01-21 at 8 02 16 PM](https://user-images.githubusercontent.com/46742717/72813262-0e84ed00-3c89-11ea-90d7-de83427ed8c3.png)

**Would you like to work on the issue?**

Yes

**Comment by kpulkit29** [comment]
@meliodas113 This is a duplicate issue.The original one is    #3048. Kindly close this. Please don't create3 duplicate issues.
