### ISSUE TITLE
Click on filters button not working properly (Mobile)

### ISSUE THREAD

**Issue by kpulkit29** [fossasia/susi.ai#3378]
**Actual Behaviour**

When  somebody clicks to slightly  left of the filter button (outside the button) the sidemenu opens up.

**Expected Behaviour**

Side menu should open only when clicked on the button

**Steps to Reproduce**
    - Open the homepage in mobile
    - Click to slightly left of filter button

**Screenshots**
<img width="347" alt="Screenshot 2020-01-23 at 11 35 01 PM" src="https://user-images.githubusercontent.com/20151526/73011261-e688bb80-3e39-11ea-8231-1e62e28e2b86.png">

**Would you like to work on the issue?**
Yes

**Comment by anishagg17** [comment]
@kpulkit29 may i work over this issue?

**Comment by kpulkit29** [comment]
Actually @anishagg17 I have made the changes, just have to raise the PR.
