### ISSUE TITLE
Unnecessary scroll bar present in speech tab in settings.

### ISSUE THREAD

**Issue by plxity** [fossasia/susi.ai#3379]
**Actual Behaviour**

When clicked on 'speech' tab in settings unnecessary scroll bar adds up in the x-direction.
![Screenshot from 2020-01-24 00-18-29](https://user-images.githubusercontent.com/28510494/73014059-8268f600-3e3f-11ea-822e-2b180f697c29.png)

**Expected Behaviour**

There should not be a scroll bar in the x-direction.

**Steps to reproduce it**

**Would you like to work on the issue?**

Yes, I am working on this.

**Comment by Dishebh** [comment]
@plxity Are you still working on this? If not, can I take it?

**Comment by plxity** [comment]
@Dishebh Yes, I'm working on this.
