### ISSUE TITLE
Console errors in AccountTab

### ISSUE THREAD

**Issue by Dilshaad21** [fossasia/susi.ai#3382]
**Actual Behaviour**

There are many console errors in Account Tab section.

**Expected Behaviour**

Fix those errors

**Screenshots of the issue**

![Screenshot from 2020-01-24 16-47-29](https://user-images.githubusercontent.com/45489945/73065485-a8d37380-3ec9-11ea-9bf4-3beaf9af2264.png)

**Would you like to work on the issue?**

Yes, I'm working on this

**Comment by anishagg17** [comment]
please close this issue too..
