### ISSUE TITLE
website responding with 404

### ISSUE THREAD

**Issue by Dishebh** [fossasia/susi.ai#3390]
**Actual Behaviour**
Currently, the website responds with 404

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**
![Screenshot from 2020-01-25 18-14-49](https://user-images.githubusercontent.com/43489708/73121311-d4745d80-3f9e-11ea-9bf1-9e7ea512d5c0.png)

**Would you like to work on the issue?**

**Comment by Dilshaad21** [comment]
@Dishebh close this issue as a PR which reverts the commit is already made.
