### ISSUE TITLE
Forgot Password not working.

### ISSUE THREAD

**Issue by manosriram** [fossasia/susi.ai#3400]
**Actual Behaviour**
After clicking the link sent to the mail and entering the new password, it just opens a white blank page.

**Expected Behaviour**
The Entered password must be updated as the new password and the user should be logged in.

**Steps to reproduce it**
1. Click on Login.
2. Click Forgot password.
4. Enter email and click reset.
4. Open the link sent to mail.
5. Enter new password and click submit.

**Would you like to work on the issue?**
Need some help to get started.

**Comment by BLasan** [comment]
It's updating successfully
