### ISSUE TITLE
Unnecessary entry in the submenu of  "SUSI skills".

### ISSUE THREAD

**Issue by mohitm15** [fossasia/susi.ai#3413]
**Actual Behaviour**
Unnecessary entry named `en` (Last entry)  is present in the submenu of `susi skills`.

**Expected Behaviour**
Needs to be removed from the submenu.

**Steps to reproduce it**
1. Go to Home Page
2. See Error

**Screenshots of the issue**
![Screenshot 2020-02-02 17:55:44](https://user-images.githubusercontent.com/35539313/73608163-61de3000-45e5-11ea-89be-408ea0c3ff76.png)

**Would you like to work on the issue?**
Yes, working on it.

**Comment by simranaggarwal1999** [comment]
Hey! Is this issue up to be rectified? May I work upon it?

**Comment by mohitm15** [comment]
@simranaggarwal1999 Go ahead

**Comment by mohitm15** [comment]
@simranaggarwal1999 Any updates?

**Comment by simranaggarwal1999** [comment]
Not yet. I have to start working upon it.

**Comment by Dishebh** [comment]
@simranaggarwal1999 @mohitm15 if it is up for grabs, can I take it?

**Comment by mohitm15** [comment]
@simranaggarwal1999 is working on this!
What's the status @simranaggarwal1999 ?

**Comment by snitin315** [comment]
There is no sign of work done , you can go ahead with this

**Comment by simranaggarwal1999** [comment]
@Dishebh You may work upon it. Meanwhile I will also try.

**Comment by snitin315** [comment]
> @Dishebh You may work upon it. Meanwhile I will also try.

15 days and you have still not tried. Please claim an issue only if you are confident you can solve it and you have time to solve it.
Otherwise make way for active contributors.

**Comment by simranaggarwal1999** [comment]
@snitin315 Sorry for the inconvenience. But I was busy with another issue of the same project from a long time. It is stuck.

**Comment by mohitm15** [comment]
> @snitin315 Sorry for the inconvenience. But I was busy with another issue of the same project from a long time. It is stuck.

@simranaggarwal1999 not worthy that two people working on same issue.
@Dishebh Go ahead and report me the status?

**Comment by mohitm15** [comment]
@Dishebh any updates?

**Comment by Dishebh** [comment]
> @Dishebh any updates?

Busy with something else, currently. Anyone else is welcome to take up the issue.

**Comment by mohitm15** [comment]
> > @Dishebh any updates?
> 
> Busy with something else, currently. Anyone else is welcome to take up the issue.

@simranaggarwal1999 Go aheaf

**Comment by mohitm15** [comment]
@simranaggarwal1999 Any updates , Stale !

**Comment by arteevraina** [comment]
@mohitm15 I cannot reproduce this issue. Is it still there? 
![image](https://user-images.githubusercontent.com/43968121/81819912-8c794680-954d-11ea-8f1c-9abe5f54e772.png)

**Comment by chetan-v** [comment]
@snitin315 I wanna work on it

**Comment by akshatnitd** [comment]
Not a valid issue.
