### ISSUE TITLE
Multiple Options can be selected from language drop-down.

### ISSUE THREAD

**Issue by mohitm15** [fossasia/susi.ai#3418]
**Actual Behaviour**
Multiple options can be selected from language dropdown.

**Expected Behaviour**
Only a  single option should be selected from the drop-down.

**Steps to reproduce it**
1. Go to Home page.
2. Select Language dropdown.
3. Click on more than one option.

**Screenshots of the issue**
![ezgif com-video-to-gif1](https://user-images.githubusercontent.com/35539313/73655378-ec8d6080-46b3-11ea-8fbf-e962f285c14f.gif)

**Would you like to work on the issue?**
Yes working on it

**Comment by akshatnitd** [comment]
It is a feature.

**Comment by mohitm15** [comment]
but we can view the page in a single language at one time.
@akshatnitd
