### ISSUE TITLE
Chatbot Showing Map in russian Language

### ISSUE THREAD

**Issue by ShubhamChaudharyy** [fossasia/susi.ai#3423]
**Actual Behaviour**

![Screenshot (159)](https://user-images.githubusercontent.com/43263087/73675523-8f57d600-46d8-11ea-9afe-5e60dfd7aba0.png)

**Expected Behaviour**

should be mentioning map assets in English

**Steps to reproduce it**

1. Type Where is india

**Would you like to work on the issue?**

Yes

**Comment by anishagg17** [comment]
please don't duplicate issue #3270
