### ISSUE TITLE
Skill-Cards in grid not clickable.

### ISSUE THREAD

**Issue by tobehonest** [fossasia/susi.ai#3455]
** Actual Behaviour **
![Screenshot from 2020-02-11 19-21-56](https://user-images.githubusercontent.com/42002993/74242534-1f62d480-4d04-11ea-8b2d-a236e9ce7ee9.png)

**Expected Behaviour**

The text on the cards must be clickable like 'Anagrams'. 

**Steps to reproduce it**

1. Click on All under Skills. 
2. The list will be visible in List View
3. Click on grid view.
4. These cards can't be clicked now.

**Screenshots of the issue**

![issue](https://user-images.githubusercontent.com/42002993/74254338-504c0500-4d16-11ea-9571-65d022404c45.gif)

**Would you like to work on the issue?**

Yes.

**Comment by mohitm15** [comment]
Its non-reproducible @tobehonest and already being fixed.
See..
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35539313/74258779-e3883900-4d1c-11ea-8962-e7392618fee4.gif)

**Comment by tobehonest** [comment]
@mohitm15 Please follow steps to reproduce it correctly.

**Comment by mohitm15** [comment]
@tobehonest Thanks for clarification
