### ISSUE TITLE
Problem with Skills Sidebar.

### ISSUE THREAD

**Issue by tobehonest** [fossasia/susi.ai#3456]
**Actual Behaviour**

On clicking any of the skill, in the side bar, all the skill options gets hidden. But on clicking back Susi Skills, all other skills aren't coming back. 
( Comparing to the functionality of New Arrivals , this should happen )

**Expected Behaviour**

After clicking on any of the options in side bar (All , Arts and Beauty etc), the skills gets hidden.
On clicking "< My Skills" ,these skills must be visible again.

**Steps to reproduce it**

1. Click any of the skills category in list
2. Click < My Skills

**Screenshots of the issue**

![Screenshot from 2020-02-11 19-33-21](https://user-images.githubusercontent.com/42002993/74243356-9c427e00-4d05-11ea-8d73-587e50261528.png)
![Issue](https://user-images.githubusercontent.com/42002993/74244823-0c520380-4d08-11ea-9d2e-ebf5ab3cc369.gif)

**Would you like to work on the issue?**

Yes

**Comment by AkashDhiman** [comment]
Hi can i take this issue?

**Comment by tobehonest** [comment]
> Hi can i take this issue?

Akash i am working on it.

**Comment by AkashDhiman** [comment]
Okay, let me know if you need help, I already solved it in my local build.

**Comment by tobehonest** [comment]
> Okay, let me know if you need help, I already solved it in my local build. <
Fixed this one. You may review :)
