### ISSUE TITLE
Display of unspecific number of Skill Card in grid-view.

### ISSUE THREAD

**Issue by mohitm15** [fossasia/susi.ai#3458]
**Actual Behaviour**
On selecting the option for selecting 50 cards , it shows more than 50 cards in the same page.

**Expected Behaviour**
It should display the specified number of skill cards in a single page.

**Steps to reproduce it**
1. Click on All under Skills.
2. The list will be visible in List View
3. Click on grid view icon.
4. Select `Skills per page` display option to 50.
5. See error.

**Screenshots of the issue**
![screencapture-localhost-3000-category-All-2020-02-11-23_11_02](https://user-images.githubusercontent.com/35539313/74262841-ab382900-4d23-11ea-8ab8-73066acb9c9c.png)

**GIF**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/35539313/74263264-7bd5ec00-4d24-11ea-8242-5762e9baa719.gif)
_(Ignore red line)_

**Would you like to work on the issue?**
Yes

**Comment by tobehonest** [comment]
@mohitm15 Are you sure ? I see 41 cards. Please recheck this issue.
