### ISSUE TITLE
Replacing text with their icons on navigation bar

### ISSUE THREAD

**Issue by mohitm15** [fossasia/susi.ai#3466]
**Actual Behaviour**
Replacing the text `Create ` and `Login` on navigation bar.

**Expected Behaviour**
Added their icons

**Steps to reproduce it**
1. See Error at the navigation bar

**Screenshots of the issue**

![Screenshot 2020-02-14 01:32:58](https://user-images.githubusercontent.com/35539313/74473577-d52b5000-4ec9-11ea-8348-dc6ee69648b4.png)

![Screenshot 2020-02-14 01:33:36](https://user-images.githubusercontent.com/35539313/74473601-e07e7b80-4ec9-11ea-82a7-da2a40b55124.png)

**Would you like to work on the issue?**

Yes

**Comment by akshatnitd** [comment]
This change is not required. It was intentionally not replaced with icons. Hence, closing the issue.

**Comment by mohitm15** [comment]
@akshatnitd okay ..just suggestions

_Sent from my VIBE K6 Power using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
