### ISSUE TITLE
Responsive Grid in Blog Page

### ISSUE THREAD

**Issue by MuhammadWasif** [fossasia/susi.ai#3475]
**Actual Behaviour**
The blog page has large posts that take over the whole screen in laptops or desktops. The page has a very large image of blog and covers the whole screen

**Expected Behaviour**
The blog should have a responsive grid system. A nice looking blog page in mobile devices as well as on big screens

**Steps to reproduce it**
Go to `susi.ai/blog` and you will see the inappropriate interface 

**Would you like to work on the issue?**
Yes

**Comment by snitin315** [comment]
looking into it

**Comment by MuhammadWasif** [comment]
@snitin315 Will you create a blog page first? because the whole UI will break even if we fix the heights  😕

**Comment by snitin315** [comment]
yes.

**Comment by akshatnitd** [comment]
We have removed the blog page completely. Hence, closing it.
