### ISSUE TITLE
Unaesthatic UI view of the team page

### ISSUE THREAD

**Issue by mohitm15** [fossasia/susi.ai#3485]
**Actual Behaviour**
The background color of page and the card of colour are similar making it difficult to distinguish the boundary of the card.

**Expected Behaviour**
Change the color card (please refer to PR)

**Steps to reproduce it**
1. Go to Teams Page
2. Scroll down to each section
3. See UI glitch.

**Screenshots of the issue**

![Screenshot 2020-02-16 12:30:34](https://user-images.githubusercontent.com/35539313/74600632-43cf0000-50ba-11ea-94f8-8ef89f36e2b5.png)

**Would you like to work on the issue?**
Yes

**Comment by tobehonest** [comment]
This change doesn't seem necessary.

**Comment by akshatnitd** [comment]
This change not required. Hence, closing the issue and PR.
