### ISSUE TITLE
enhancement(): Highlight the words searched in the chatbot

### ISSUE THREAD

**Issue by mohitm15** [fossasia/susi.ai#3510]
**Actual Behaviour**
Currently, words do not get highlighted that we search no matter how many times they occurs

**Expected Behaviour**
Get highlighted wherever that word occurs.

**Steps to reproduce it**
1. Go to chatbot
2. Search for word say `Fossasia`
2. See error

**Screenshots of the issue**
![Screenshot 2020-02-22 15:37:06](https://user-images.githubusercontent.com/35539313/75090491-6dd86480-5589-11ea-91ad-ba5cc7e96388.png)

**Would you like to work on the issue?**
Yes

**Comment by BLasan** [comment]
@mohitm15  Is this issue still available? Can I work on this?

**Comment by mohitm15** [comment]
Sure
