### ISSUE TITLE
Adding country flags in front of the name in dropdown in Settings Section

### ISSUE THREAD

**Issue by mohitm15** [fossasia/susi.ai#3511]
**Actual Behaviour**
No country flags in front of the name in the dropdown in Settings Section

**Expected Behaviour**
Adding country flags in front of the name in dropdown in Settings Section

**Steps to reproduce it**
1. Go to Settings
2. Select mobile option on sidebar
3. Click the dropdown

**Screenshots of the issue**
![Screenshot 2020-02-22 15:42:59](https://user-images.githubusercontent.com/35539313/75090567-18508780-558a-11ea-95a9-60f81f9db142.png)

**Would you like to work on the issue?**
Yes

**Comment by BLasan** [comment]
@mohitm15  Is this issue still opened? Can I work on this?

**Comment by snitin315** [comment]
Yes
