### ISSUE TITLE
Admin Skills Page - Cannot Open Edit Popup

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#3515]
![Screenshot from 2020-04-13 11-50-21](https://user-images.githubusercontent.com/1583873/79111667-4168e980-7d7d-11ea-9447-2f01eab09180.png)

Cannot open "Edit" pop up on page https://susi.ai/admin/skills

**Comment by MuhammadWasif** [comment]
I am looking into it

**Comment by MuhammadWasif** [comment]
It says **404 - Page not Found**  🙄
Or I don't have access to the page

**Comment by BLasan** [comment]
@mariobehling Can I work on this? Are there any admin credentials?
