### ISSUE TITLE
Deleting skills not working for Admins

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#3517]
The option "Please type in the name of the skill to confirm." does not activate the delete option at https://susi.ai/admin/skills.

![Screenshot from 2020-04-25 23-09-22](https://user-images.githubusercontent.com/1583873/80291009-1b165700-874a-11ea-886e-a8ce42cf5a20.png)

**Comment by madhur1846** [comment]
I would like to work on this issue

**Comment by snitin315** [comment]
Go ahead.

**Comment by madhur1846** [comment]
can u tell me how to check if my changes are working or not because when i open that page it shows we are sorry page not found

**Comment by madhur1846** [comment]
how to check if my changes are working or not because when i open this page it shows page not found?

**Comment by madhur1846** [comment]
> Go ahead.

how to check if my changes are working or not because when i open this page it shows page not found?

**Comment by BLasan** [comment]
> > Go ahead.
> 
> how to check if my changes are working or not because when i open this page it shows page not found?

I think you need admin privileges. How can we fix these issues that need admin privileges ? @snitin315

**Comment by BLasan** [comment]
@mariobehling Is there a way to visit the admin/skills page ?
