### ISSUE TITLE
Admin Pages can only show up to 20 entries per page - show more

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#3518]
Admin pages User, Skills, Bots should be able to show quantities as follows 25, 50, 100, 200, 500 entries per page.

![Screenshot from 2020-04-25 23-13-42](https://user-images.githubusercontent.com/1583873/80291075-a0017080-874a-11ea-8563-d2f79d6d5651.png)

Links
https://susi.ai/admin/skills
https://susi.ai/admin/user
https://susi.ai/admin/bots

**Comment by arteevraina** [comment]
@mariobehling Can I work on this issue?

**Comment by snitin315** [comment]
Yes you can.

**Comment by arteevraina** [comment]
@snitin315 @mariobehling I am not able to reproduce this issue. From the above links I am getting this.
![image](https://user-images.githubusercontent.com/43968121/81506391-957ed380-9313-11ea-812b-6960133a81ef.png)
Any workarounds?

**Comment by snitin315** [comment]
You should have admin previllages to access that page.

**Comment by arteevraina** [comment]
@snitin315 I don't have admin privileges. Can I still work on this issue?

**Comment by BLasan** [comment]
@snitin315 Can I work on this? How do we solve these admin privilege based issues?

**Comment by madhur1846** [comment]
@snitin315  can you tell me more about admit privileges? and how to access this?
