### ISSUE TITLE
Start Page Content area and menu disappear on a number of browsers on larges screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi.ai#3519]
![Screenshot from 2020-05-03 15-32-48](https://user-images.githubusercontent.com/1583873/80915578-84eabe00-8d53-11ea-80ed-48ebdbf1393c.png)

After an initial loading time the start page content in the main area disappears as shown in the screenshot on large screens with a resolution wider than 2560px.

**Comment by BLasan** [comment]
@mariobehling Can I work on this?

**Comment by BLasan** [comment]
@mariobehling Can you specify the browsers?

**Comment by ashwani99** [comment]
I am taking this up

**Comment by BLasan** [comment]
@snitin315 Can I work on this?

**Comment by snitin315** [comment]
If @ashwani99 isn't then you can

**Comment by BLasan** [comment]
> If @ashwani99 isn't then you can

How many days we have to wait?

**Comment by snitin315** [comment]
3-4 days , if there is no sign of work done you can start working.

**Comment by ashwani99** [comment]
@BLasan I am working on it already
