### ISSUE TITLE
susi.ai is giving 0c(euro cents) as an answer to some how to ? Questions.

### ISSUE THREAD

**Issue by tewarig** [fossasia/susi.ai#3524]
**Actual Behaviour**

Susi is giving 0c(euro cents) as an answer to some questions, like how to cook noodles? , how can I cook noodles?
**Expected Behaviour**

Susi should search the web and give the recipes of food.
**Steps to reproduce it**
 just ask susi.ai how to cook noodles?  how can I cook noodles?

**Screenshots of the issue**

![2020-05-09-11-00-22](https://user-images.githubusercontent.com/54894783/81465218-0031f100-91e6-11ea-8ceb-3222352cf0b3.gif)

**Would you like to work on the issue?**
I am just a beginner to open source, I would like to work on other issues.

**Comment by anishagg17** [comment]
did you test this on susi android?

If it gives the same output then It's probably a server side issue and not related to `susi.ai web_client`

**Comment by tewarig** [comment]
yes, there also it is giving the same error.
![WhatsApp Image 2020-05-10 at 10 56 20](https://user-images.githubusercontent.com/54894783/81491525-ffb05d80-92ac-11ea-88f7-b47fbf70a001.jpeg)
