### ISSUE TITLE
bottom links need proper alignment

### ISSUE THREAD

**Issue by nlok5923** [fossasia/susi.ai#3525]
**Actual Behaviour**

Link present at the bottom of the page are not aligned properly.
**Expected Behaviour**

The link should be aligned proper with above section (About devices Blog ) section not aligned properly.

**Steps to reproduce it**

it is not a bug a slight issue with alignment

**LogCat for the issue**

**Screenshots of the issue**

![Screenshot (806)](https://user-images.githubusercontent.com/56120084/81472302-ef648980-91ab-11ea-82b9-801a34aa9f63.png)

**Would you like to work on the issue?**

  I would like to work on this issue.
 please let me know.

**Comment by madhur1846** [comment]
I would like to work on this issue

**Comment by snitin315** [comment]
There is already a PR for this one, you can check some other issues.
