### ISSUE TITLE
Misaligned elements in share susi modal

### ISSUE THREAD

**Issue by elit-altum** [fossasia/susi.ai#3527]
**Actual Behaviour**

Currently the share susi modal has 
- Misaligned content-share button (Mozilla Firefox Developer Edition)
![image](https://user-images.githubusercontent.com/41413622/81480792-70be2980-9249-11ea-9f84-9ab8ce11e122.png)

- Out of textarea scroll-bars (Google Chrome)
![image](https://user-images.githubusercontent.com/41413622/81480806-82073600-9249-11ea-8bd7-b90dc3ddfa1e.png)

**Expected Behaviour**
The textarea and button styles should be fixed and coherent.

**Steps to reproduce it**
- Go to the chatbox and try to share a Susi response

**Would you like to work on the issue?**
Yes

**Comment by elit-altum** [comment]
I have implemented this design for the share susi modal. Please tell me if this okay so I can send a PR !

![image](https://user-images.githubusercontent.com/41413622/81481343-fd1e1b80-924c-11ea-9489-d531b53a498a.png)

@akshatnitd

**Comment by madhur1846** [comment]
I would like to work on this issue

**Comment by snitin315** [comment]
@elit-altum is already working on this.

**Comment by snitin315** [comment]
> I have implemented this design for the share susi modal. Please tell me if this okay so I can send a PR !
> 
> ![image](https://user-images.githubusercontent.com/41413622/81481386-643bd000-924d-11ea-864d-e2f710b9dfc0.png)


You can send PR
