### ISSUE TITLE
Wechat link in the about pages leads to a empty repository in github

### ISSUE THREAD

**Issue by tewarig** [fossasia/susi.ai#3537]
**Steps to reproduce it**

Go to about page and click on WeChat link  under on many platforms sections in the about page.

**Screenshots of the issue**
![susi](https://user-images.githubusercontent.com/54894783/81554358-46cd4a00-93a4-11ea-824c-fe9573c32a11.gif)

**Would you like to work on the issue?**
yes, I would like to add the new link of the repo, or I can even integrate Susi with WeChat. 
if you want to remove the link i would even do that.

**Comment by anandgupta887** [comment]
Can i work on it??

**Comment by tewarig** [comment]
@anandgupta887 hey,  there is no reply of mentors about what to do in this issue. it is a  hard one we can work on it together. but I have already mentioned I would like to work on that. the real problem is is it even an issue?

**Comment by snitin315** [comment]
This is the expected behavior for now.
