### ISSUE TITLE
Padding not required in dropdown menu.

### ISSUE THREAD

**Issue by arteevraina** [fossasia/susi.ai#3545]
**Actual Behaviour**

Dropdown having `padding-top` and `padding-bottom` in the `dropdown` menu.

**Expected Behaviour**

These padding's should not be present.
![image](https://user-images.githubusercontent.com/43968121/81814749-c135cf80-9546-11ea-8a00-267ce178d40d.png)

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/43968121/81814846-dc084400-9546-11ea-9adf-dabe7b7bd604.png)

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by BLasan** [comment]
@snitin315 Can I work on this?

**Comment by arteevraina** [comment]
@BLasan I am working on this.

**Comment by rahullli** [comment]
Can I work on this project ?

**Comment by BLasan** [comment]
@snitin315 Is this still opened ?

**Comment by snitin315** [comment]
If an issue is green it's open if it's red it's closed.

**Comment by BLasan** [comment]
@snitin315 I would like to work on this

**Comment by snitin315** [comment]
Go ahead
