### ISSUE TITLE
Contributors section is empty in the Team Page when a user is logged in

### ISSUE THREAD

**Issue by 927tanmay** [fossasia/susi.ai#3547]
**Actual Behaviour**

When the user is logged in and visits Team page then the Contributors section is empty but it shows up when the user is not logged in.

**Expected Behaviour**

The Contributors section must show the list of contributors both when the user is logged in as well as logged out.

**Steps to reproduce it**

Login to Susi.ai
Go to the team page.
Now, visit the Contributors section at bottom of the team page.

**LogCat for the issue**

![image](https://user-images.githubusercontent.com/36269283/81860686-b4d06780-9584-11ea-9cb7-e2dd7f326af8.png)

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/36269283/81861078-4e981480-9585-11ea-8cc4-d18d434945f2.png)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by 1209simran** [comment]
Can I work on this issue?

**Comment by 927tanmay** [comment]
@1209simran Sure! You can work on this issue.
