### ISSUE TITLE
Move search bar in navigation bar to center 

### ISSUE THREAD

**Issue by ashwani99** [fossasia/susi.ai#3554]
**Actual Behaviour**
Currently in the navigation bar, the search bar is just placed after the logo. And the other links/buttons are to the right end. The position of the elements can be improved

**Expected Behaviour**
We should place the search bar in the center. More appropriately, we should put the elements of nav bar inside flex container and use spaces evenly between them.

Finally, it should look somewhat like this
![Screenshot from 2020-05-23 00-34-59](https://user-images.githubusercontent.com/12485623/82701372-b5a48000-9c8d-11ea-8d9c-2dabff51c42a.png)

**Would you like to work on the issue?**
Yes, I am working on this

**Comment by elit-altum** [comment]
@ashwani99 Can you explain why do you think this change is necessary?

Thank you!

**Comment by ashwani99** [comment]
@elit-altum This is just to improve the look of the navigation bar. If we place the search bar in the middle, the logo will stand out more. 
Earlier, it was just beside the logo which allowed a lot of unused space right after the search bar. As the logo, search bar and the other link(login, help etc) are not related to each other we should place them separately for better experience
