### ISSUE TITLE
Issue in recaptcha while signing up

### ISSUE THREAD

**Issue by shrey** [fossasia/susi.ai#3564]
**Actual Behaviour**

Recaptcha doesn't load and shows error on the actual site

**Expected Behaviour**
Recaptcha should load and I should be able to signup

**Steps to reproduce it**
>Click on Login
>Click on SIgn up for susi
>Fill in details and click the captcha checkbox

**LogCat for the issue**

**Screenshots of the issue**

![Screenshot 2020-05-31 at 3 32 46 PM](https://user-images.githubusercontent.com/53302612/83349798-28c88900-a355-11ea-9540-f17c969e2b41.jpg)

**Would you like to work on the issue?**

Yes

**Comment by shrey** [comment]
@snitin315 @anishagg17 Are you able to reproduce the error on the website?

**Comment by snitin315** [comment]
Yes but I think it's likely to be a problem on their end.

**Comment by shrey** [comment]
@snitin315 Yeah, so are there any login credentials through which I can check the features provided for a logged in user.

**Comment by codebreakeragr8** [comment]
I am also facing this issue. Any solutions?

**Comment by pg07codes** [comment]
this issue has not been fixed till now . Any updates ?

**Comment by BLasan** [comment]
@snitin315 Is this still occurring?

**Comment by Swayamsvk** [comment]
Yes.

**Comment by Sayan-dev** [comment]
Oh man, it still is not working.....

**Comment by neeraj-2** [comment]
the problem is probably due to captcha key i guess.I tried with my localhost key it worked.
![recaptcha](https://user-images.githubusercontent.com/56186425/91311976-534da500-e7d1-11ea-90b3-b05bc40259d0.PNG)
But i was still not able to sign-up :(

**Comment by hongquan** [comment]
There is also error from JS side:

![image](https://user-images.githubusercontent.com/314607/93011283-2c5be500-f5bf-11ea-9b06-06d19198ded1.png)

**Comment by ItsNidhaan** [comment]
Is this issue still open, if yes then can i work on it?

**Comment by explorigin** [comment]
I've been wanting to try SUSI for months but can't signup. Just try to create a new account. I can't. I'm using FF 82. I see all the JS errors in the console that @hongquan posted.

**Comment by iamareebjamal** [comment]
I recommend to just disable recaptcha as it was implemented without notifying the mobile devs. It doesn't solve any problem on mobile at least and also is causing inconvenience on web. If actions are restricted to verified accounts, the bot problem which captcha service is supposed to solve will automatically be resolved

**Comment by PratishShrivastava** [comment]
If you have disable recaptcha, So now **Sign up is not working.**

![Screenshot (48)](https://user-images.githubusercontent.com/65657554/97754783-1cbc3f80-1b1e-11eb-8538-6fd3a5598ea9.png)
