### ISSUE TITLE
New UI for the Language Select Menu which would include 'add' and 'close' icons

### ISSUE THREAD

**Issue by Akhil-Kashyap** [fossasia/susi.ai#3565]
**Actual Behaviour**

Currently when a user clicks on a language option it just highlights itself. It will be great if we can provide the menu with dynamic icons.

**Expected Behaviour**

We can add some icons which changes accordingly. A 'x' icon will be displayed in front of a selected language option and similarly a '+' in front of unselected options which would change dynamically upon toggling the selections

![Screenshot (123)](https://user-images.githubusercontent.com/42600255/83516758-492f4980-a4f5-11ea-840d-1b82323f88f1.png)

**Would you like to work on the issue?**

Yes, I would love to work on the issue

**Comment by Akhil-Kashyap** [comment]
@anishagg17 @snitin315 Should I go forward adding the icons or the menu should be left as it is??

**Comment by snitin315** [comment]
Low prioriry
