### ISSUE TITLE
Show password not working in login/register

### ISSUE THREAD

**Issue by Tanuj22** [fossasia/susi.ai#3578]
**Actual Behaviour**
The show password eye in login/register is not working

**Expected Behaviour**
The password should be visible when clicked upon

**Steps to reproduce it**
Try to login/register

**Screenshots of the issue**

![pass (online-video-cutter com)](https://user-images.githubusercontent.com/42486853/84072075-3c768e00-a9ec-11ea-9fa3-9c46bb386b6b.gif)

**Would you like to work on the issue?**

Yes

**Comment by Tanuj22** [comment]
@snitin315 Is this a valid issue?

**Comment by snitin315** [comment]
Yes, feel free to fix it.

**Comment by amit2699** [comment]
@Tanuj22  Can I work on this issue #3578

**Comment by 26Vinayak** [comment]
I am working on this issue.

**Comment by ShubhamChaudharyy** [comment]
> I am working on this issue. #3578

but i linked a pull request for this issue 4 days ago

**Comment by ShubhamChaudharyy** [comment]
> According to the [docs](https://www.npmjs.com/package/material-ui-password-field) this should be enabled by default. Is this an issue with the component itself?

actually yes , the pre-installed package wasnt working.. I Linked a pull request can you check @Tanuj22

**Comment by SingingApple** [comment]
Pr #3608 fixed this issue!
