### ISSUE TITLE
Two Category Menus in mobile

### ISSUE THREAD

**Issue by Tanuj22** [fossasia/susi.ai#3582]
**Actual Behaviour**
There are two category menu. One present directly the other in the side drawer

**Expected Behaviour**
There should only be one

**Screenshots of the issue**
![Screenshot from 2020-06-10 19-16-37](https://user-images.githubusercontent.com/42486853/84275858-35b45c00-ab4f-11ea-9cf1-26cd58950850.png)

**Would you like to work on the issue?**
Yes!

**Comment by Tanuj22** [comment]
@anishagg17 what do you think about this issue? Should I work on it?

**Comment by akshatnitd** [comment]
This is not a valid issue. It is intentional.
