### ISSUE TITLE
Show Password not working in settings section(admin) and in Login and Register components

### ISSUE THREAD

**Issue by ShubhamChaudharyy** [fossasia/susi.ai#3584]
**Actual Behaviour**

 Currently if user wants to see the password entered it isnt showing the input password
**Expected Behaviour**

it should show the password when clicked on "eye" icon

**Steps to reproduce it**

1. Go to Profile Section and then switch to Password section. 

**LogCat for the issue**

**Screenshots of the issue**

![Screenshot (210)](https://user-images.githubusercontent.com/43263087/86252889-68db8f80-bbd1-11ea-8908-20c7965d47b4.png)

**Would you like to work on the issue?**

Yes

**Comment by madhur1846** [comment]
can i work on this issue?

**Comment by ShubhamChaudharyy** [comment]
Hey @madhur1846 the issue is solved you can check the PR #3587

**Comment by SingingApple** [comment]
As I can see this issue is still open. Can I work on it?
