### ISSUE TITLE
how to get the susi.ai web chat HTML code

### ISSUE THREAD

**Issue by sysdl132** [fossasia/susi.ai#3585]
I can't find any HTML code about susi webchat in the offical site  https://susi.ai

Can you give me the susi.ai  website online chat HTML code?

**Comment by snitin315** [comment]
susi web client is built with react.js

**Comment by sysdl132** [comment]
ok.is it possible to deploy on netlify?

**Comment by snitin315** [comment]
yes

**Comment by sysdl132** [comment]
(the reply was so fast)
