### ISSUE TITLE
Add package-lock.json to gitignore

### ISSUE THREAD

**Issue by elit-altum** [fossasia/susi.ai#3591]
**Actual Behaviour**

Reference to https://github.com/fossasia/susi.ai/issues/3497
```package-lock.json``` is not added to ```.gitignore```. Some people might use ```npm``` as a package manager & a newly added ```package-lock.json``` file will pollute the PR.

**Expected Behaviour**
```package-lock.json``` should be added to  ```.gitignore```.

**Would you like to work on the issue?**
Yes

**Comment by elit-altum** [comment]
@snitin315 @akshatnitd Would it be okay if I also update ```README.md``` with a specific alert for using ```yarn``` instead of ```npm``` as the package manager ?

On the lines of:
> 🚨 Please only use ```yarn``` for package management and not ```npm```.

Thank You!

**Comment by akshitkr** [comment]
is this solved?

**Comment by Lucifer0x17** [comment]
Is this issue open?

**Comment by yashgagneja** [comment]
Can I work on this issue?

**Comment by salhasalman** [comment]
Shall I work on this issue?
