### ISSUE TITLE
Visibility of Burger Menu for width from 520px to 768px

### ISSUE THREAD

**Issue by neeraj-2** [fossasia/susi.ai#3594]
**Actual Behaviour**
If we go for width less than 520px we have burger menu which works smooth.But for width range from 520px to 768px ,side bar disappears and there is no burger menu.

**Expected Behaviour**

It would be better if we can make burger menu visible for width ranges from 520px to 768px. 
**Steps to reproduce it**

1.After opening site ,go for inpect element and issue can be seen as shown:

**Screenshots of the issue**
![for_width_morethan_768](https://user-images.githubusercontent.com/56186425/91141427-89a1fc00-e6cd-11ea-8ce2-95faff2283ac.png)

![pic2](https://user-images.githubusercontent.com/56186425/91139340-f072e580-e6cc-11ea-9545-529bc8fdbc73.png)
![pic3](https://user-images.githubusercontent.com/56186425/91139350-f1a41280-e6cc-11ea-9d2b-fd6db28057d5.png)

**Would you like to work on the issue?**
Open for all!

**Comment by padmaja-12** [comment]
Can i solve it?

**Comment by neeraj-2** [comment]
Sure,Go ahead

> Can i solve it?

**Comment by naman360** [comment]
@neeraj-2 Can I work on it?
