### ISSUE TITLE
Home page slider images are broken

### ISSUE THREAD

**Issue by dhanushkac** [fossasia/susi.ai#3607]
**Actual Behaviour**

Some slider images are broken 

**Expected Behaviour**

Slider images should be displayed without broken links

**Steps to reproduce it**

Go to the homepage and wait until the slider loads

**More Details**
I found that these are the broken links

https://api.susi.ai/cms/getImage.png?image=6513db361b0f140ca808e71751cef8e2/1562865924087_devices
https://api.susi.ai/cms/getImage.png?image=6513db361b0f140ca808e71751cef8e2/1562866101453_android
https://api.susi.ai/cms/getImage.png?image=6513db361b0f140ca808e71751cef8e2/1563089223499_Trump

**Screenshots of the issue**

![error](https://i.ibb.co/smVJX3M/chrome-WQ6c-PLSn-EJ.png)

**Would you like to work on the issue?**

should be assigned to someone else

**Comment by PratishShrivastava** [comment]
Can I work on this issue.

**Comment by Gautam-Arora24** [comment]
@dhanushkac The links of the images you provided can't be downloaded. Also I inspect the Image on the website. It also can't be downloaded.

**Comment by dhanushkac** [comment]
> @dhanushkac The links of the images you provided can't be downloaded. Also I inspect the Image on the website. It also can't be downloaded. 

Yes those are broken. Those are the links available from the inspect. It is the reason not to load images.

**Comment by Gautam-Arora24** [comment]
So can you provide me the links of the image so that I can add them?

**Comment by dhanushkac** [comment]
> So can you provide me the links of the image so that I can add them?

Sorry, I am not from this team. I saw this bug and reported. Someone from the team should attend on this.

**Comment by Gautam-Arora24** [comment]
@mariobehling Kindly provide me the image link so that I can add to  can add to it

**Comment by imshubh4141** [comment]
The links seem to work just fine. I guess the issue is fixed.

**Comment by Gautam-Arora24** [comment]
Is this issue still persisting? @dhanushkac

**Comment by dhanushkac** [comment]
> Is this issue still persisting? @dhanushkac

Seems like it is fixed now.
