### ISSUE TITLE
npm test and npm run predeploy breaks for devs who donot have yarn installed globally

### ISSUE THREAD

**Issue by ashutoshc8101** [fossasia/susi.ai#3612]
**Actual Behaviour**
`npm test` and `npm run predeploy`  throws error for developers who haven't installed yarn globally

**Expected Behaviour**
`npm test` and `npm run predeploy` should work fine without having to install yarn globally

**Steps to reproduce it**
git clone <forked_repository>
cd susi.ai
npm install 
npm test || npm run predeploy

**Screenshots of the issue**
![Screenshot from 2020-12-10 17-29-56](https://user-images.githubusercontent.com/24855641/101770609-af350300-3b0e-11eb-8a42-383e28947edb.png)
![npm run predeploy](https://user-images.githubusercontent.com/24855641/101770807-05a24180-3b0f-11eb-9481-d3f32d74364b.png)

**Would you like to work on the issue?**
I would like make global installation of yarn optional to work on project for developers.
I will add yarn to `devDependencies` in `package.json`.
So tha dev have a local installation of yarn in project and  `npm test` and `npm run predeploy` work fine after `npm install` command
I will change test and predeploy scripts from `yarn lint` to `yarn || npm lint` so that if *yarn* is not installed script should run with *npm*

**Comment by akshatnitd** [comment]
@ashutoshc8101 Installing `yarn` is a part of the dev setup. We are trying to avoid usage of `npm` as compared to `yarn`, because of its multiple downsides and slowness.

**Comment by ashutoshc8101** [comment]
@akshatnitd should i close this issue and associated PR

**Comment by akshatnitd** [comment]
@ashutoshc8101 Yes please
