### ISSUE TITLE
Dark Mode feature for Entire Website.

### ISSUE THREAD

**Issue by JagjiwanChimkar** [fossasia/susi.ai#3614]
**Actual Behaviour**
Currently, there is no toggling button to switch between light to the dark theme in the HomePage.

**Expected Behaviour**

A Dark and Light Button on HomePage for Entire Website.

**Would you like to work on the issue?**
Yes

**Comment by RASHI3004** [comment]
@JagjiwanChimkar I would like to work on this issue!
