### ISSUE TITLE
"Add AI rules on GitHub" button has broken link 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi.ai#6]
It redirect to this url https://github.com/fossasia/susi_server/blob/development/docs/susi_skill_development_tutorial.md

and it gives 404 error page

**Comment by sakshee-19** [comment]
@mariobehling @isuruAb This issue can be closed. It has been solved.

**Comment by isuruAb** [comment]
@sakshee-19  thank you for pointing out 👍
